<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class AllgaeuSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#a9cbe8',
        'sky_bottom' => '#eef1df',
        'accent' => '#f2c14e',
        'layers' => ['#5f8a5b', '#3f6b46', '#2c4a33'],
        'water' => '#3a7ca5',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'allgaeu'],
            [
                'name' => 'Allgäu',
                'type' => 'Reisegebiet',
                'country' => 'Deutschland',
                'federal_state' => 'Bayern',
                'short_description' => 'Alpenpanorama, Königsschlösser und Bergseen',
                'description' => "Das Allgäu vereint majestätische Alpengipfel, sanfte Hügellandschaften und die weltberühmten Königsschlösser Neuschwanstein und Hohenschwangau. Zwischen Füssen, Oberstdorf und Kempten wechseln sich glasklare Bergseen, tosende Wasserfälle und urige Almhütten ab.\n\nDie Region ist bekannt für ihre Käsereitradition, gut ausgebaute Wander- und Radwege sowie eine hohe Dichte an familienfreundlichen Ausflugszielen. Vom gemütlichen Uferspaziergang bis zur alpinen Gipfeltour ist im Allgäu für jeden Anspruch etwas dabei.",
                'hero_image' => 'regions/allgaeu/allgaeu-1.jpg',
                'latitude' => 47.5580,
                'longitude' => 10.2200,
                'best_travel_time' => 'Juni bis September für Wandern, Dezember bis März für Wintersport',
                'arrival_information' => 'Nächstgelegene Flughäfen: Memmingen, München und Friedrichshafen. Gute Zuganbindung über Kempten und Füssen, Autobahnausfahrten der A7.',
                'seo_title' => 'Allgäu Reisetipps – Schlösser, Seen & Berge | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele im Allgäu: Königsschlösser, Bergseen, Klammen und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 2,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/allgaeu', 'allgaeu', 'mountains', $this->palette, 'Alpenpanorama mit grünen Wiesen im Allgäu', true, 0);
        MediaSeederHelper::attach($region, 'regions/allgaeu', 'allgaeu', 'castle', $this->palette, 'Schlosssilhouette vor Bergkulisse im Allgäu', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['natur', 'wandern', 'familie', 'kultur'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' im Allgäu | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Schloss Neuschwanstein',
                'short_description' => 'Das weltberühmte Märchenschloss König Ludwigs II.',
                'description' => "Schloss Neuschwanstein ist das meistfotografierte Bauwerk Deutschlands und diente als Vorbild für zahlreiche Märchenschlösser weltweit. König Ludwig II. ließ die Anlage im 19. Jahrhundert im romantisch-mittelalterlichen Stil erbauen, bewohnte sie jedoch nur wenige Monate.\n\nDie Innenräume lassen sich im Rahmen einer Führung besichtigen, die vorherige Online-Reservierung wird dringend empfohlen. Der Blick von der nahen Marienbrücke auf das Schloss vor den Ammergauer Alpen zählt zu den bekanntesten Postkartenmotiven Bayerns.",
                'location_name' => 'Schwangau',
                'address' => 'Neuschwansteinstraße 20, 87645 Schwangau',
                'lat' => 47.5576, 'lng' => 10.7498,
                'duration' => '2–3 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 21 €, Führung erforderlich',
                'opening_hours' => 'Täglich 9–18 Uhr (Winter bis 15:30 Uhr)',
                'parking_information' => 'Kostenpflichtige Parkplätze in Hohenschwangau',
                'arrival_information' => 'Fußweg oder Kutsche ab Hohenschwangau, ca. 30–40 Minuten Aufstieg',
                'website_url' => 'https://www.neuschwanstein.de',
                'phone' => '+49 8362 930830',
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig, besonders schön im Herbst',
                'highlights' => ['Meistfotografiertes Schloss Deutschlands', 'Blick von der Marienbrücke', 'Vorbild für Märchenschlösser weltweit'],
                'categories' => ['kultur-geschichte', 'familie-ausflug'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Schloss Hohenschwangau',
                'short_description' => 'Gelbes Schloss der Wittelsbacher mit Blick auf Neuschwanstein.',
                'description' => "Schloss Hohenschwangau war die Kindheitsresidenz von König Ludwig II. und liegt dem berühmteren Neuschwanstein direkt gegenüber. Die gelb getünchte Anlage aus dem 19. Jahrhundert zeigt weitgehend original erhaltene Wohnräume der Wittelsbacher Familie.\n\nDa Hohenschwangau meist weniger überlaufen ist als Neuschwanstein, lohnt sich ein Besuch als ruhigere Alternative mit ebenso beeindruckendem Blick auf den Alpsee und die umliegenden Berge.",
                'location_name' => 'Schwangau',
                'address' => 'Alpseestraße 30, 87645 Schwangau',
                'lat' => 47.5514, 'lng' => 10.7391,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 19 €, Führung erforderlich',
                'opening_hours' => 'Täglich 9–18 Uhr (Winter bis 15:30 Uhr)',
                'parking_information' => 'Kostenpflichtige Parkplätze im Ort Hohenschwangau',
                'arrival_information' => 'Kurzer Fußweg vom Ortszentrum Hohenschwangau',
                'website_url' => 'https://www.hohenschwangau.de',
                'phone' => '+49 8362 930830',
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Original erhaltene Wohnräume', 'Weniger überlaufen als Neuschwanstein', 'Blick auf den Alpsee'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Hopfensee',
                'short_description' => 'Sonniger Badesee bei Füssen mit Blick auf die Allgäuer Alpen.',
                'description' => "Der Hopfensee gilt als einer der wärmsten Seen im Allgäu und ist bei Sonnenuntergang für seine spektakulären Farben über der Bergkulisse bekannt. Ein rund sechs Kilometer langer Uferweg umrundet den See fast vollständig und eignet sich für Spaziergänge und Radtouren.\n\nMehrere Liegewiesen, Strandbäder und Bootsverleihe machen den Hopfensee im Sommer zu einem beliebten Familienziel. Auch Stand-up-Paddling und Segeln sind hier verbreitet.",
                'location_name' => 'Hopfen am See, Füssen',
                'address' => 'Uferweg, 87629 Füssen',
                'lat' => 47.5967, 'lng' => 10.6631,
                'duration' => '2–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Freier Zugang, Strandbäder teils kostenpflichtig',
                'opening_hours' => 'Ganzjährig frei zugänglich',
                'parking_information' => 'Parkplätze rund um den See',
                'arrival_information' => 'Mit dem Auto oder Bus ab Füssen in wenigen Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Wärmster See der Region', 'Rundweg von ca. 6 Kilometern', 'Spektakuläre Sonnenuntergänge'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'natur', 'seen', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Forggensee',
                'short_description' => 'Bayerns fünftgrößter See mit Rundweg und Dampferrundfahrten.',
                'description' => "Der Forggensee ist ein künstlich angelegter Stausee der Lech und bietet mit seinem rund 30 Kilometer langen Uferweg eines der schönsten Rad- und Wandergebiete im Allgäu. Von den Ufern eröffnen sich immer wieder Ausblicke auf Neuschwanstein und die umliegenden Berge.\n\nIm Sommer verkehren Ausflugsschiffe über den See, im Winter wird der abgelassene See teilweise zur Wanderfläche. Mehrere Badestellen laden zwischen Mai und September zum Schwimmen ein.",
                'location_name' => 'Füssen',
                'address' => 'Uferpromenade, 87629 Füssen',
                'lat' => 47.6167, 'lng' => 10.7333,
                'duration' => '2–5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos, Schifffahrt kostenpflichtig',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Mehrere Parkplätze entlang des Ufers',
                'arrival_information' => 'Mit dem Auto oder Bus ab Füssen erreichbar',
                'website_url' => 'https://www.forggensee-schifffahrt.de',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Fünftgrößter See Bayerns', '30 Kilometer langer Uferweg', 'Blick auf Neuschwanstein'],
                'categories' => ['seen-baden', 'natur-landschaft'],
                'labels' => ['familie', 'natur', 'seen', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Breitachklamm',
                'short_description' => 'Eine der tiefsten und spektakulärsten Felsschluchten Mitteleuropas.',
                'description' => "Die Breitachklamm bei Oberstdorf zählt zu den spektakulärsten Felsschluchten Mitteleuropas. Auf gesicherten Stegen und Tunneln führt der Weg dicht am tosenden Wasser vorbei, an manchen Stellen ragen die Felswände bis zu 150 Meter senkrecht empor.\n\nDer knapp zweistündige Rundweg ist technisch nicht schwierig, aber wegen der Nässe und Kälte in der Schlucht festes Schuhwerk und wärmere Kleidung empfehlenswert. Besonders im Sommer bietet die Klamm eine willkommene Abkühlung.",
                'location_name' => 'Oberstdorf',
                'address' => 'Breitachklamm 1, 87567 Oberstdorf',
                'lat' => 47.3931, 'lng' => 10.1319,
                'duration' => '1–2 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Erwachsene ca. 6 €',
                'opening_hours' => 'Ganzjährig, saisonal abweichende Öffnungszeiten',
                'parking_information' => 'Parkplatz am Eingang der Klamm',
                'arrival_information' => 'Mit dem Auto oder Bus ab Oberstdorf erreichbar',
                'website_url' => 'https://www.breitachklamm.com',
                'phone' => '+49 8322 4879',
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Bis zu 150 Meter hohe Felswände', 'Gesicherte Stege und Tunnel', 'Eine der tiefsten Klammen Europas'],
                'categories' => ['natur-landschaft', 'wandern'],
                'labels' => ['natur', 'aktiv', 'familie', 'geheimtipp'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Oberstdorf',
                'short_description' => 'Südlichster Ort Deutschlands mit alpinem Bergpanorama.',
                'description' => "Oberstdorf ist der südlichste Ort Deutschlands und liegt eingebettet zwischen den Gipfeln der Allgäuer Alpen. Der historische Ortskern mit seinen Chalets und Fußgängerzonen bildet den Ausgangspunkt für zahlreiche Wander-, Rad- und Skitouren.\n\nAls bekannter Wintersportort mit Skisprungschanze und internationalen Wettkämpfen ist Oberstdorf auch im Sommer ein beliebtes Ziel für Bergsportler und Erholungssuchende. Mehrere Seilbahnen erschließen die umliegenden Gipfel bequem.",
                'location_name' => 'Oberstdorf',
                'address' => 'Marktplatz, 87561 Oberstdorf',
                'lat' => 47.4089, 'lng' => 10.2789,
                'duration' => '2–4 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Mehrere Parkhäuser im Ortszentrum',
                'arrival_information' => 'Endstation der Bahnlinie ab Immenstadt, gut mit dem Zug erreichbar',
                'website_url' => 'https://www.oberstdorf.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Südlichster Ort Deutschlands', 'Ausgangspunkt zahlreicher Bergtouren', 'Bekannter Wintersportort'],
                'categories' => ['familie-ausflug', 'wandern'],
                'labels' => ['familie', 'aktiv', 'winter'],
                'motif' => 'town',
            ],
            [
                'title' => 'Nebelhorn',
                'short_description' => 'Aussichtsberg über Oberstdorf mit Gipfelrestaurant.',
                'description' => "Das Nebelhorn ist mit 2.224 Metern der höchste öffentlich zugängliche Gipfel im Gebiet um Oberstdorf und bietet ein weites Panorama über die Allgäuer und Lechtaler Alpen. Die Nebelhornbahn bringt Besucher bequem in mehreren Sektionen fast bis zum Gipfel.\n\nOben angekommen führen leichte Wege zu mehreren Aussichtspunkten, außerdem starten hier anspruchsvollere Bergtouren, etwa zum Gaisalpsee. Ein Gipfelrestaurant lädt zur Einkehr mit Panoramablick ein.",
                'location_name' => 'Oberstdorf',
                'address' => 'Nebelhornbahn, 87561 Oberstdorf',
                'lat' => 47.3903, 'lng' => 10.3308,
                'duration' => '3–6 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Seilbahn ab ca. 34 € Hin- und Rückfahrt',
                'opening_hours' => 'Ganzjährig, saisonal abweichend',
                'parking_information' => 'Parkplatz an der Talstation',
                'arrival_information' => 'Mit der Nebelhornbahn ab Oberstdorf',
                'website_url' => 'https://www.nebelhorn.de',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Juni bis Oktober, Dezember bis April',
                'highlights' => ['Höchster öffentlich zugänglicher Gipfel', 'Panorama über zwei Alpenländer', 'Gipfelrestaurant'],
                'categories' => ['aussicht-panorama', 'wandern'],
                'labels' => ['wandern', 'natur', 'aktiv', 'winter'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Alpsee',
                'short_description' => 'Klarer Bergsee direkt unterhalb der Königsschlösser.',
                'description' => "Der Alpsee bei Hohenschwangau liegt malerisch zwischen bewaldeten Hängen direkt unterhalb der Königsschlösser. Ein gut ausgebauter Rundweg von etwa fünf Kilometern führt einmal komplett um den See und bietet immer wieder Ausblicke auf Neuschwanstein.\n\nDas glasklare, tiefblaue Wasser lädt im Sommer zum Baden ein, mehrere kleine Liegewiesen und Stege bieten Zugang zum See. Der Rundweg ist auch für Familien mit Kindern gut geeignet.",
                'location_name' => 'Hohenschwangau, Schwangau',
                'address' => 'Alpseeuferweg, 87645 Schwangau',
                'lat' => 47.5511, 'lng' => 10.7275,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplätze in Hohenschwangau',
                'arrival_information' => 'Fußläufig vom Ortszentrum Hohenschwangau erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Rundweg mit Schlossblick', 'Glasklares, tiefblaues Wasser', 'Familienfreundlicher Weg'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'natur', 'seen', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Großer Alpsee',
                'short_description' => 'Größter Voralpensee im Allgäu bei Immenstadt.',
                'description' => "Der Große Alpsee bei Immenstadt ist der größte Voralpensee im Allgäu und beliebtes Ziel für Wassersport, Baden und Spaziergänge. Der etwa neun Kilometer lange Uferweg eignet sich hervorragend für Radtouren mit der ganzen Familie.\n\nMehrere Strandbäder, ein Bootsverleih und Restaurants direkt am Wasser machen den See zu einem vielseitigen Ausflugsziel. Von den Ufern aus reicht der Blick bis zu den Gipfeln des Alpenhauptkamms.",
                'location_name' => 'Immenstadt',
                'address' => 'Seestraße, 87509 Immenstadt',
                'lat' => 47.5578, 'lng' => 10.2214,
                'duration' => '2–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Freier Zugang, Strandbäder kostenpflichtig',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Mehrere Parkplätze rund um den See',
                'arrival_information' => 'Mit Bahn oder Auto bis Immenstadt, See in Gehnähe',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Größter Voralpensee im Allgäu', 'Neun Kilometer langer Uferweg', 'Bootsverleih und Strandbäder'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'natur', 'seen', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Kempten',
                'short_description' => 'Älteste Stadt Bayerns mit römischen Wurzeln.',
                'description' => "Kempten gilt als älteste Stadt Bayerns und blickt auf eine über 2.000-jährige Geschichte zurück, die bis in die römische Provinz Rätien reicht. Die Ausgrabungsstätte Cambodunum lässt die römische Vergangenheit unmittelbar erlebbar werden.\n\nDie barocke Altstadt mit Residenz, Hofgarten und St.-Lorenz-Basilika lädt zum Bummeln ein. Zahlreiche Cafés und Geschäfte in der Fußgängerzone machen Kempten zu einem lebendigen Zentrum des Allgäus.",
                'location_name' => 'Kempten',
                'address' => 'Rathausplatz, 87435 Kempten',
                'lat' => 47.7267, 'lng' => 10.3167,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Museen kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Mehrere Parkhäuser im Stadtzentrum',
                'arrival_information' => 'Guter Bahnanschluss, Bahnhof Kempten zentral gelegen',
                'website_url' => 'https://www.kempten.de',
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Älteste Stadt Bayerns', 'Römische Ausgrabungsstätte Cambodunum', 'Barocke Altstadt'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Füssen',
                'short_description' => 'Historische Altstadt am Fuße der Königsschlösser.',
                'description' => "Füssen liegt am Fuße der Allgäuer Alpen unweit der Königsschlösser und punktet mit einer gut erhaltenen Altstadt aus Kaufmannshäusern, Klosteranlagen und dem Hohen Schloss. Die Fußgängerzone lädt zu einem entspannten Stadtbummel abseits des Schlosstrubels ein.\n\nDas Kloster St. Mang und die Lechfälle direkt in der Stadt sind zusätzliche Ziele für einen Spaziergang. Füssen eignet sich hervorragend als ruhigerer Ausgangspunkt für Ausflüge in die umliegende Bergwelt.",
                'location_name' => 'Füssen',
                'address' => 'Reichenstraße, 87629 Füssen',
                'lat' => 47.5722, 'lng' => 10.7019,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser im Stadtzentrum',
                'arrival_information' => 'Endstation der Bahnlinie ab München/Kaufbeuren',
                'website_url' => 'https://www.fuessen.de',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Historische Altstadt', 'Kloster St. Mang', 'Lechfälle mitten in der Stadt'],
                'categories' => ['kultur-geschichte', 'familie-ausflug'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Tegelberg',
                'short_description' => 'Aussichtsberg mit Seilbahn, Rodelbahn und Drachenfliegern.',
                'description' => "Der Tegelberg oberhalb von Schwangau bietet mit der Tegelbergbahn einen bequemen Zugang zu einem grandiosen Panorama über das Alpenvorland bis zu den Königsschlössern. Der Berg ist außerdem bekannt als einer der besten Startplätze für Gleitschirm- und Drachenflieger in Bayern.\n\nAn der Bergstation starten mehrere Wanderwege, unter anderem zur Tegelbergalm. Im Sommer lockt zusätzlich eine Sommerrodelbahn an der Talstation Familien mit Kindern an.",
                'location_name' => 'Schwangau',
                'address' => 'Tegelbergbahn, 87645 Schwangau',
                'lat' => 47.5606, 'lng' => 10.7003,
                'duration' => '2–4 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Seilbahn ab ca. 23 € Hin- und Rückfahrt',
                'opening_hours' => 'Ganzjährig, saisonal abweichend',
                'parking_information' => 'Parkplatz an der Talstation',
                'arrival_information' => 'Mit der Tegelbergbahn ab Schwangau',
                'website_url' => 'https://www.tegelbergbahn.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Mai bis Oktober, Winter für Rodelbahn',
                'highlights' => ['Panorama bis zu den Königsschlössern', 'Beliebter Startplatz für Gleitschirmflieger', 'Sommerrodelbahn im Tal'],
                'categories' => ['aussicht-panorama', 'familie-ausflug'],
                'labels' => ['familie', 'aktiv', 'natur'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Skywalk Allgäu',
                'short_description' => 'Erlebnispfad mit Hängebrücke und Aussichtsplattformen.',
                'description' => "Der Skywalk Allgäu am Grünten verbindet einen Walderlebnispfad mit spektakulären Aussichtsplattformen und einer Hängebrücke über eine tiefe Schlucht. Der Rundweg ist auch für Familien mit Kindern gut machbar und bietet zahlreiche Stationen zum Entdecken.\n\nHöhepunkt ist die freischwebende Aussichtsplattform mit Panoramablick auf das Alpenvorland. Wetterfeste Kleidung und festes Schuhwerk werden empfohlen, da der Weg naturbelassen ist.",
                'location_name' => 'Rettenberg',
                'address' => 'Skywalk Allgäu, 87549 Rettenberg',
                'lat' => 47.5931, 'lng' => 10.3306,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 8 €',
                'opening_hours' => 'April bis November, täglich 10–17 Uhr',
                'parking_information' => 'Parkplatz am Eingang',
                'arrival_information' => 'Mit dem Auto über Rettenberg erreichbar',
                'website_url' => 'https://www.skywalk-allgaeu.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'April bis November',
                'highlights' => ['Freischwebende Aussichtsplattform', 'Hängebrücke über eine Schlucht', 'Familienfreundlicher Erlebnispfad'],
                'categories' => ['aussicht-panorama', 'familie-ausflug'],
                'labels' => ['familie', 'aktiv', 'geheimtipp'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Hündle',
                'short_description' => 'Familienfreundlicher Aussichtsberg über Oberstaufen.',
                'description' => "Das Hündle oberhalb von Oberstaufen ist ein beliebter Familienberg mit sanftem Gelände und weitem Panorama über das Alpenvorland bis zum Bodensee. Die Hündlebahn erschließt den Berg bequem, oben angekommen laden mehrere leichte Rundwege zum Erkunden ein.\n\nEin Barfußweg und ein Alpsee-Spielplatz machen das Hündle besonders für Kinder attraktiv. Im Winter ist der Berg ein kleines, familienfreundliches Skigebiet.",
                'location_name' => 'Oberstaufen',
                'address' => 'Hündlebahn, 87534 Oberstaufen',
                'lat' => 47.5461, 'lng' => 10.0197,
                'duration' => '2–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Seilbahn ab ca. 15 € Hin- und Rückfahrt',
                'opening_hours' => 'Ganzjährig, saisonal abweichend',
                'parking_information' => 'Parkplatz an der Talstation Steibis',
                'arrival_information' => 'Mit der Hündlebahn ab Steibis bei Oberstaufen',
                'website_url' => 'https://www.huendle.de',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Mai bis Oktober, Dezember bis März',
                'highlights' => ['Barfußweg für Kinder', 'Panorama bis zum Bodensee', 'Familienfreundliches Wintersportgebiet'],
                'categories' => ['familie-ausflug', 'aussicht-panorama'],
                'labels' => ['familie', 'natur', 'winter'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Starzlachklamm',
                'short_description' => 'Wildromantische Klamm bei Burgberg mit Steganlage.',
                'description' => "Die Starzlachklamm bei Burgberg im Allgäu ist eine wildromantische, weniger bekannte Schlucht mit gut gesicherten Stegen entlang des tosenden Wassers. Moosbewachsene Felsen und mehrere kleine Wasserfälle prägen den rund einstündigen Rundweg.\n\nIm Vergleich zur bekannteren Breitachklamm ist die Starzlachklamm deutlich ruhiger und eignet sich gut als Geheimtipp für einen kurzen, erfrischenden Ausflug.",
                'location_name' => 'Burgberg im Allgäu',
                'address' => 'Klammweg, 87545 Burgberg im Allgäu',
                'lat' => 47.5514, 'lng' => 10.3467,
                'duration' => '1 Stunde',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'April bis Oktober',
                'parking_information' => 'Kleiner Parkplatz am Eingang',
                'arrival_information' => 'Mit dem Auto über Burgberg erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Wildromantische, ruhige Schlucht', 'Gut gesicherte Stege', 'Kleine Wasserfälle unterwegs'],
                'categories' => ['natur-landschaft', 'wandern'],
                'labels' => ['geheimtipp', 'natur', 'familie'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Eistobel',
                'short_description' => 'Tief eingeschnittene Klamm mit türkisfarbenem Wasser.',
                'description' => "Der Eistobel bei Isny ist eine der eindrucksvollsten Klammen im westlichen Allgäu. Die Argen hat sich hier tief in den Nagelfluhfelsen gegraben und ein türkisfarbenes, mäanderndes Flussbett geformt, das von gesicherten Wegen aus bestaunt werden kann.\n\nDer rund zweistündige Rundweg führt über mehrere Brücken und Aussichtspunkte hoch über der Schlucht. Der Naturschutzgebiet-Status sorgt für eine besonders ursprüngliche Waldlandschaft.",
                'location_name' => 'Isny im Allgäu',
                'address' => 'Eistobel, 88316 Isny im Allgäu',
                'lat' => 47.6867, 'lng' => 10.0181,
                'duration' => '2 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig, bei Glätte gesperrt',
                'parking_information' => 'Parkplatz am Wanderparkplatz Rohrdorf',
                'arrival_information' => 'Mit dem Auto über Isny und Rohrdorf erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Türkisfarbenes, mäanderndes Flussbett', 'Naturschutzgebiet', 'Mehrere Aussichtspunkte hoch über der Schlucht'],
                'categories' => ['natur-landschaft', 'wandern'],
                'labels' => ['natur', 'geheimtipp', 'aktiv'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Alpsee Bergwelt',
                'short_description' => 'Freizeitpark und Wanderparadies bei Immenstadt.',
                'description' => "Die Alpsee Bergwelt in Immenstadt verbindet Bergerlebnis und Freizeitpark: Neben klassischen Wanderwegen gibt es einen Baumwipfelpfad, Sommerrodelbahnen und einen Erlebnispark für Kinder. Die Mittagbahn bringt Besucher bequem auf den Berg.\n\nDamit eignet sich die Alpsee Bergwelt besonders für Familien, die Naturerlebnis und actionreiche Attraktionen an einem Ort verbinden möchten. Der Blick auf den Großen Alpsee von oben ist ein zusätzliches Highlight.",
                'location_name' => 'Immenstadt',
                'address' => 'Mittagbahn, 87509 Immenstadt',
                'lat' => 47.5486, 'lng' => 10.2072,
                'duration' => '3–5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kombiticket ab ca. 25 €',
                'opening_hours' => 'April bis Oktober, saisonal abweichend',
                'parking_information' => 'Parkplatz an der Talstation',
                'arrival_information' => 'Mit der Mittagbahn ab Immenstadt',
                'website_url' => 'https://www.alpsee-bergwelt.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Baumwipfelpfad', 'Sommerrodelbahnen', 'Blick auf den Großen Alpsee'],
                'categories' => ['familie-ausflug', 'aussicht-panorama'],
                'labels' => ['familie', 'aktiv'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Lechfall',
                'short_description' => 'Tosender Wasserfall des Lechs mitten in Füssen.',
                'description' => "Der Lechfall liegt nur wenige Gehminuten von der Füssener Altstadt entfernt und ist damit eines der am leichtesten erreichbaren Naturschauspiele im Allgäu. Der Lech stürzt hier über eine mehrstufige Felskante und hat sich tief in den Fels eingeschnitten.\n\nEine kleine Brücke direkt über dem Fall bietet einen eindrucksvollen Blick auf die Wassermassen. Der Abstecher lässt sich gut mit einem Stadtbummel durch Füssen verbinden.",
                'location_name' => 'Füssen',
                'address' => 'Alatseestraße, 87629 Füssen',
                'lat' => 47.5622, 'lng' => 10.6994,
                'duration' => '30–60 Minuten',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze im Füssener Stadtzentrum',
                'arrival_information' => 'Fußläufig von der Füssener Altstadt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Mitten in Füssen gelegen', 'Mehrstufige Felskante', 'Gut mit Stadtbummel kombinierbar'],
                'categories' => ['natur-landschaft'],
                'labels' => ['natur', 'familie', 'geheimtipp'],
                'motif' => 'waterfall',
            ],
            [
                'title' => 'Buchenegger Wasserfälle',
                'short_description' => 'Familienfreundlicher Wasserfallweg im Naturschutzgebiet.',
                'description' => "Die Buchenegger Wasserfälle bilden eine Kaskade aus mehreren kleinen und mittleren Fällen entlang eines gut ausgebauten Rundwegs im Naturschutzgebiet bei Buchenberg. Der Weg ist kurz, größtenteils flach und damit ideal für einen Ausflug mit kleinen Kindern.\n\nHolzstege und Aussichtspunkte führen direkt an die schönsten Wasserstellen heran. Ein angrenzender Wald- und Erlebnisspielplatz rundet das Ausflugsziel für Familien ab.",
                'location_name' => 'Buchenberg',
                'address' => 'Buchegger Wasserfälle, 87474 Buchenberg',
                'lat' => 47.6764, 'lng' => 10.3517,
                'duration' => '1 Stunde',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Wanderparkplatz am Ortseingang',
                'arrival_information' => 'Mit dem Auto über Buchenberg erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Kaskade mehrerer kleiner Wasserfälle', 'Kurzer, familienfreundlicher Rundweg', 'Angrenzender Waldspielplatz'],
                'categories' => ['natur-landschaft', 'familie-ausflug'],
                'labels' => ['natur', 'familie', 'geheimtipp'],
                'motif' => 'waterfall',
            ],
            [
                'title' => 'Fellhorn',
                'short_description' => 'Grenzüberschreitendes Wander- und Skigebiet bei Oberstdorf.',
                'description' => "Das Fellhorn liegt im Grenzgebiet zwischen Deutschland und Österreich und bietet eines der schneesichersten Skigebiete des Allgäus sowie im Sommer ein weitläufiges Wandergebiet. Von der Bergstation führen zahlreiche Wege zu Aussichtspunkten und Almhütten.\n\nBesonders beliebt ist die Wanderung weiter zum benachbarten Söllereck oder hinüber ins österreichische Kleinwalsertal. Mehrere Almen entlang der Wege laden zur urigen Einkehr ein.",
                'location_name' => 'Oberstdorf',
                'address' => 'Fellhornbahn, 87561 Oberstdorf',
                'lat' => 47.3492, 'lng' => 10.1908,
                'duration' => '3–6 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Seilbahn ab ca. 28 € Hin- und Rückfahrt',
                'opening_hours' => 'Juni bis Oktober, Dezember bis April',
                'parking_information' => 'Parkplatz an der Talstation',
                'arrival_information' => 'Mit der Fellhornbahn ab Oberstdorf',
                'website_url' => 'https://www.fellhorn-kanzelwand.de',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Juni bis Oktober, Dezember bis April',
                'highlights' => ['Grenzüberschreitendes Wandergebiet', 'Verbindung ins Kleinwalsertal', 'Zahlreiche Almhütten'],
                'categories' => ['wandern', 'aussicht-panorama'],
                'labels' => ['wandern', 'natur', 'aktiv', 'winter'],
                'motif' => 'mountains',
            ],
        ];
    }
}
