<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class DuesseldorfSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#9db8d0',
        'sky_bottom' => '#e8e4da',
        'accent' => '#d4a24a',
        'layers' => ['#6a6a70', '#4a4a50', '#2a2a30'],
        'water' => '#3a6a8a',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'duesseldorf'],
            [
                'name' => 'Düsseldorf',
                'type' => 'Stadt',
                'country' => 'Deutschland',
                'federal_state' => 'Nordrhein-Westfalen',
                'short_description' => 'Modemetropole am Rhein mit Altstadt und Kunstszene',
                'description' => "Düsseldorf verbindet rheinische Geselligkeit mit internationalem Flair. Die Altstadt gilt mit ihrer hohen Dichte an Brauhäusern als „längste Theke der Welt“, während die Königsallee mit ihren Luxusboutiquen und dem historischen Stadtgraben für Eleganz steht.\n\nAls Kunst- und Modestadt beherbergt Düsseldorf bedeutende Museen wie die Kunstsammlung Nordrhein-Westfalen und ein pulsierendes Ausgehviertel im Medienhafen mit spektakulärer moderner Architektur. Grünflächen wie der Hofgarten und der Nordpark mit seinem japanischen Garten bieten ruhige Rückzugsorte mitten in der Stadt.",
                'hero_image' => 'regions/duesseldorf/duesseldorf-1.jpg',
                'latitude' => 51.2277,
                'longitude' => 6.7735,
                'best_travel_time' => 'Ganzjährig, besonders Mai bis September',
                'arrival_information' => 'Internationaler Flughafen Düsseldorf mit direkter Bahnanbindung zum Hauptbahnhof. Zentrale Lage im ICE-Netz, Autobahnanschluss über A3, A44, A46 und A52.',
                'seo_title' => 'Düsseldorf Reisetipps – Altstadt, Kunst & Rhein | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele in Düsseldorf: Altstadt, Museen, Rheinufer und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 5,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/duesseldorf', 'duesseldorf', 'town', $this->palette, 'Skyline von Düsseldorf am Rhein', true, 0);
        MediaSeederHelper::attach($region, 'regions/duesseldorf', 'duesseldorf', 'canyon', $this->palette, 'Rheinufer in Düsseldorf', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['kultur', 'familie', 'kulinarik'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' in Düsseldorf | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Altstadt Düsseldorf',
                'short_description' => 'Die „längste Theke der Welt“ mit historischen Brauhäusern.',
                'description' => "Die Düsseldorfer Altstadt ist berühmt für ihre hohe Dichte an traditionellen Brauhäusern, in denen das obergärige Altbier direkt aus dem Fass serviert wird. Enge Gassen, historische Fassaden und ein lebendiges Treiben prägen das Viertel zu jeder Tageszeit.\n\nNeben den Brauhäusern laden zahlreiche Boutiquen, Galerien und Cafés zum Bummeln ein. Am Rheinufer direkt neben der Altstadt lässt sich der Abend bei einem Spaziergang mit Blick auf den Fluss ausklingen.",
                'location_name' => 'Düsseldorf Altstadt',
                'address' => 'Bolkerstraße, 40213 Düsseldorf',
                'lat' => 51.2270, 'lng' => 6.7735,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Verzehr in Brauhäusern kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser rund um die Altstadt',
                'arrival_information' => 'Fußläufig vom Hauptbahnhof in ca. 20 Minuten oder mit der Bahn erreichbar',
                'website_url' => 'https://www.duesseldorf-tourismus.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['„Längste Theke der Welt“', 'Traditionelle Altbier-Brauhäuser', 'Lebendiges Nachtleben'],
                'categories' => ['kulinarik', 'kultur-geschichte'],
                'labels' => ['kulinarik', 'kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Königsallee',
                'short_description' => 'Elegante Einkaufsstraße mit historischem Stadtgraben.',
                'description' => "Die Königsallee, liebevoll „Kö“ genannt, ist die bekannteste Einkaufsstraße Düsseldorfs und Synonym für Eleganz und Luxus. Ein von Kastanien gesäumter Wassergraben teilt die Straße in zwei Promenaden mit exklusiven Boutiquen und Passagen.\n\nDie prächtigen Gründerzeitgebäude entlang der Kö und der elegante Kö-Bogen mit moderner Architektur machen einen Spaziergang zu einem Erlebnis auch für Nicht-Shopper. Cafés mit Blick auf den Graben laden zum Verweilen ein.",
                'location_name' => 'Düsseldorf',
                'address' => 'Königsallee, 40212 Düsseldorf',
                'lat' => 51.2233, 'lng' => 6.7838,
                'duration' => '1–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Geschäfte meist Mo–Sa 10–20 Uhr',
                'parking_information' => 'Parkhäuser entlang der Königsallee',
                'arrival_information' => 'Fußläufig vom Hauptbahnhof in ca. 10 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Kastaniengesäumter Stadtgraben', 'Exklusive Boutiquen und Passagen', 'Moderner Kö-Bogen'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Rheinturm',
                'short_description' => 'Aussichtsturm mit Panoramablick über Düsseldorf.',
                'description' => "Der Rheinturm ist mit rund 240 Metern das höchste Bauwerk Düsseldorfs und bietet von seiner Aussichtsplattform einen weiten Panoramablick über die Stadt und den Rhein. Bei guter Sicht reicht der Blick bis zum Kölner Dom.\n\nEin Drehrestaurant im Turm ermöglicht das Speisen mit sich langsam änderndem Panorama. Die markante Lichtinstallation am Turmschaft fungiert zugleich als größte Digitaluhr der Welt.",
                'location_name' => 'Düsseldorf',
                'address' => 'Stromstraße 20, 40221 Düsseldorf',
                'lat' => 51.2217, 'lng' => 6.7695,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 14 €',
                'opening_hours' => 'Täglich 10–23:30 Uhr',
                'parking_information' => 'Parkplatz am Rheinturm',
                'arrival_information' => 'Fußläufig vom Medienhafen oder der Altstadt erreichbar',
                'website_url' => 'https://rheinturm.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Panoramablick bis zum Kölner Dom', 'Drehrestaurant im Turm', 'Größte Digitaluhr der Welt'],
                'categories' => ['aussicht-panorama'],
                'labels' => ['familie', 'kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Medienhafen',
                'short_description' => 'Moderner Hafen mit spektakulärer Architektur.',
                'description' => "Der Medienhafen hat sich vom historischen Handelshafen zu einem der architektonisch spannendsten Viertel Düsseldorfs entwickelt. Bauten renommierter Architekten wie Frank Gehry mit seinen unverwechselbaren Neuer-Zollhof-Gebäuden prägen das Ufer.\n\nZahlreiche Restaurants und Bars mit Blick auf das Hafenbecken machen den Medienhafen besonders abends zu einem beliebten Ausgehviertel. Ein Spaziergang entlang der Kaimauern zeigt die Kontraste zwischen historischen Speichergebäuden und ultramoderner Architektur.",
                'location_name' => 'Düsseldorf',
                'address' => 'Speditionstraße, 40221 Düsseldorf',
                'lat' => 51.2178, 'lng' => 6.7649,
                'duration' => '1–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser im Medienhafen',
                'arrival_information' => 'Fußläufig von der Altstadt in ca. 15 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Mai bis September',
                'highlights' => ['Gehry-Bauten am Neuer Zollhof', 'Restaurants mit Hafenblick', 'Kontrast aus Alt und Neu'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'kulinarik'],
                'motif' => 'town',
            ],
            [
                'title' => 'Schlossturm Burgplatz',
                'short_description' => 'Letzter Rest des Düsseldorfer Stadtschlosses am Rhein.',
                'description' => "Der Schlossturm am Burgplatz ist der einzige erhaltene Überrest des einstigen Düsseldorfer Stadtschlosses, das bei einem Brand im 19. Jahrhundert zerstört wurde. Der Turm liegt direkt am Rheinufer und beherbergt heute ein kleines Schifffahrtsmuseum.\n\nDer Burgplatz davor ist einer der beliebtesten Treffpunkte der Stadt, mit direktem Blick auf den Rhein und die vorbeifahrenden Schiffe. Besonders bei Sonnenuntergang versammeln sich hier viele Menschen auf den Stufen zum Fluss.",
                'location_name' => 'Düsseldorf Altstadt',
                'address' => 'Burgplatz 30, 40213 Düsseldorf',
                'lat' => 51.2264, 'lng' => 6.7722,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Museum ca. 4 €, Platz kostenlos',
                'opening_hours' => 'Di–So 11–18 Uhr (Museum)',
                'parking_information' => 'Parkhäuser in der Altstadt',
                'arrival_information' => 'Fußläufig von der Altstadt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Letzter Rest des Stadtschlosses', 'Beliebter Treffpunkt am Rhein', 'Schönes Sonnenuntergangsziel'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Kunstsammlung K20',
                'short_description' => 'Bedeutende Sammlung klassischer Moderne im schwarzen Granitbau.',
                'description' => "Die Kunstsammlung K20 am Grabbeplatz zeigt Kunst des 20. Jahrhunderts mit Schwerpunkt auf Paul Klee, Pablo Picasso und der klassischen Moderne. Der markante schwarze Granitbau selbst zählt zu den architektonischen Wahrzeichen der Stadt.\n\nWechselnde Sonderausstellungen internationaler Künstlerinnen und Künstler ergänzen die umfangreiche Sammlung. Das Museum liegt zentral in der Innenstadt und lässt sich gut mit einem Spaziergang durch den Hofgarten verbinden.",
                'location_name' => 'Düsseldorf',
                'address' => 'Grabbeplatz 5, 40213 Düsseldorf',
                'lat' => 51.2258, 'lng' => 6.7742,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 12 €',
                'opening_hours' => 'Di–So 10–18 Uhr',
                'parking_information' => 'Parkhaus am Grabbeplatz',
                'arrival_information' => 'Fußläufig von der Altstadt erreichbar',
                'website_url' => 'https://www.kunstsammlung.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Bedeutende Sammlung zu Paul Klee', 'Markanter schwarzer Granitbau', 'Wechselnde Sonderausstellungen'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Kunstsammlung K21',
                'short_description' => 'Zeitgenössische Kunst im historischen Ständehaus.',
                'description' => "Die Kunstsammlung K21 zeigt internationale Gegenwartskunst im ehemaligen Ständehaus, einem historischen Gebäude mit gläserner Kuppel. Die Installation „In Orbit“ von Tomás Saraceno unter der Kuppel zählt zu den spektakulärsten begehbaren Kunstwerken Europas.\n\nAuf mehreren Etagen werden Video-, Foto- und Installationskunst zeitgenössischer Künstlerinnen und Künstler präsentiert. Der historische Rahmen des Gebäudes bildet einen reizvollen Kontrast zu den modernen Werken.",
                'location_name' => 'Düsseldorf',
                'address' => 'Ständehausstraße 1, 40217 Düsseldorf',
                'lat' => 51.2183, 'lng' => 6.7867,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 12 €',
                'opening_hours' => 'Di–So 11–18 Uhr',
                'parking_information' => 'Parkhaus Ständehaus',
                'arrival_information' => 'Mit der Bahn ab Hauptbahnhof in wenigen Minuten erreichbar',
                'website_url' => 'https://www.kunstsammlung.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Installation „In Orbit“ von Saraceno', 'Historisches Ständehaus mit Glaskuppel', 'Internationale Gegenwartskunst'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter', 'geheimtipp'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Hofgarten Düsseldorf',
                'short_description' => 'Ältester öffentlicher Park Deutschlands.',
                'description' => "Der Hofgarten gilt als ältester öffentlicher Landschaftspark Deutschlands und erstreckt sich als grünes Band mitten durch die Innenstadt. Alte Baumbestände, kleine Seen und Wiesenflächen laden zum Spazieren und Entspannen ein.\n\nMehrere Denkmäler, darunter das Goethe-Denkmal, säumen die Wege durch den Park. Der Hofgarten verbindet die Königsallee mit dem Rheinufer und ist ein beliebter Ort für Jogger, Familien und Picknicker gleichermaßen.",
                'location_name' => 'Düsseldorf',
                'address' => 'Hofgarten, 40213 Düsseldorf',
                'lat' => 51.2280, 'lng' => 6.7820,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser in der Innenstadt',
                'arrival_information' => 'Fußläufig von der Königsallee erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Ältester öffentlicher Park Deutschlands', 'Goethe-Denkmal', 'Verbindung zwischen Kö und Rhein'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'natur', 'sommer'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Schloss Benrath',
                'short_description' => 'Rosafarbenes Lustschloss mit weitläufigem Park.',
                'description' => "Schloss Benrath wurde im 18. Jahrhundert als kurfürstliches Jagd- und Lustschloss errichtet und besticht durch seine symmetrische Anlage und die zartrosa Fassade. Drei Museen im Schloss widmen sich Kunst, Naturkunde und Gartenkunst.\n\nDer weitläufige Schlosspark mit Kanälen, Alleen und Wiesenflächen lädt zu ausgedehnten Spaziergängen ein. Besonders im Frühling, wenn die Rhododendren blühen, zeigt sich der Park von seiner schönsten Seite.",
                'location_name' => 'Benrath, Düsseldorf',
                'address' => 'Benrather Schlossallee 100, 40597 Düsseldorf',
                'lat' => 51.1611, 'lng' => 6.8672,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Schloss ca. 8 €, Park kostenlos',
                'opening_hours' => 'Di–So 11–18 Uhr, Park ganztägig',
                'parking_information' => 'Parkplatz am Schloss',
                'arrival_information' => 'Mit der Bahn ab Düsseldorf Hauptbahnhof in ca. 20 Minuten erreichbar',
                'website_url' => 'https://schloss-benrath.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Zartrosa Rokoko-Fassade', 'Drei Museen im Schloss', 'Weitläufiger Schlosspark'],
                'categories' => ['kultur-geschichte', 'familie-ausflug'],
                'labels' => ['kultur', 'familie', 'natur'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Rheinuferpromenade',
                'short_description' => 'Beliebte Flanierstrecke direkt am Rhein.',
                'description' => "Die Rheinuferpromenade entstand nach der Verlegung der Uferstraße in einen Tunnel und zählt heute zu den beliebtesten Spazierwegen Düsseldorfs. Direkt am Wasser reihen sich Cafés, Biergärten und Sitzstufen aneinander.\n\nBesonders an warmen Abenden versammeln sich hier Einheimische zum Picknick mit Blick auf die vorbeifahrenden Schiffe und den gegenüberliegenden Medienhafen. Die Promenade verbindet die Altstadt mit dem Rheinturm und dem Landtag.",
                'location_name' => 'Düsseldorf',
                'address' => 'Rheinuferpromenade, 40213 Düsseldorf',
                'lat' => 51.2260, 'lng' => 6.7715,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser in der Altstadt',
                'arrival_information' => 'Fußläufig von der Altstadt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Direkter Blick auf den Rhein', 'Cafés und Sitzstufen am Wasser', 'Verbindung zu Altstadt und Rheinturm'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'sommer'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'St. Lambertus Basilika',
                'short_description' => 'Gotische Basilika mit markant verdrehtem Kirchturm.',
                'description' => "Die Basilika St. Lambertus ist die älteste Pfarrkirche Düsseldorfs und bekannt für ihren auffällig verdrehten Turmhelm, dessen Ursache bis heute nicht abschließend geklärt ist. Im Inneren finden sich wertvolle Kunstschätze, darunter ein spätgotisches Sakramentshäuschen.\n\nDie Kirche liegt direkt am Burgplatz und ist damit gut mit einem Spaziergang durch die Altstadt und entlang des Rheinufers zu verbinden. Der schiefe Turm ist eines der markantesten Wahrzeichen der Düsseldorfer Skyline.",
                'location_name' => 'Düsseldorf Altstadt',
                'address' => 'Stiftsplatz 7a, 40213 Düsseldorf',
                'lat' => 51.2267, 'lng' => 6.7728,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Täglich 8–19 Uhr',
                'parking_information' => 'Parkhäuser in der Altstadt',
                'arrival_information' => 'Fußläufig von der Altstadt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Markant verdrehter Turmhelm', 'Älteste Pfarrkirche Düsseldorfs', 'Spätgotisches Sakramentshäuschen'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'town',
            ],
            [
                'title' => 'Japanisches Viertel Düsseldorf',
                'short_description' => 'Größte japanische Community Kontinentaleuropas.',
                'description' => "Rund um die Immermannstraße hat sich die größte japanische Gemeinde Kontinentaleuropas angesiedelt. Zahlreiche authentische Restaurants, Teehäuser und Geschäfte machen das Viertel zu einem kulinarischen Ausflug nach Japan mitten in Düsseldorf.\n\nBesonders zur Kirschblüte im April verwandelt sich die Gegend um das EKO-Haus, einen japanischen Kulturtempel am Rhein, in ein beliebtes Fotomotiv. Ramen-Restaurants und Manga-Cafés runden das Angebot ab.",
                'location_name' => 'Düsseldorf',
                'address' => 'Immermannstraße, 40210 Düsseldorf',
                'lat' => 51.2214, 'lng' => 6.7889,
                'duration' => '1–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Restaurants meist ab 11:30 Uhr geöffnet',
                'parking_information' => 'Parkhäuser am Hauptbahnhof',
                'arrival_information' => 'Fußläufig vom Hauptbahnhof erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders zur Kirschblüte im April',
                'highlights' => ['Größte japanische Community Kontinentaleuropas', 'Authentische Restaurants und Teehäuser', 'Kirschblüte am EKO-Haus im April'],
                'categories' => ['kulinarik', 'kultur-geschichte'],
                'labels' => ['kulinarik', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Aquazoo Löbbecke Museum',
                'short_description' => 'Kombiniertes Zoo- und Naturkundemuseum im Nordpark.',
                'description' => "Der Aquazoo Löbbecke Museum verbindet lebendige Tierwelt mit naturkundlicher Ausstellung unter einem Dach. Von tropischen Aquarien über ein begehbares Terrarium bis zu Pinguinen bietet das Museum Einblicke in verschiedenste Lebensräume der Erde.\n\nDas Museum liegt direkt im Nordpark und lässt sich gut mit einem Spaziergang durch den angrenzenden japanischen Garten verbinden. Besonders an Regentagen ist der Aquazoo ein beliebtes Ausflugsziel für Familien.",
                'location_name' => 'Düsseldorf',
                'address' => 'Kaiserswerther Straße 380, 40200 Düsseldorf',
                'lat' => 51.2308, 'lng' => 6.7822,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 6 €',
                'opening_hours' => 'Di–So 10–18 Uhr',
                'parking_information' => 'Parkplatz am Nordpark',
                'arrival_information' => 'Mit der Bahn ab Hauptbahnhof erreichbar',
                'website_url' => 'https://www.aquazoo.de',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Tropische Aquarien und Terrarien', 'Pinguine und Naturkundeausstellung', 'Direkt im Nordpark gelegen'],
                'categories' => ['familie-ausflug', 'indoor-schlechtwetter'],
                'labels' => ['familie', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Kaiserswerth',
                'short_description' => 'Historischer Stadtteil mit Kaiserpfalz-Ruine am Rhein.',
                'description' => "Kaiserswerth ist einer der ältesten Stadtteile Düsseldorfs und besticht mit seiner gut erhaltenen Altstadt aus Kopfsteinpflastergassen und historischen Bürgerhäusern. Die Ruine der einstigen Kaiserpfalz Barbarossas liegt direkt am Rheinufer und zeugt von der einstigen Bedeutung des Ortes.\n\nEin Spaziergang entlang der Rheinpromenade mit Blick auf die Ruine und die vorbeifahrenden Schiffe gehört zu den schönsten Erlebnissen abseits der Innenstadt. Zahlreiche Cafés laden zur Rast nach dem Rundgang ein.",
                'location_name' => 'Kaiserswerth, Düsseldorf',
                'address' => 'Kaiserpfalz, 40489 Düsseldorf',
                'lat' => 51.2761, 'lng' => 6.7314,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze im Ortskern Kaiserswerth',
                'arrival_information' => 'Mit der Bahn ab Düsseldorf Hauptbahnhof in ca. 25 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Ruine der Kaiserpfalz Barbarossas', 'Historische Altstadtgassen', 'Rheinpromenade abseits der Innenstadt'],
                'categories' => ['kultur-geschichte', 'natur-landschaft'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Filmmuseum Düsseldorf',
                'short_description' => 'Interaktives Museum zur Geschichte des Films.',
                'description' => "Das Filmmuseum Düsseldorf zeigt anschaulich die Technikgeschichte des Films von den Anfängen bis zur digitalen Gegenwart. Zahlreiche interaktive Stationen laden dazu ein, selbst Kamera- und Trickeffekte auszuprobieren.\n\nDas angeschlossene Kino „Black Box“ zeigt regelmäßig Programmkino abseits des Mainstreams. Das Museum liegt zentral in der Altstadt und eignet sich besonders gut als Ziel für einen regnerischen Nachmittag.",
                'location_name' => 'Düsseldorf Altstadt',
                'address' => 'Schulstraße 4, 40213 Düsseldorf',
                'lat' => 51.2262, 'lng' => 6.7737,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 5 €',
                'opening_hours' => 'Di–So 11–18 Uhr',
                'parking_information' => 'Parkhäuser in der Altstadt',
                'arrival_information' => 'Fußläufig von der Altstadt erreichbar',
                'website_url' => 'https://www.duesseldorf.de/filmmuseum',
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Interaktive Technikstationen', 'Programmkino Black Box', 'Zentrale Lage in der Altstadt'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter', 'geheimtipp'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'NRW-Forum Düsseldorf',
                'short_description' => 'Ausstellungshaus für Fotografie, Pop und digitale Kultur.',
                'description' => "Das NRW-Forum widmet sich als Ausstellungshaus schwerpunktmäßig Fotografie, Popkultur und digitalen Kunstformen. Wechselnde, oft international vielbeachtete Ausstellungen machen das Haus zu einem lebendigen Ort zeitgenössischer visueller Kultur.\n\nNeben den Ausstellungsräumen finden regelmäßig Vorträge, Konzerte und Filmvorführungen statt. Die zentrale Lage am Ehrenhof direkt neben der Tonhalle ermöglicht eine gute Kombination mit weiteren kulturellen Zielen.",
                'location_name' => 'Düsseldorf',
                'address' => 'Ehrenhof 2, 40479 Düsseldorf',
                'lat' => 51.2305, 'lng' => 6.7765,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 8 €',
                'opening_hours' => 'Di–So 11–18 Uhr, Do bis 20 Uhr',
                'parking_information' => 'Parkhaus Ehrenhof',
                'arrival_information' => 'Mit der Bahn ab Hauptbahnhof erreichbar',
                'website_url' => 'https://www.nrw-forum.de',
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Fokus auf Fotografie und Popkultur', 'International vielbeachtete Ausstellungen', 'Direkt neben der Tonhalle'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Nordpark mit Japanischem Garten',
                'short_description' => 'Weitläufiger Park mit authentischem japanischem Garten.',
                'description' => "Der Nordpark entstand für die Reichsausstellung 1937 und besticht heute vor allem durch seinen japanischen Garten, eines der schönsten Beispiele japanischer Gartenkunst in Europa. Kunstvoll angelegte Teiche, Steingärten und Bonsai-Bäume schaffen eine meditative Atmosphäre.\n\nDer restliche Park mit weiten Rasenflächen, Alleen und Spielplätzen lädt zu ausgedehnten Spaziergängen ein. Der Nordpark liegt in direkter Nachbarschaft zum Aquazoo und lässt sich gut mit einem Besuch dort verbinden.",
                'location_name' => 'Düsseldorf',
                'address' => 'Nordpark, 40474 Düsseldorf',
                'lat' => 51.2350, 'lng' => 6.7797,
                'duration' => '1,5–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze am Nordpark',
                'arrival_information' => 'Mit der Bahn ab Hauptbahnhof erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Authentischer japanischer Garten', 'Weite Rasenflächen und Alleen', 'Nachbarschaft zum Aquazoo'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'natur', 'geheimtipp'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Volksgarten Düsseldorf',
                'short_description' => 'Ruhiger Landschaftspark mit See im Süden der Stadt.',
                'description' => "Der Volksgarten im Süden Düsseldorfs bietet mit seinem großen See und weitläufigen Wiesenflächen eine ruhige Alternative zu den zentraleren Parks der Stadt. Der Park wird von den Einheimischen gerne zum Joggen, Radfahren und Picknicken genutzt.\n\nEin Rundweg um den See eignet sich für einen entspannten Spaziergang, während mehrere Spielplätze den Park auch für Familien mit Kindern attraktiv machen. Die Ruhe abseits der touristischen Innenstadt macht den Volksgarten zu einem echten Geheimtipp.",
                'location_name' => 'Düsseldorf',
                'address' => 'Volksgartenstraße, 40219 Düsseldorf',
                'lat' => 51.2039, 'lng' => 6.7975,
                'duration' => '1–1,5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze rund um den Volksgarten',
                'arrival_information' => 'Mit der Bahn ab Hauptbahnhof in ca. 15 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Großer See mit Rundweg', 'Ruhige Alternative zur Innenstadt', 'Mehrere Spielplätze für Familien'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'natur', 'geheimtipp'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Grafenberger Wald',
                'short_description' => 'Ausgedehntes Waldgebiet mit Pferderennbahn.',
                'description' => "Der Grafenberger Wald im Osten Düsseldorfs bietet auf großer Fläche ein Netz aus Wander- und Radwegen durch ruhige Mischwälder. Der Wald ist ein beliebtes Naherholungsgebiet für Jogger, Reiter und Spaziergänger.\n\nAm Rand des Waldes liegt die traditionsreiche Galopprennbahn Grafenberg, auf der regelmäßig Pferderennen stattfinden. Der Wald eignet sich hervorragend für eine Auszeit vom Trubel der Innenstadt, ganz ohne weite Anreise.",
                'location_name' => 'Düsseldorf',
                'address' => 'Grafenberger Wald, 40233 Düsseldorf',
                'lat' => 51.2364, 'lng' => 6.8258,
                'duration' => '1,5–2,5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplätze am Waldrand',
                'arrival_information' => 'Mit der Bahn ab Hauptbahnhof erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Ausgedehntes Wander- und Radwegenetz', 'Traditionsreiche Galopprennbahn', 'Naherholung ohne weite Anreise'],
                'categories' => ['wandern', 'natur-landschaft'],
                'labels' => ['natur', 'aktiv', 'geheimtipp'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Tonhalle Düsseldorf',
                'short_description' => 'Historischer Konzertsaal in ehemaliger Planetariumskuppel.',
                'description' => "Die Tonhalle Düsseldorf ist in einem denkmalgeschützten Rundbau untergebracht, der ursprünglich als Planetarium errichtet wurde. Die besondere Kuppelarchitektur sorgt für eine bemerkenswerte Akustik und macht das Gebäude zu einem der schönsten Konzertsäle Deutschlands.\n\nNeben regelmäßigen Konzerten des Düsseldorfer Symphonieorchesters finden hier auch Lesungen und Sonderveranstaltungen statt. Schon von außen ist die markante Rundform des Gebäudes direkt am Rheinufer ein architektonisches Highlight.",
                'location_name' => 'Düsseldorf',
                'address' => 'Ehrenhof 1, 40479 Düsseldorf',
                'lat' => 51.2308, 'lng' => 6.7770,
                'duration' => '1–2 Stunden (bei Konzertbesuch)',
                'difficulty' => null,
                'price_information' => 'Je nach Veranstaltung',
                'opening_hours' => 'Nach Veranstaltungskalender',
                'parking_information' => 'Parkhaus Ehrenhof',
                'arrival_information' => 'Mit der Bahn ab Hauptbahnhof erreichbar',
                'website_url' => 'https://www.tonhalle.de',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Ehemaliges Planetarium', 'Bemerkenswerte Konzertakustik', 'Markante Rundarchitektur am Rhein'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
        ];
    }
}
