<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class FaroSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#7ec8e3',
        'sky_bottom' => '#fbeec6',
        'accent' => '#f0a24a',
        'layers' => ['#d9b16a', '#b08a4a', '#7a5c35'],
        'water' => '#1e8fa8',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'faro'],
            [
                'name' => 'Faro',
                'type' => 'Region',
                'country' => 'Portugal',
                'federal_state' => 'Algarve',
                'short_description' => 'Naturparadies und historische Altstadt an der Ostalgarve',
                'description' => "Faro ist das Tor zur Algarve und überrascht viele Besucher mit einer charmanten, wenig überlaufenen Altstadt hinter alten Stadtmauern. Anders als die touristischen Küstenorte weiter westlich punktet Faro mit ruhiger Authentizität, einer beeindruckenden Kathedrale und engen Kopfsteinpflastergassen.\n\nVor der Stadt erstreckt sich der Naturpark Ria Formosa, eine einzigartige Lagunenlandschaft mit vorgelagerten Sandinseln, die per Boot erreichbar sind. Die Region um Faro verbindet unberührte Natur, feine Sandstrände, römische Ruinen und malerische Nachbarstädte wie Olhão und Tavira zu einem vielseitigen Reiseziel abseits des Massentourismus.",
                'hero_image' => 'regions/faro/faro-1.jpg',
                'latitude' => 37.0134,
                'longitude' => -7.9344,
                'best_travel_time' => 'April bis Juni und September bis Oktober',
                'arrival_information' => 'Internationaler Flughafen Faro liegt direkt an der Stadt und ist der Hauptzugang zur Algarve. Gute Bahn- und Busverbindungen entlang der Küste nach Tavira, Olhão und Lagos.',
                'seo_title' => 'Faro Reisetipps – Ria Formosa & Algarve | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele rund um Faro: Altstadt, Naturpark, Inseln und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 7,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/faro', 'faro', 'town', $this->palette, 'Altstadt von Faro an der Algarve', true, 0);
        MediaSeederHelper::attach($region, 'regions/faro', 'faro', 'lake', $this->palette, 'Ria Formosa Lagune bei Faro', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['natur', 'sommer', 'seen'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' bei Faro | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Cidade Velha de Faro',
                'short_description' => 'Ummauerte Altstadt mit maurischem Ursprung.',
                'description' => "Die Cidade Velha, die historische Altstadt von Faro, liegt geschützt hinter gut erhaltenen Stadtmauern maurischen Ursprungs. Enge, weiß getünchte Gassen mit Orangenbäumen und kleinen Plätzen schaffen eine ruhige, fast dörfliche Atmosphäre.\n\nDurch das Stadttor Arco da Vila betritt man eine der authentischsten Altstädte der Algarve, die abseits der großen Touristenströme geblieben ist. Ein Spaziergang ohne festen Plan durch die Gassen offenbart immer wieder kleine Plätze, Kirchen und Ausblicke auf die Ria Formosa.",
                'location_name' => 'Faro',
                'address' => 'Cidade Velha, 8000 Faro',
                'lat' => 37.0134, 'lng' => -7.9344,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser am Stadtrand der Altstadt',
                'arrival_information' => 'Fußläufig vom Bahnhof Faro in ca. 10 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Maurische Stadtmauern', 'Ruhige, authentische Gassen', 'Historisches Stadttor Arco da Vila'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Sé Catedral de Faro',
                'short_description' => 'Kathedrale mit Aussichtsturm über der Altstadt.',
                'description' => "Die Kathedrale von Faro vereint gotische, Renaissance- und barocke Bauelemente, da sie nach mehreren Zerstörungen wiederholt umgebaut wurde. Der Innenraum besticht durch prächtige Azulejo-Fliesen und eine vergoldete Barockkapelle.\n\nÜber eine schmale Wendeltreppe lässt sich der Glockenturm besteigen, von dem sich ein herrlicher Blick über die Dächer der Altstadt und die Ria Formosa bis zum Meer bietet. Neben der Kathedrale erinnert ein Storchennest auf einem der Türme an die vielen Weißstörche, die in Faro heimisch sind.",
                'location_name' => 'Faro',
                'address' => 'Largo da Sé, 8000-138 Faro',
                'lat' => 37.0139, 'lng' => -7.9319,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 3,50 €',
                'opening_hours' => 'Mo–Sa 10–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkhäuser am Stadtrand der Altstadt',
                'arrival_information' => 'Fußläufig durch die Cidade Velha erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Aussichtsturm über der Altstadt', 'Prächtige Azulejo-Fliesen', 'Storchennester auf den Türmen'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Arco da Vila',
                'short_description' => 'Historisches Stadttor zur Altstadt von Faro.',
                'description' => "Der Arco da Vila bildet den repräsentativen Zugang zur Cidade Velha und wurde im 19. Jahrhundert im neoklassizistischen Stil über einem älteren maurischen Tor errichtet. Ein Storchenpaar nistet traditionell auf der Spitze des Torbogens.\n\nDas Tor markiert den Übergang von der belebten Innenstadt zur ruhigen Altstadt und ist damit ein zentraler Orientierungspunkt für einen Rundgang durch Faro. Direkt davor liegt der belebte Jardim Manuel Bívar mit Cafés und Palmen.",
                'location_name' => 'Faro',
                'address' => 'Arco da Vila, 8000-138 Faro',
                'lat' => 37.0147, 'lng' => -7.9339,
                'duration' => '15–20 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser in der Innenstadt',
                'arrival_information' => 'Zentral gelegen, fußläufig erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Neoklassizistisches Stadttor', 'Nistplatz für Weißstörche', 'Eingang zur Cidade Velha'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Naturpark Ria Formosa',
                'short_description' => 'Einzigartige Lagunenlandschaft mit Sandinseln.',
                'description' => "Der Naturpark Ria Formosa erstreckt sich über rund 60 Kilometer entlang der Ostalgarve und besteht aus Salzwiesen, Kanälen und vorgelagerten Sandinseln. Die Lagune beherbergt eine außergewöhnliche Vielfalt an Wasservögeln, darunter seltene Arten wie den purpurroten Sichler.\n\nBootstouren ab Faro führen durch die Kanäle der Lagune und zu den unbewohnten Inseln. Die Landschaft wechselt je nach Gezeitenstand ihr Gesicht komplett, von weiten Wattflächen bis zu ruhigen Wasserflächen.",
                'location_name' => 'Faro',
                'address' => 'Ria Formosa, 8000 Faro',
                'lat' => 37.0050, 'lng' => -7.9600,
                'duration' => '2–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Bootstouren ab ca. 20 €',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplätze am Hafen von Faro',
                'arrival_information' => 'Bootstouren starten am Hafen von Faro',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig, besonders Frühling und Herbst für Vogelbeobachtung',
                'highlights' => ['Seltene Wasservögel wie der Sichler', 'Bootstouren durch die Lagune', 'Wechselnde Gezeitenlandschaft'],
                'categories' => ['natur-landschaft', 'seen-baden'],
                'labels' => ['natur', 'geheimtipp'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Praia de Faro',
                'short_description' => 'Langer Sandstrand auf einer vorgelagerten Halbinsel.',
                'description' => "Die Praia de Faro liegt auf einer schmalen Halbinsel direkt vor der Stadt und bietet einen der längsten Sandstrände der Region. Auf der einen Seite öffnet sich der Strand zum offenen Atlantik, auf der anderen Seite liegt die ruhige Lagune der Ria Formosa.\n\nZahlreiche Strandbars und Restaurants sorgen für Verpflegung, während der breite Sandstrand viel Platz auch an belebten Sommertagen bietet. Eine Brücke verbindet die Halbinsel direkt mit dem Festland und dem Flughafen Faro.",
                'location_name' => 'Faro',
                'address' => 'Praia de Faro, 8005-520 Faro',
                'lat' => 37.0022, 'lng' => -7.9836,
                'duration' => '2–4 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze an der Praia de Faro',
                'arrival_information' => 'Mit dem Bus ab Faro Zentrum in ca. 20 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Langer Sandstrand auf Halbinsel', 'Atlantik und Lagune nebeneinander', 'Zahlreiche Strandbars'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Ilha Deserta',
                'short_description' => 'Unbewohnte Sandinsel mit dem südlichsten Strand Portugals.',
                'description' => "Die Ilha Deserta, auch Ilha da Barreta genannt, ist eine unbewohnte Sandinsel vor Faro und beherbergt den südlichsten Punkt des portugiesischen Festlandsockels. Der kilometerlange, feinsandige Strand zählt zu den unberührtesten der gesamten Algarve.\n\nDie Insel ist ausschließlich per Boot ab Faro erreichbar und bietet abgesehen von einem Restaurant keinerlei Infrastruktur. Wer Ruhe und ursprüngliche Natur sucht, findet auf der Ilha Deserta einen der schönsten Rückzugsorte der Region.",
                'location_name' => 'Ilha Deserta, Faro',
                'address' => 'Ilha Deserta, 8000 Faro',
                'lat' => 36.9686, 'lng' => -7.9736,
                'duration' => '3–5 Stunden',
                'difficulty' => null,
                'price_information' => 'Bootsfahrt ab ca. 15 €',
                'opening_hours' => 'Bootsfahrten ganzjährig, saisonal abweichend',
                'parking_information' => 'Parkplätze am Hafen von Faro',
                'arrival_information' => 'Nur mit dem Boot ab Faro erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Mai bis September',
                'highlights' => ['Südlichster Punkt Festlandportugals', 'Unberührter, kilometerlanger Sandstrand', 'Nur per Boot erreichbar'],
                'categories' => ['seen-baden', 'natur-landschaft'],
                'labels' => ['natur', 'geheimtipp', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Ilha da Culatra',
                'short_description' => 'Autofreies Fischerdorf auf einer Sandinsel.',
                'description' => "Die Ilha da Culatra ist eine autofreie Sandinsel mit einem lebendigen Fischerdorf, in dem das Leben noch stark von Fischfang und Muschelzucht geprägt ist. Enge Sandwege statt Straßen und bunte Fischerhäuser prägen das Ortsbild.\n\nAm Ortsrand liegt ein feiner, oft menschenleerer Atlantikstrand, während auf der anderen Seite der Insel die ruhige Lagune zum Baden einlädt. Die Fährfahrt ab Olhão gehört bereits zum entspannten Charakter dieses Ausflugsziels.",
                'location_name' => 'Ilha da Culatra',
                'address' => 'Culatra, 8700 Olhão',
                'lat' => 36.9814, 'lng' => -7.8433,
                'duration' => '3–4 Stunden',
                'difficulty' => null,
                'price_information' => 'Fährfahrt ab ca. 5 €',
                'opening_hours' => 'Fähren ganzjährig, saisonal abweichend',
                'parking_information' => 'Parkplätze am Hafen von Olhão',
                'arrival_information' => 'Mit der Fähre ab Olhão in ca. 30 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Autofreies Fischerdorf', 'Menschenleerer Atlantikstrand', 'Ruhige Lagune zum Baden'],
                'categories' => ['seen-baden', 'natur-landschaft'],
                'labels' => ['natur', 'geheimtipp'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Museu Municipal de Faro',
                'short_description' => 'Archäologisches Museum im ehemaligen Kloster.',
                'description' => "Das Museu Municipal de Faro ist in einem ehemaligen Renaissancekloster untergebracht und zeigt Funde von der Vorgeschichte über die römische Zeit bis zur maurischen Epoche. Höhepunkt der Sammlung ist ein außergewöhnlich gut erhaltenes römisches Mosaik mit Meeresgott-Darstellung.\n\nDer ruhige Kreuzgang des ehemaligen Klosters bildet einen stimmungsvollen Rahmen für den Rundgang. Das Museum liegt mitten in der Cidade Velha und lässt sich gut mit einem Altstadtbummel verbinden.",
                'location_name' => 'Faro',
                'address' => 'Praça Dom Afonso III 14, 8000-167 Faro',
                'lat' => 37.0142, 'lng' => -7.9322,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 2 €',
                'opening_hours' => 'Di–So 10–18 Uhr',
                'parking_information' => 'Parkhäuser am Stadtrand der Altstadt',
                'arrival_information' => 'Fußläufig durch die Cidade Velha erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Römisches Mosaik mit Meeresgott', 'Ehemaliges Renaissancekloster', 'Ruhiger historischer Kreuzgang'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Palácio de Estói',
                'short_description' => 'Verspieltes Rokoko-Schloss mit Gartenanlage.',
                'description' => "Der Palácio de Estói besticht mit seiner rosa Rokoko-Fassade und den kunstvollen Azulejo-Verzierungen im Garten. Das Schloss wurde aufwendig restauriert und beherbergt heute ein Luxushotel, während Teile des Gartens frei zugänglich sind.\n\nDie terrassierten Gartenanlagen mit Statuen, Springbrunnen und Zitrusbäumen erinnern an die prunkvollen Gärten Sintras, sind jedoch deutlich weniger überlaufen. Der Palast liegt nur wenige Kilometer von Faro entfernt in den Hügeln des Hinterlands.",
                'location_name' => 'Estói, Faro',
                'address' => 'Rua de São José, 8005-465 Estói',
                'lat' => 37.0742, 'lng' => -7.9236,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Garten kostenlos, Schlossbesichtigung variiert',
                'opening_hours' => 'Garten täglich 9–18 Uhr',
                'parking_information' => 'Parkplatz am Palast',
                'arrival_information' => 'Mit dem Auto ab Faro in ca. 15 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Rosa Rokoko-Fassade', 'Terrassierte Gartenanlage', 'Weniger überlaufen als Sintra'],
                'categories' => ['kultur-geschichte', 'natur-landschaft'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Ruínas Romanas de Milreu',
                'short_description' => 'Römische Villenruine mit gut erhaltenen Mosaiken.',
                'description' => "Die römischen Ruinen von Milreu gehörten einst zu einer großzügigen Landvilla mit Thermenanlage und zählen zu den bedeutendsten römischen Fundstätten der Algarve. Besonders gut erhalten sind die Mosaikböden mit Fischmotiven im ehemaligen Badebereich.\n\nDie Anlage liegt unmittelbar neben dem Palácio de Estói und lässt sich gut mit einem Besuch dort kombinieren. Informationstafeln erklären die einzelnen Gebäudeteile der einstigen Villa anschaulich.",
                'location_name' => 'Estói, Faro',
                'address' => 'Estrada de Milreu, 8005-465 Estói',
                'lat' => 37.0797, 'lng' => -7.9314,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 2 €',
                'opening_hours' => 'Di–So 9:30–17:30 Uhr',
                'parking_information' => 'Parkplatz an den Ruinen',
                'arrival_information' => 'Mit dem Auto ab Faro in ca. 15 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Gut erhaltene römische Mosaiken', 'Ehemalige Thermenanlage', 'Nähe zum Palácio de Estói'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Olhão',
                'short_description' => 'Traditionsreiche Fischerstadt mit maurisch geprägter Architektur.',
                'description' => "Olhão ist bekannt für seine kubischen, flachgedeckten Häuser, die an nordafrikanische Architektur erinnern und der Stadt einen unverwechselbaren Charakter verleihen. Die historischen Markthallen am Hafen zählen zu den schönsten Fischmärkten der Algarve.\n\nVon Olhão aus starten die meisten Fähren zu den vorgelagerten Inseln Culatra und Armona. Ein Spaziergang durch die engen Gassen der Altstadt und entlang der Uferpromenade rundet den Besuch ab.",
                'location_name' => 'Olhão',
                'address' => 'Mercado Municipal, 8700-349 Olhão',
                'lat' => 37.0286, 'lng' => -7.8408,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Markthallen Mo–Sa 7–14 Uhr',
                'parking_information' => 'Parkplätze am Hafen von Olhão',
                'arrival_information' => 'Mit dem Zug ab Faro in ca. 15 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Nordafrikanisch geprägte Architektur', 'Historische Fischmarkthallen', 'Ausgangspunkt für Inselfähren'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Tavira',
                'short_description' => 'Elegante Altstadt mit römischer Brücke am Fluss Gilão.',
                'description' => "Tavira gilt als eine der schönsten Städte der Algarve und besticht mit einer eleganten Altstadt aus weißen Kirchen, kunstvollen Kaminen und der historischen Brücke über den Fluss Gilão. Die ruhige, kultivierte Atmosphäre unterscheidet Tavira deutlich von den touristischeren Küstenorten.\n\nEine Burgruine oberhalb der Stadt bietet einen schönen Blick über die Dächer und den Fluss. Von Tavira aus ist die vorgelagerte Ilha de Tavira mit ihren feinen Sandstränden in wenigen Minuten mit der Fähre erreichbar.",
                'location_name' => 'Tavira',
                'address' => 'Praça da República, 8800-333 Tavira',
                'lat' => 37.1256, 'lng' => -7.6497,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze am Stadtrand',
                'arrival_information' => 'Mit dem Zug ab Faro in ca. 30 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Römische Brücke über den Gilão', 'Elegante, ruhige Altstadt', 'Burgruine mit Panoramablick'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Ilha de Tavira',
                'short_description' => 'Kilometerlanger Sandstrand vor Tavira.',
                'description' => "Die Ilha de Tavira ist eine der beliebtesten Sandinseln der Ostalgarve und bietet einen kilometerlangen, feinsandigen Strand zwischen Atlantik und ruhiger Lagune. Ein kleines Feriendorf mit Restaurants versorgt Tagesgäste direkt am Fähranleger.\n\nJe weiter man am Strand entlangläuft, desto ruhiger und einsamer wird es. Die Fährfahrt ab Tavira dauert nur wenige Minuten und macht die Insel zu einem idealen Ausflugsziel für einen Strandtag.",
                'location_name' => 'Ilha de Tavira',
                'address' => 'Ilha de Tavira, 8800 Tavira',
                'lat' => 37.1064, 'lng' => -7.6244,
                'duration' => '3–5 Stunden',
                'difficulty' => null,
                'price_information' => 'Fährfahrt ab ca. 2 €',
                'opening_hours' => 'Fähren ganzjährig, saisonal abweichend',
                'parking_information' => 'Parkplätze am Fähranleger Quatro Águas',
                'arrival_information' => 'Mit der Fähre ab Tavira in ca. 10 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Kilometerlanger Sandstrand', 'Ruhige Lagune und Atlantik', 'Kurze Fährfahrt ab Tavira'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Praia do Barril',
                'short_description' => 'Strand mit berühmtem Ankerfriedhof.',
                'description' => "Die Praia do Barril ist berühmt für ihren Ankerfriedhof, in dem hunderte alte Fischeranker aufgereiht an den einst florierenden Thunfischfang der Region erinnern. Die rostigen Anker im Sand sind eines der ungewöhnlichsten Fotomotive der Algarve.\n\nEin kleines Kettenbähnchen bringt Besucher bequem vom Parkplatz durch die Salzwiesen zum Strand, alternativ ist der Weg auch zu Fuß gut machbar. Der breite Sandstrand selbst zählt zu den schönsten der Ostalgarve und ist deutlich ruhiger als die Strände weiter westlich.",
                'location_name' => 'Praia do Barril, Tavira',
                'address' => 'Praia do Barril, 8800 Tavira',
                'lat' => 37.1039, 'lng' => -7.6142,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Kettenbähnchen kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplatz an der Talstation des Bähnchens',
                'arrival_information' => 'Mit dem Auto ab Tavira in ca. 10 Minuten, dann Bähnchen oder Fußweg',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Berühmter Ankerfriedhof', 'Kettenbähnchen durch die Salzwiesen', 'Breiter, ruhiger Sandstrand'],
                'categories' => ['seen-baden', 'kultur-geschichte'],
                'labels' => ['natur', 'geheimtipp', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Loulé',
                'short_description' => 'Traditionsreiche Marktstadt im Hinterland der Algarve.',
                'description' => "Loulé liegt im Hinterland der Algarve und ist bekannt für seine maurisch geprägte Markthalle mit kunstvollen Kuppeln, in der samstags ein lebendiger Wochenmarkt stattfindet. Handwerkstraditionen wie Kupferschmieden und Korbflechten sind in der Altstadt noch heute lebendig.\n\nDie Ruinen einer maurischen Burg mitten in der Stadt lassen sich besteigen und bieten einen Blick über die Dächer der Altstadt. Loulé ist deutlich ruhiger und authentischer als die Küstenorte und lohnt einen Ausflug abseits des Strandes.",
                'location_name' => 'Loulé',
                'address' => 'Mercado Municipal, 8100-274 Loulé',
                'lat' => 37.1364, 'lng' => -8.0197,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Markt Sa vormittags, Altstadt ganztägig',
                'parking_information' => 'Parkplätze am Stadtrand',
                'arrival_information' => 'Mit dem Bus ab Faro in ca. 30 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Maurisch geprägte Markthalle', 'Lebendige Handwerkstraditionen', 'Burgruine mit Aussicht'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Farol da Ilha da Culatra',
                'short_description' => 'Historischer Leuchtturm am südlichsten Zipfel der Küste.',
                'description' => "Der Leuchtturm Farol de Santa Maria markiert die südwestliche Spitze der Ilha da Culatra und ist von einem kleinen, ursprünglichen Fischerort umgeben. Der weiße Turm mit seinen roten Streifen ist weithin sichtbar und ein beliebtes Fotomotiv.\n\nRund um den Leuchtturm erstreckt sich einer der schönsten und ruhigsten Strände der Region. Die Anreise per Boot und der Verzicht auf jeglichen Autoverkehr machen den Ort zu einem echten Rückzugsort.",
                'location_name' => 'Farol, Ilha da Culatra',
                'address' => 'Farol, 8700 Olhão',
                'lat' => 36.9686, 'lng' => -7.8686,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Fährfahrt ab ca. 5 €',
                'opening_hours' => 'Fähren ganzjährig, saisonal abweichend',
                'parking_information' => 'Parkplätze am Hafen von Olhão',
                'arrival_information' => 'Mit der Fähre ab Olhão in ca. 35 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Historischer Leuchtturm', 'Ruhiger, ursprünglicher Fischerort', 'Autofreier Rückzugsort'],
                'categories' => ['natur-landschaft', 'seen-baden'],
                'labels' => ['natur', 'geheimtipp'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Fuseta',
                'short_description' => 'Ruhiges Fischerdorf mit vorgelagerter Sandinsel.',
                'description' => "Fuseta ist ein noch wenig touristisches Fischerdorf östlich von Faro mit einer entspannten, ursprünglichen Atmosphäre. Bunte Fischerboote im Hafen und kleine Tabernas prägen das Ortsbild.\n\nEine kurze Fähre bringt Besucher zur vorgelagerten Ilha da Fuseta mit ihrem ruhigen Sandstrand. Der Ort eignet sich hervorragend für alle, die die Algarve abseits der bekannten Touristenorte erleben möchten.",
                'location_name' => 'Fuseta',
                'address' => 'Fuseta, 8700-405 Olhão',
                'lat' => 37.0428, 'lng' => -7.7811,
                'duration' => '1,5–2,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Fährfahrt kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze im Ortszentrum',
                'arrival_information' => 'Mit dem Zug ab Faro in ca. 15 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Ursprüngliches Fischerdorf', 'Vorgelagerte Sandinsel', 'Wenig touristisch'],
                'categories' => ['seen-baden', 'kulinarik'],
                'labels' => ['geheimtipp', 'natur'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Capela dos Ossos (Igreja do Carmo)',
                'short_description' => 'Ungewöhnliche Beinhaus-Kapelle aus Mönchsknochen.',
                'description' => "Die Capela dos Ossos in der Igreja do Carmo ist eine kleine Kapelle, deren Wände vollständig mit den Knochen und Schädeln von über tausend Mönchen ausgekleidet sind. Die im 19. Jahrhundert errichtete Kapelle sollte an die Vergänglichkeit des Lebens erinnern.\n\nDie prunkvolle Barockkirche selbst mit ihrer goldverzierten Fassade bildet einen starken Kontrast zur schlichten Beinhauskapelle im Innenhof. Der Besuch ist ein ungewöhnliches, aber eindrucksvolles Ziel abseits der klassischen Sehenswürdigkeiten.",
                'location_name' => 'Faro',
                'address' => 'Largo do Carmo, 8000-172 Faro',
                'lat' => 37.0169, 'lng' => -7.9308,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 3 €',
                'opening_hours' => 'Mo–Fr 10–17 Uhr, saisonal abweichend',
                'parking_information' => 'Parkhäuser in der Innenstadt',
                'arrival_information' => 'Fußläufig vom Zentrum Faro erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => false, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Wände aus Mönchsknochen', 'Prunkvolle Barockkirche', 'Ungewöhnliches Ausflugsziel'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter', 'geheimtipp'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Jardim Manuel Bívar',
                'short_description' => 'Palmengesäumter Stadtgarten am Hafen von Faro.',
                'description' => "Der Jardim Manuel Bívar liegt direkt zwischen der Marina und der Altstadt von Faro und ist mit seinen hohen Palmen ein beliebter Treffpunkt für Einheimische und Reisende. Cafés und Restaurants unter schattigen Bäumen laden zur Pause ein.\n\nVon hier aus lässt sich der Blick über die ruhige Marina und die Boote schweifen, während gleichzeitig die Altstadt nur einen kurzen Spaziergang entfernt liegt. Der Garten ist ein entspannter Ausgangspunkt, um Faro zu erkunden.",
                'location_name' => 'Faro',
                'address' => 'Jardim Manuel Bívar, 8000-078 Faro',
                'lat' => 37.0128, 'lng' => -7.9333,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser in der Innenstadt',
                'arrival_information' => 'Fußläufig vom Bahnhof Faro erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Palmengesäumter Stadtgarten', 'Blick auf die Marina', 'Zentraler Treffpunkt nahe der Altstadt'],
                'categories' => ['familie-ausflug'],
                'labels' => ['familie'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Cacela Velha',
                'short_description' => 'Malerisches Dorf über einer türkisfarbenen Lagune.',
                'description' => "Cacela Velha ist ein winziges, autofreies Dorf hoch über der Ria Formosa und gilt als eines der schönsten Fotomotive der Ostalgarve. Eine kleine weiße Kirche und die Reste einer maurischen Festung überblicken die türkisfarbene Lagune und einen langen Sandstreifen.\n\nÜber einen schmalen Pfad gelangt man vom Dorf hinunter zum Strand, der bei Ebbe von weiten Wattflächen umgeben ist. Die Abgeschiedenheit und Ruhe machen Cacela Velha zu einem der größten Geheimtipps der Region.",
                'location_name' => 'Cacela Velha, Vila Real de Santo António',
                'address' => 'Cacela Velha, 8900 Vila Real de Santo António',
                'lat' => 37.1667, 'lng' => -7.5217,
                'duration' => '1,5–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplatz am Ortseingang',
                'arrival_information' => 'Mit dem Auto ab Faro in ca. 40 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Mai bis September',
                'highlights' => ['Türkisfarbene Lagune', 'Maurische Festungsreste', 'Eines der schönsten Fotomotive der Algarve'],
                'categories' => ['natur-landschaft', 'kultur-geschichte'],
                'labels' => ['natur', 'geheimtipp', 'sommer'],
                'motif' => 'lake',
            ],
        ];
    }
}
