<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class LissabonSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#7ab8d9',
        'sky_bottom' => '#f4e0b8',
        'accent' => '#e8934a',
        'layers' => ['#c9905a', '#a06a4a', '#6a4535'],
        'water' => '#2a7a9a',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'lissabon'],
            [
                'name' => 'Lissabon',
                'type' => 'Stadt',
                'country' => 'Portugal',
                'federal_state' => null,
                'short_description' => 'Hügelige Hafenstadt mit Azulejos, Trams und Meerblick',
                'description' => "Lissabon erstreckt sich über sieben Hügel am Ufer des Tejo und begeistert mit einer einzigartigen Mischung aus maurischem Erbe, Entdeckerzeit-Geschichte und moderner Lebensfreude. Bunte Azulejo-Fliesen, knarrende Straßenbahnen und schmale Gassen im Viertel Alfama prägen das Stadtbild ebenso wie die weiten Ausblicke von zahlreichen Miradouros.\n\nAls Ausgangspunkt der großen portugiesischen Seefahrten hinterließ das Zeitalter der Entdeckungen prächtige Bauwerke wie den Torres de Belém und das Kloster Jerónimos. Gleichzeitig zeigt sich Lissabon in Vierteln wie der LX Factory kreativ und modern, während der nahe Küstenort Sintra mit seinen Märchenschlössern einen lohnenden Tagesausflug bietet.",
                'hero_image' => 'regions/lissabon/lissabon-hero-1.jpg',
                'latitude' => 38.7223,
                'longitude' => -9.1393,
                'best_travel_time' => 'März bis Juni und September bis Oktober',
                'arrival_information' => 'Flughafen Humberto Delgado liegt nur wenige Kilometer vom Zentrum entfernt und ist mit der Metro gut angebunden. Gute Zuganbindung nach Porto und Faro, internationale Flugverbindungen aus ganz Europa.',
                'seo_title' => 'Lissabon Reisetipps – Alfama, Belém & Sintra | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele in Lissabon: Historische Viertel, Aussichtspunkte, Strände und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 6,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/lissabon', 'lissabon-hero', 'town', $this->palette, 'Blick über die Dächer von Lissabon', true, 0);
        MediaSeederHelper::attach($region, 'regions/lissabon', 'lissabon-hero', 'canyon', $this->palette, 'Tejo-Ufer in Lissabon', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['kultur', 'sommer', 'familie'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' in Lissabon | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Torre de Belém',
                'short_description' => 'Wahrzeichen des Zeitalters der Entdeckungen am Tejo-Ufer.',
                'description' => "Der Torre de Belém wurde im 16. Jahrhundert zur Verteidigung des Hafens errichtet und zählt zu den bekanntesten Bauwerken Portugals. Der reich verzierte Turm im manuelinischen Stil steht symbolisch für die große Zeit der portugiesischen Seefahrt.\n\nEin Rundgang durch die Innenräume führt vorbei an Kanonenbastionen bis auf die Turmspitze, von der sich ein schöner Blick auf den Tejo bietet. Der Turm zählt zum UNESCO-Weltkulturerbe und ist meist stark besucht, weshalb sich ein früher Besuch empfiehlt.",
                'location_name' => 'Belém, Lissabon',
                'address' => 'Av. Brasília, 1400-038 Lissabon',
                'lat' => 38.6916, 'lng' => -9.2160,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 6 €',
                'opening_hours' => 'Di–So 10–17:30 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplätze entlang der Av. Brasília',
                'arrival_information' => 'Mit der Straßenbahn 15E ab Praça do Comércio erreichbar',
                'website_url' => 'https://www.torrebelem.gov.pt',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Manuelinische Baukunst', 'UNESCO-Weltkulturerbe', 'Blick auf den Tejo von der Turmspitze'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Mosteiro dos Jerónimos',
                'short_description' => 'Prachtvolles Kloster im manuelinischen Baustil.',
                'description' => "Das Kloster Jerónimos gilt als Höhepunkt der manuelinischen Architektur und wurde zur Erinnerung an Vasco da Gamas Entdeckungsfahrt nach Indien errichtet. Die aufwendig verzierten Portale und der lichte Kreuzgang zählen zu den schönsten Beispielen portugiesischer Baukunst.\n\nIn der angeschlossenen Kirche liegt das Grab von Vasco da Gama. Das gesamte Ensemble zählt zusammen mit dem nahen Torre de Belém zum UNESCO-Weltkulturerbe und ist eines der meistbesuchten Ziele Lissabons.",
                'location_name' => 'Belém, Lissabon',
                'address' => 'Praça do Império, 1400-206 Lissabon',
                'lat' => 38.6979, 'lng' => -9.2068,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 10 €, Kirche kostenlos',
                'opening_hours' => 'Di–So 10–17:30 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplätze rund um die Praça do Império',
                'arrival_information' => 'Mit der Straßenbahn 15E ab Praça do Comércio erreichbar',
                'website_url' => 'https://www.mosteirojeronimos.gov.pt',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Meisterwerk manuelinischer Architektur', 'Grab von Vasco da Gama', 'UNESCO-Weltkulturerbe'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Praça do Comércio',
                'short_description' => 'Prächtiger Platz direkt am Ufer des Tejo.',
                'description' => "Die Praça do Comércio öffnet sich als einer der größten Plätze Europas direkt zum Tejo hin und bildet das repräsentative Eingangstor zur Lissabonner Innenstadt. Der Triumphbogen an der Rua Augusta und die gelben Arkadengebäude prägen das Bild des Platzes.\n\nCafés unter den Arkaden laden zum Verweilen mit Blick auf den Fluss ein. Vom Platz aus führt die Fußgängerzone Rua Augusta direkt in die Baixa, das historische Zentrum Lissabons.",
                'location_name' => 'Baixa, Lissabon',
                'address' => 'Praça do Comércio, 1100-148 Lissabon',
                'lat' => 38.7075, 'lng' => -9.1364,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhaus am Platz',
                'arrival_information' => 'Mit der Metro bis Terreiro do Paço erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Einer der größten Plätze Europas', 'Triumphbogen an der Rua Augusta', 'Direkter Blick auf den Tejo'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Alfama',
                'short_description' => 'Ältestes Viertel Lissabons mit engen Gassen und Fado.',
                'description' => "Die Alfama ist das älteste Viertel Lissabons und entging als eines der wenigen dem großen Erdbeben von 1755. Enge, verwinkelte Gassen, bunte Azulejo-Fassaden und Wäscheleinen zwischen den Häusern schaffen eine unverwechselbare Atmosphäre.\n\nAbends erklingt aus kleinen Tavernen oft der melancholische Fado, die traditionelle Musik Lissabons. Ein Spaziergang ohne festen Plan durch die Gassen der Alfama gehört zu den authentischsten Erlebnissen der Stadt.",
                'location_name' => 'Alfama, Lissabon',
                'address' => 'Alfama, 1100-585 Lissabon',
                'lat' => 38.7127, 'lng' => -9.1305,
                'duration' => '2–3 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Wenige Parkplätze, Anreise mit ÖPNV empfohlen',
                'arrival_information' => 'Mit der Straßenbahn 28 oder zu Fuß von der Baixa erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Ältestes Viertel Lissabons', 'Traditionelle Fado-Tavernen', 'Bunte Azulejo-Fassaden'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Castelo de São Jorge',
                'short_description' => 'Maurische Burg mit dem schönsten Panorama der Stadt.',
                'description' => "Das Castelo de São Jorge thront auf dem höchsten Hügel Lissabons und blickt auf eine über 2.000-jährige Geschichte zurück, von phönizischen Anfängen bis zur maurischen Herrschaft. Die restaurierten Wehrmauern und Türme lassen sich auf einem Rundgang erklimmen.\n\nVon den Zinnen bietet sich ein spektakulärer Panoramablick über die Altstadt, den Tejo und die roten Dächer der Alfama. Pfauen streifen frei über das weitläufige Burggelände, was besonders bei Familien für Begeisterung sorgt.",
                'location_name' => 'Alfama, Lissabon',
                'address' => 'R. de Santa Cruz do Castelo, 1100-129 Lissabon',
                'lat' => 38.7139, 'lng' => -9.1335,
                'duration' => '1,5–2 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Erwachsene ca. 15 €',
                'opening_hours' => 'Täglich 9–21 Uhr, saisonal abweichend',
                'parking_information' => 'Wenige Parkplätze, Anreise mit ÖPNV empfohlen',
                'arrival_information' => 'Mit dem Bus 737 oder zu Fuß über die Alfama erreichbar',
                'website_url' => 'https://castelodesaojorge.pt',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Bester Panoramablick über Lissabon', 'Frei umherstreifende Pfauen', 'Über 2.000 Jahre Geschichte'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Elevador de Santa Justa',
                'short_description' => 'Historischer Aufzug im Herzen der Baixa.',
                'description' => "Der Elevador de Santa Justa verbindet die untere Baixa mit dem höher gelegenen Largo do Carmo und ist ein filigranes Meisterwerk der Eisenarchitektur aus dem frühen 20. Jahrhundert. Der Aufzug steht unter Denkmalschutz und wird noch heute im Alltagsbetrieb genutzt.\n\nVon der oberen Plattform des Aufzugs bietet sich ein schöner Blick über die Dächer der Baixa bis zum Castelo de São Jorge. Wegen der oft langen Warteschlangen lohnt sich auch der Fußweg zur Aussichtsplattform über die benachbarten Gassen.",
                'location_name' => 'Baixa, Lissabon',
                'address' => 'R. do Ouro, 1150-060 Lissabon',
                'lat' => 38.7139, 'lng' => -9.1394,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Fahrt ca. 5,30 €, Aussichtsplattform separat',
                'opening_hours' => 'Täglich 7–23 Uhr, saisonal abweichend',
                'parking_information' => 'Parkhäuser in der Baixa',
                'arrival_information' => 'Zentral in der Baixa gelegen, fußläufig erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Historischer Eisenaufzug', 'Aussichtsplattform über der Baixa', 'Denkmalgeschützte Architektur'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Bairro Alto',
                'short_description' => 'Angesagtes Ausgehviertel mit Bars und Straßenkunst.',
                'description' => "Das Bairro Alto verwandelt sich mit Einbruch der Dunkelheit von einem ruhigen Wohnviertel in eines der lebendigsten Ausgehviertel Lissabons. Zahlreiche kleine Bars öffnen ihre Türen direkt zur Straße, sodass sich das Nachtleben oft mitten auf den Gassen abspielt.\n\nTagsüber lohnt sich ein Spaziergang durch die ruhigeren Straßen mit ihrer bunten Straßenkunst und kleinen Boutiquen. Das Viertel liegt zentral und lässt sich gut mit einem Besuch der nahen Aussichtspunkte verbinden.",
                'location_name' => 'Bairro Alto, Lissabon',
                'address' => 'Bairro Alto, 1200-045 Lissabon',
                'lat' => 38.7139, 'lng' => -9.1458,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Verzehr in Bars kostenpflichtig',
                'opening_hours' => 'Bars meist ab 20 Uhr geöffnet',
                'parking_information' => 'Parkhäuser am Chiado',
                'arrival_information' => 'Mit der Standseilbahn Elevador da Glória erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => false, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Lebendiges Nachtleben', 'Bunte Straßenkunst', 'Historische Standseilbahn Elevador da Glória'],
                'categories' => ['kulinarik', 'kultur-geschichte'],
                'labels' => ['kulinarik', 'aktiv'],
                'motif' => 'town',
            ],
            [
                'title' => 'Padrão dos Descobrimentos',
                'short_description' => 'Monumentales Denkmal zu Ehren der portugiesischen Seefahrer.',
                'description' => "Das Padrão dos Descobrimentos wurde 1960 zum 500. Todestag Heinrichs des Seefahrers errichtet und zeigt in Form eines stilisierten Segelschiffs die bedeutendsten Persönlichkeiten der portugiesischen Entdeckungszeit. Das Denkmal steht direkt am Tejo-Ufer in Belém.\n\nEin Aufzug führt hinauf zur Aussichtsplattform an der Spitze des Denkmals, von der sich ein weiter Blick über den Fluss und die Brücke 25 de Abril bietet. Der davor liegende Bodenkompass mit Weltkarte aus Mosaiksteinen zeigt die einstigen portugiesischen Seerouten.",
                'location_name' => 'Belém, Lissabon',
                'address' => 'Av. Brasília, 1400-038 Lissabon',
                'lat' => 38.6933, 'lng' => -9.2058,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 6 € (Aussichtsplattform)',
                'opening_hours' => 'Täglich 10–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplätze entlang der Av. Brasília',
                'arrival_information' => 'Mit der Straßenbahn 15E ab Praça do Comércio erreichbar',
                'website_url' => 'https://padraodosdescobrimentos.pt',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Monument in Form eines Segelschiffs', 'Aussichtsplattform über den Tejo', 'Mosaik-Weltkarte am Boden'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Oceanário de Lisboa',
                'short_description' => 'Eines der größten Aquarien Europas.',
                'description' => "Das Oceanário de Lisboa zählt zu den größten und modernsten Aquarien Europas und zeigt in einem zentralen Großbecken verschiedenste Lebensräume der Weltmeere unter einem Dach. Haie, Rochen und Schwärme exotischer Fische ziehen durch das imposante Hauptbecken.\n\nRund um das Becken sind vier Themenbereiche angeordnet, die jeweils ein anderes Ozean-Ökosystem nachbilden, von der Antarktis bis zu tropischen Riffen. Das Oceanário liegt im Park der Nationen und ist ein beliebtes Ausflugsziel für Familien, besonders an Regentagen.",
                'location_name' => 'Parque das Nações, Lissabon',
                'address' => 'Esplanada Dom Carlos I, 1990-005 Lissabon',
                'lat' => 38.7634, 'lng' => -9.0939,
                'duration' => '2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 22 €',
                'opening_hours' => 'Täglich 10–19 Uhr',
                'parking_information' => 'Parkhaus am Parque das Nações',
                'arrival_information' => 'Mit der Metro bis Oriente erreichbar',
                'website_url' => 'https://www.oceanario.pt',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Eines der größten Aquarien Europas', 'Vier nachgebildete Ozean-Ökosysteme', 'Zentrales Großbecken mit Haien'],
                'categories' => ['familie-ausflug', 'indoor-schlechtwetter'],
                'labels' => ['familie', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'LX Factory',
                'short_description' => 'Kreatives Fabrikareal mit Cafés, Kunst und Design.',
                'description' => "Die LX Factory hat sich aus einem stillgelegten Fabrikgelände zu einem der angesagtesten Kreativviertel Lissabons entwickelt. Street Art, unabhängige Buchläden, Designstudios und Cafés füllen die alten Industriehallen mit neuem Leben.\n\nAm Wochenende verwandeln Märkte und Popup-Stände das Gelände in einen lebendigen Treffpunkt. Direkt unter der Brücke 25 de Abril gelegen, verbindet die LX Factory industriellen Charme mit alternativer Stadtkultur.",
                'location_name' => 'Alcântara, Lissabon',
                'address' => 'R. Rodrigues de Faria 103, 1300-501 Lissabon',
                'lat' => 38.7036, 'lng' => -9.1783,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich, Geschäfte variieren',
                'parking_information' => 'Parkplätze am Gelände',
                'arrival_information' => 'Mit der Bahn bis Alcântara-Mar oder mit dem Bus erreichbar',
                'website_url' => 'https://lxfactory.com',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Street Art und Designstudios', 'Wochenendmärkte', 'Lage unter der Brücke 25 de Abril'],
                'categories' => ['kulinarik', 'kultur-geschichte'],
                'labels' => ['kulinarik', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Miradouro da Senhora do Monte',
                'short_description' => 'Höchster und weitester Aussichtspunkt Lissabons.',
                'description' => "Der Miradouro da Senhora do Monte liegt auf dem höchsten der sieben Hügel Lissabons und bietet den weitesten Panoramablick der Stadt. Von hier aus sind sowohl das Castelo de São Jorge als auch der Tejo und die Brücke 25 de Abril gut zu erkennen.\n\nIm Vergleich zu bekannteren Aussichtspunkten ist der Miradouro da Senhora do Monte deutlich ruhiger und weniger überlaufen. Besonders bei Sonnenuntergang lohnt sich der etwas versteckte Aufstieg durch die Gassen der Graça.",
                'location_name' => 'Graça, Lissabon',
                'address' => 'R. Senhora do Monte, 1170-109 Lissabon',
                'lat' => 38.7178, 'lng' => -9.1319,
                'duration' => '45–60 Minuten',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Wenige Parkplätze, Anreise mit Tram empfohlen',
                'arrival_information' => 'Mit der Straßenbahn 28 bis Graça, dann kurzer Fußweg',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Weitester Panoramablick Lissabons', 'Ruhiger als bekanntere Miradouros', 'Beliebt bei Sonnenuntergang'],
                'categories' => ['aussicht-panorama'],
                'labels' => ['geheimtipp', 'kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Eléctrico 28',
                'short_description' => 'Historische Straßenbahnlinie durch die schönsten Altstadtviertel.',
                'description' => "Die Straßenbahnlinie 28 fährt seit den 1930er-Jahren mit ihren gelben Holzwaggons durch die engsten Gassen und steilsten Hügel Lissabons. Die Route führt vorbei an der Baixa, der Alfama, der Graça und dem Estrela-Viertel.\n\nDie Fahrt selbst ist bereits eine Sehenswürdigkeit und ermöglicht einen bequemen Überblick über mehrere Altstadtviertel. Wegen der großen Beliebtheit bei Touristen empfiehlt sich eine Fahrt früh am Morgen, um lange Wartezeiten zu vermeiden.",
                'location_name' => 'Lissabon',
                'address' => 'Martim Moniz, 1100-341 Lissabon',
                'lat' => 38.7169, 'lng' => -9.1359,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Einzelfahrt ca. 3 €',
                'opening_hours' => 'Täglich ca. 6–23 Uhr',
                'parking_information' => 'Parkhäuser am Martim Moniz',
                'arrival_information' => 'Start an mehreren Haltestellen, u. a. Martim Moniz oder Praça do Comércio',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Historische Holzwaggons seit den 1930ern', 'Fahrt durch mehrere Altstadtviertel', 'Günstige Alternative zur Stadtführung'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Sé de Lisboa',
                'short_description' => 'Wehrhafte Kathedrale aus der Zeit der Reconquista.',
                'description' => "Die Sé de Lisboa wurde im 12. Jahrhundert unmittelbar nach der Rückeroberung der Stadt von den Mauren errichtet und wirkt mit ihren wuchtigen Zwillingstürmen wie eine Festung. Die Kathedrale ist die älteste Kirche Lissabons und überstand mehrere Erdbeben nahezu unbeschadet.\n\nIm Inneren beeindrucken der romanische Hauptraum und der angrenzende gotische Kreuzgang mit römischen Ausgrabungen. Die Lage am Rand der Alfama macht die Kathedrale zu einem guten Ausgangspunkt für einen Rundgang durchs Viertel.",
                'location_name' => 'Alfama, Lissabon',
                'address' => 'Largo da Sé, 1100-585 Lissabon',
                'lat' => 38.7099, 'lng' => -9.1332,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Kreuzgang kostenpflichtig',
                'opening_hours' => 'Täglich 9–19 Uhr, saisonal abweichend',
                'parking_information' => 'Wenige Parkplätze, Anreise mit Tram empfohlen',
                'arrival_information' => 'Mit der Straßenbahn 28 erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Älteste Kirche Lissabons', 'Wehrhafte romanische Architektur', 'Gotischer Kreuzgang mit Ausgrabungen'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'town',
            ],
            [
                'title' => 'Praça do Rossio',
                'short_description' => 'Lebendiger Platz mit wellenförmigem Pflastermuster.',
                'description' => "Die Praça do Rossio ist seit Jahrhunderten das gesellschaftliche Zentrum der Baixa und bekannt für ihr wellenförmiges, mosaikartiges Pflastermuster aus schwarzen und weißen Steinen. Zwei barocke Springbrunnen und das Nationaltheater Dona Maria II. prägen den Platz.\n\nRund um den Rossio reihen sich traditionsreiche Kaffeehäuser und Kirschlikör-Stände (Ginjinha) aneinander. Der Platz ist ein zentraler Ausgangspunkt für Erkundungen der Baixa und liegt nur wenige Schritte vom Bahnhof Rossio entfernt.",
                'location_name' => 'Baixa, Lissabon',
                'address' => 'Praça do Rossio, 1100-200 Lissabon',
                'lat' => 38.7139, 'lng' => -9.1394,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser in der Baixa',
                'arrival_information' => 'Mit der Metro oder Bahn bis Rossio erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Wellenförmiges Pflastermuster', 'Traditionelle Ginjinha-Stände', 'Zentrale Lage in der Baixa'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Ponte 25 de Abril',
                'short_description' => 'Markante Hängebrücke mit Ähnlichkeit zur Golden Gate Bridge.',
                'description' => "Die Ponte 25 de Abril überspannt den Tejo und erinnert mit ihrer rostroten Farbe und Konstruktion stark an die Golden Gate Bridge in San Francisco. Die Brücke verbindet Lissabon mit dem südlichen Ufer und der Cristo-Rei-Statue.\n\nEine Aussichtsplattform im Brückenpfeiler, das „Pilar 7“, ermöglicht einen ungewöhnlichen Blick auf die Konstruktion und die Stadt. Am besten lässt sich die Brücke von einem der Miradouros oder vom gegenüberliegenden Ufer aus fotografieren.",
                'location_name' => 'Lissabon',
                'address' => 'Ponte 25 de Abril, 1300 Lissabon',
                'lat' => 38.6903, 'lng' => -9.1773,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Pilar 7 Aussichtsplattform ca. 7 €',
                'opening_hours' => 'Pilar 7 täglich 10–19 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz am Pilar 7',
                'arrival_information' => 'Mit der Bahn bis Alcântara-Mar erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Ähnlichkeit zur Golden Gate Bridge', 'Aussichtsplattform Pilar 7', 'Verbindung zur Cristo-Rei-Statue'],
                'categories' => ['aussicht-panorama'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Parque das Nações',
                'short_description' => 'Modernes Flussufer-Viertel der Expo 98.',
                'description' => "Der Parque das Nações entstand für die Weltausstellung 1998 und zeigt sich mit moderner Architektur, weiten Promenaden und dem markanten Vasco-da-Gama-Turm als zeitgenössisches Gegenstück zur historischen Altstadt. Die Seilbahn bietet einen ungewöhnlichen Blick über das Gelände und den Tejo.\n\nNeben dem Oceanário laden Parks, Spielplätze und Restaurants entlang der Uferpromenade zum Verweilen ein. Der Stadtteil ist besonders bei Familien beliebt, da viele Wege flach und kinderwagengeeignet sind.",
                'location_name' => 'Parque das Nações, Lissabon',
                'address' => 'Parque das Nações, 1990-231 Lissabon',
                'lat' => 38.7686, 'lng' => -9.0938,
                'duration' => '1,5–2,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Seilbahn kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser im Parque das Nações',
                'arrival_information' => 'Mit der Metro bis Oriente erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Moderne Expo-98-Architektur', 'Seilbahn über den Tejo', 'Familienfreundliche Uferpromenade'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'sommer'],
                'motif' => 'town',
            ],
            [
                'title' => 'Miradouro de Santa Luzia',
                'short_description' => 'Romantischer Aussichtspunkt mit Azulejo-Kacheln.',
                'description' => "Der Miradouro de Santa Luzia zählt zu den fotogensten Aussichtspunkten Lissabons und ist von blühenden Bougainvillea-Ranken und historischen Azulejo-Bildern gerahmt. Von der kleinen Terrasse öffnet sich ein malerischer Blick über die roten Dächer der Alfama bis zum Tejo.\n\nDie Wandbilder aus Kacheln zeigen historische Szenen der Stadt und der Reconquista. Der Aussichtspunkt liegt auf dem Weg zwischen Sé und Castelo de São Jorge und lässt sich gut in einen Alfama-Rundgang einbauen.",
                'location_name' => 'Alfama, Lissabon',
                'address' => 'Largo Santa Luzia, 1100-487 Lissabon',
                'lat' => 38.7117, 'lng' => -9.1319,
                'duration' => '20–30 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Wenige Parkplätze, Anreise mit Tram empfohlen',
                'arrival_information' => 'Mit der Straßenbahn 28 erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Rahmen aus Bougainvillea und Azulejos', 'Blick über die Alfama-Dächer', 'Auf dem Weg zum Castelo'],
                'categories' => ['aussicht-panorama', 'kultur-geschichte'],
                'labels' => ['geheimtipp', 'kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Palácio da Pena in Sintra',
                'short_description' => 'Bunt bemaltes Märchenschloss in den Bergen von Sintra.',
                'description' => "Der Palácio da Pena thront auf einem bewaldeten Gipfel oberhalb von Sintra und gilt mit seiner Mischung aus Türmen, Zinnen und leuchtenden Farben als eines der schönsten Schlösser Europas. Der romantische Baustil des 19. Jahrhunderts vereint gotische, maurische und manuelinische Elemente.\n\nDer weitläufige Park rund um das Schloss mit exotischen Bäumen und versteckten Pavillons lädt zu einem ausgedehnten Spaziergang ein. Sintra selbst ist ein beliebter Tagesausflug von Lissabon aus und beherbergt mehrere weitere sehenswerte Paläste.",
                'location_name' => 'Sintra',
                'address' => 'Estrada da Pena, 2710-609 Sintra',
                'lat' => 38.7876, 'lng' => -9.3906,
                'duration' => '2,5–3,5 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Erwachsene ca. 20 €',
                'opening_hours' => 'Täglich 9:30–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz am Schloss, Shuttlebus ab Sintra-Zentrum',
                'arrival_information' => 'Mit dem Zug ab Lissabon Rossio nach Sintra, dann Bus 434',
                'website_url' => 'https://www.parquesdesintra.pt',
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Eines der schönsten Schlösser Europas', 'Mischung aus gotischem und maurischem Stil', 'Weitläufiger Schlosspark'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Cristo Rei',
                'short_description' => 'Monumentale Christusstatue mit Blick über Lissabon.',
                'description' => "Die Christusstatue Cristo Rei erhebt sich am südlichen Tejo-Ufer und wurde nach dem Vorbild der berühmten Statue in Rio de Janeiro errichtet. Ein Aufzug bringt Besucher auf die Aussichtsplattform am Sockel der Statue.\n\nVon dort aus bietet sich ein spektakulärer Blick über Lissabon, die Brücke 25 de Abril und den Tejo. Die Fährfahrt über den Fluss zur Statue ist bereits Teil des Erlebnisses und bietet zusätzliche Ausblicke auf die Skyline.",
                'location_name' => 'Almada, gegenüber Lissabon',
                'address' => 'Alto do Pragal, 2800-058 Almada',
                'lat' => 38.6785, 'lng' => -9.1708,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 8 €',
                'opening_hours' => 'Täglich 9:30–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz am Cristo Rei',
                'arrival_information' => 'Mit der Fähre ab Cais do Sodré nach Almada, dann Bus',
                'website_url' => 'https://www.cristorei.pt',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Monumentale Christusstatue', 'Panoramablick über Lissabon', 'Fährfahrt über den Tejo'],
                'categories' => ['aussicht-panorama', 'kultur-geschichte'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Jardim da Estrela',
                'short_description' => 'Romantischer Park mit Seerosenteich und Pavillon.',
                'description' => "Der Jardim da Estrela zählt zu den schönsten Parkanlagen Lissabons und lockt mit altem Baumbestand, einem gusseisernen Pavillon und einem malerischen Seerosenteich. Der Park liegt im ruhigen Viertel Estrela, etwas abseits der touristischen Hauptrouten.\n\nEin Spielplatz und ein kleines Café machen den Park besonders bei Familien beliebt. Gegenüber liegt die imposante Basílica da Estrela mit ihrer markanten Kuppel, die sich gut mit einem Parkbesuch verbinden lässt.",
                'location_name' => 'Estrela, Lissabon',
                'address' => 'Praça da Estrela, 1200-667 Lissabon',
                'lat' => 38.7139, 'lng' => -9.1608,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Täglich 7–24 Uhr',
                'parking_information' => 'Parkplätze rund um die Praça da Estrela',
                'arrival_information' => 'Mit der Straßenbahn 28 erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Malerischer Seerosenteich', 'Gusseiserner Pavillon', 'Gegenüber der Basílica da Estrela'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'geheimtipp', 'natur'],
                'motif' => 'garden',
            ],
        ];
    }
}
