<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class LuxemburgSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#a9cbe8',
        'sky_bottom' => '#eef1df',
        'accent' => '#e8c04a',
        'layers' => ['#5f7a5b', '#3f5b46', '#2c3a2f'],
        'water' => '#3a6a8a',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'luxemburg'],
            [
                'name' => 'Luxemburg',
                'type' => 'Stadt',
                'country' => 'Luxemburg',
                'federal_state' => null,
                'short_description' => 'Festungsstadt mit Kasematten, Burgen und dem Mullerthal',
                'description' => "Luxemburg überrascht mit einer spektakulären Lage: Die Altstadt und die historischen Festungsanlagen thronen auf schroffen Felsen hoch über den Tälern von Alzette und Petrusse. Die Kasematten, ein weitläufiges unterirdisches Gangsystem, machten die Stadt einst zu einer der stärksten Festungen Europas und zählen heute zum UNESCO-Weltkulturerbe.\n\nÜber die Stadtgrenzen hinaus lockt das Großherzogtum mit malerischen Burgen wie Vianden und Beaufort, dem als „Kleine Luxemburger Schweiz“ bekannten Mullerthal mit seinen Felsformationen und Wasserfällen sowie den Weinorten entlang der Mosel. Die kompakte Größe des Landes macht viele Ausflugsziele in kurzer Zeit erreichbar.",
                'hero_image' => 'regions/luxemburg/luxemburg-1.jpg',
                'latitude' => 49.6116,
                'longitude' => 6.1319,
                'best_travel_time' => 'April bis Oktober',
                'arrival_information' => 'Flughafen Luxemburg-Findel liegt nur wenige Kilometer vom Zentrum entfernt. Guter Bahnanschluss über Trier, Metz und Brüssel, öffentlicher Nahverkehr in Luxemburg ist komplett kostenlos.',
                'seo_title' => 'Luxemburg Reisetipps – Kasematten, Burgen & Mullerthal | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele in Luxemburg: Festungsstadt, Burgen, Wanderwege und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 4,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/luxemburg', 'luxemburg', 'castle', $this->palette, 'Altstadt und Festung von Luxemburg', true, 0);
        MediaSeederHelper::attach($region, 'regions/luxemburg', 'luxemburg', 'canyon', $this->palette, 'Mullerthal in Luxemburg', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['kultur', 'natur', 'wandern'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' in Luxemburg | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Bock-Kasematten',
                'short_description' => 'Weitläufiges unterirdisches Festungssystem im Felsen.',
                'description' => "Die Bock-Kasematten zählen zu den beeindruckendsten Festungsanlagen Europas. Über 17 Kilometer Gänge wurden einst in den Sandsteinfelsen unterhalb der Altstadt getrieben, um Soldaten, Werkstätten und sogar Ställe unterzubringen.\n\nEin begehbarer Teil des Gangsystems führt vorbei an alten Kanonenstellungen und öffnet an mehreren Stellen den Blick auf das tief liegende Alzettetal. Festes Schuhwerk und eine Jacke werden empfohlen, da es im Inneren kühl und uneben ist.",
                'location_name' => 'Luxemburg-Stadt',
                'address' => 'Montée de Clausen, 1343 Luxemburg',
                'lat' => 49.6108, 'lng' => 6.1350,
                'duration' => '1–1,5 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Erwachsene ca. 10 €',
                'opening_hours' => 'Täglich 10–17:30 Uhr, saisonal abweichend',
                'parking_information' => 'Parkhaus Saint-Esprit in Gehnähe',
                'arrival_information' => 'Fußläufig von der Altstadt Luxemburg erreichbar',
                'website_url' => 'https://www.luxembourg-city.com',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['17 Kilometer Felsengänge', 'UNESCO-Weltkulturerbe', 'Blick auf das Alzettetal'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Chemin de la Corniche',
                'short_description' => 'Als „schönster Balkon Europas“ bekannter Panoramaweg.',
                'description' => "Der Chemin de la Corniche schlängelt sich entlang der ehemaligen Stadtmauer hoch über dem Alzettetal und wird oft als „schönster Balkon Europas“ bezeichnet. Der Spazierweg bietet immer wieder spektakuläre Ausblicke auf den Stadtteil Grund und die Festungsanlagen.\n\nDer Weg ist nahezu eben und gut befestigt, was ihn zu einem entspannten Spaziergang für die ganze Familie macht. Besonders am Abend, wenn die Altstadt beleuchtet wird, lohnt sich ein Besuch.",
                'location_name' => 'Luxemburg-Stadt',
                'address' => 'Chemin de la Corniche, 1364 Luxemburg',
                'lat' => 49.6103, 'lng' => 6.1345,
                'duration' => '30–45 Minuten',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhaus Saint-Esprit in Gehnähe',
                'arrival_information' => 'Fußläufig von der Altstadt Luxemburg erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['„Schönster Balkon Europas“', 'Blick auf den Stadtteil Grund', 'Nahezu ebener Spazierweg'],
                'categories' => ['aussicht-panorama', 'familie-ausflug'],
                'labels' => ['familie', 'kultur'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Kathedrale Notre-Dame Luxemburg',
                'short_description' => 'Spätgotische Kathedrale im Herzen der Altstadt.',
                'description' => "Die Kathedrale Notre-Dame ist die einzige Kathedrale Luxemburgs und ein Meisterwerk spätgotischer Architektur mit Renaissance- und Barockelementen. Der schlanke Innenraum mit den kunstvollen Chorschranken zählt zu den schönsten Kirchenräumen des Landes.\n\nIn der Krypta liegen Mitglieder des großherzoglichen Hauses begraben. Die zentrale Lage in der Altstadt macht einen Besuch gut mit einem Bummel über den Place Guillaume II kombinierbar.",
                'location_name' => 'Luxemburg-Stadt',
                'address' => 'Rue Notre-Dame, 2240 Luxemburg',
                'lat' => 49.6100, 'lng' => 6.1300,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Täglich 10–17:30 Uhr, saisonal abweichend',
                'parking_information' => 'Parkhaus Königsring in Gehnähe',
                'arrival_information' => 'Fußläufig vom Place d\'Armes erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Spätgotische Architektur', 'Grabstätte des großherzoglichen Hauses', 'Zentrale Lage in der Altstadt'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'town',
            ],
            [
                'title' => 'Großherzoglicher Palast',
                'short_description' => 'Offizielle Residenz des luxemburgischen Großherzogs.',
                'description' => "Der Großherzogliche Palast ist die offizielle Residenz des Staatsoberhaupts und beeindruckt mit seiner reich verzierten Renaissance-Fassade mitten in der Altstadt. Zur vollen Stunde kann die Wachablösung der Palastgarde beobachtet werden.\n\nIm Sommer werden Führungen durch einige Repräsentationsräume des Palastes angeboten. Auch ohne Innenbesichtigung lohnt sich ein Spaziergang an der prunkvollen Fassade vorbei.",
                'location_name' => 'Luxemburg-Stadt',
                'address' => 'Rue du Marché-aux-Herbes, 1728 Luxemburg',
                'lat' => 49.6108, 'lng' => 6.1306,
                'duration' => '20–30 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos (Außenbesichtigung), Führungen kostenpflichtig',
                'opening_hours' => 'Führungen im Sommer, Außenbereich ganztägig sichtbar',
                'parking_information' => 'Parkhaus Königsring in Gehnähe',
                'arrival_information' => 'Fußläufig vom Place d\'Armes erreichbar',
                'website_url' => 'https://www.monarchie.lu',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Reich verzierte Renaissance-Fassade', 'Wachablösung zur vollen Stunde', 'Sommerführungen durch Repräsentationsräume'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Place d\'Armes',
                'short_description' => 'Lebendiger Hauptplatz mit Cafés und Musikpavillon.',
                'description' => "Der Place d'Armes ist das gesellschaftliche Zentrum der Luxemburger Altstadt und von schattenspendenden Bäumen, Cafés und Restaurants gesäumt. In der Mitte des Platzes sorgt ein historischer Musikpavillon im Sommer regelmäßig für Konzerte.\n\nDer Platz ist ein idealer Ausgangspunkt, um die umliegende Altstadt mit ihren Gassen und Geschäften zu erkunden. Auch der Weihnachtsmarkt im Advent findet hier alljährlich statt.",
                'location_name' => 'Luxemburg-Stadt',
                'address' => 'Place d\'Armes, 1136 Luxemburg',
                'lat' => 49.6117, 'lng' => 6.1290,
                'duration' => '30–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhaus Place d\'Armes direkt am Platz',
                'arrival_information' => 'Zentral in der Altstadt gelegen',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Historischer Musikpavillon', 'Sommerkonzerte auf dem Platz', 'Zentraler Ausgangspunkt für die Altstadt'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Grund (Luxemburg)',
                'short_description' => 'Malerisches Flussviertel tief im Alzettetal.',
                'description' => "Der Stadtteil Grund liegt tief im Alzettetal unterhalb der Altstadt und wirkt mit seinen engen Gassen und historischen Gebäuden wie eine eigene kleine Stadt. Cafés und Bars entlang des Flusses machen den Grund besonders abends zu einem beliebten Ausgehviertel.\n\nEin Aufzug verbindet die Oberstadt direkt mit dem Grund und erspart den steilen Fußweg. Die umliegenden Festungsmauern und der Blick von unten auf die Altstadt machen den Grund zu einem der fotogensten Orte Luxemburgs.",
                'location_name' => 'Luxemburg-Stadt',
                'address' => 'Rue Munster, 2160 Luxemburg',
                'lat' => 49.6086, 'lng' => 6.1336,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhaus Saint-Esprit, Aufzug zum Grund',
                'arrival_information' => 'Mit dem kostenlosen Panoramaaufzug von der Altstadt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Malerisches Flussviertel', 'Panoramaaufzug zur Altstadt', 'Beliebtes Ausgehviertel am Abend'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Adolphe-Brücke',
                'short_description' => 'Wahrzeichenbrücke über das Petrusse-Tal.',
                'description' => "Die Adolphe-Brücke gilt als eines der Wahrzeichen Luxemburgs und überspannt mit ihrem markanten Steinbogen das tiefe Petrusse-Tal. Von der Brücke aus öffnet sich ein schöner Blick auf die Parkanlagen im Tal und die umliegende Altstadt.\n\nEin Fußweg unterhalb der Brücke führt durch die Petrusse-Grünanlagen und ermöglicht einen Blick von unten auf das imposante Bauwerk. Besonders bei Nacht, wenn die Brücke beleuchtet wird, ist sie ein beliebtes Fotomotiv.",
                'location_name' => 'Luxemburg-Stadt',
                'address' => 'Pont Adolphe, 1140 Luxemburg',
                'lat' => 49.6098, 'lng' => 6.1272,
                'duration' => '20–30 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhaus Königsring in Gehnähe',
                'arrival_information' => 'Fußläufig vom Stadtzentrum erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Wahrzeichenbrücke über das Petrusse-Tal', 'Blick auf die Petrusse-Grünanlagen', 'Beeindruckend bei Nacht beleuchtet'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Mudam Luxemburg',
                'short_description' => 'Museum für zeitgenössische Kunst in spektakulärem Glasbau.',
                'description' => "Das Mudam (Musée d'Art Moderne Grand-Duc Jean) zeigt zeitgenössische Kunst in einem lichtdurchfluteten Bau des Stararchitekten I. M. Pei. Die wechselnden Ausstellungen internationaler Künstlerinnen und Künstler machen das Museum zu einem der wichtigsten Kunstorte der Großregion.\n\nSchon die Architektur des Gebäudes auf dem Kirchberg-Plateau ist ein Erlebnis für sich. Der angrenzende Skulpturenpark lädt zu einem Spaziergang zwischen Kunstwerken im Freien ein.",
                'location_name' => 'Kirchberg, Luxemburg-Stadt',
                'address' => '3 Park Dräi Eechelen, 1499 Luxemburg',
                'lat' => 49.6206, 'lng' => 6.1454,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 8 €',
                'opening_hours' => 'Mi–Mo 10–18 Uhr, Do bis 21 Uhr',
                'parking_information' => 'Parkhaus Kirchberg direkt am Museum',
                'arrival_information' => 'Mit der Straßenbahn ab Zentrum Luxemburg erreichbar',
                'website_url' => 'https://www.mudam.com',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Architektur von I. M. Pei', 'Wechselnde zeitgenössische Ausstellungen', 'Skulpturenpark im Freien'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Schloss Vianden',
                'short_description' => 'Eine der größten und schönsten Burganlagen Europas.',
                'description' => "Schloss Vianden zählt zu den eindrucksvollsten Burganlagen Europas und thront hoch über dem gleichnamigen Städtchen im Norden Luxemburgs. Die aufwendig restaurierten Säle, Rüstkammern und der Rittersaal vermitteln einen lebendigen Eindruck mittelalterlichen Burglebens.\n\nEine Sesselbahn bringt Besucher bequem vom Ort hinauf zur Burg, alternativ führt ein steiler Fußweg durch die historische Altstadt. Der Ausblick von den Burgmauern über das Ourtal zählt zu den schönsten Panoramen Luxemburgs.",
                'location_name' => 'Vianden',
                'address' => 'Montée du Château, 9408 Vianden',
                'lat' => 49.9350, 'lng' => 6.2072,
                'duration' => '1,5–2 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Erwachsene ca. 10 €',
                'opening_hours' => 'Täglich 10–17 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz im Ortszentrum Vianden',
                'arrival_information' => 'Mit dem Bus ab Luxemburg-Stadt in ca. 50 Minuten erreichbar',
                'website_url' => 'https://www.chateau-vianden.lu',
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Eine der größten Burgen Europas', 'Sesselbahn zur Burg', 'Panoramablick über das Ourtal'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Mullerthal Trail',
                'short_description' => 'Als „Kleine Luxemburger Schweiz“ bekanntes Wandergebiet.',
                'description' => "Der Mullerthal Trail führt durch bizarre Sandsteinformationen, moosbewachsene Felsschluchten und dichte Wälder im Osten Luxemburgs. Die Region wird wegen ihrer schroffen Felslandschaft liebevoll „Kleine Luxemburger Schweiz“ genannt.\n\nDer Hauptweg ist in mehrere Etappen unterteilt und lässt sich sowohl als kurzer Spaziergang als auch als mehrtägige Wanderung erleben. Besonders die engen Felsspalten und kleinen Wasserläufe machen die Strecke zu einem abwechslungsreichen Naturerlebnis.",
                'location_name' => 'Consdorf, Luxemburg',
                'address' => 'Mullerthal Trail, 6211 Consdorf',
                'lat' => 49.7833, 'lng' => 6.3500,
                'duration' => '2–5 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig begehbar',
                'parking_information' => 'Wanderparkplätze in Consdorf und Berdorf',
                'arrival_information' => 'Mit dem Auto oder Bus ab Luxemburg-Stadt in ca. 40 Minuten erreichbar',
                'website_url' => 'https://www.mullerthal-trail.lu',
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Bizarre Sandsteinformationen', '„Kleine Luxemburger Schweiz“', 'Mehrere Etappen für jedes Niveau'],
                'categories' => ['wandern', 'natur-landschaft'],
                'labels' => ['wandern', 'natur', 'aktiv'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Echternach',
                'short_description' => 'Ältester Ort Luxemburgs mit historischer Basilika.',
                'description' => "Echternach gilt als ältester Ort Luxemburgs und ist geprägt von der imposanten Basilika St. Willibrord, einem bedeutenden Wallfahrtsort. Die gut erhaltene Altstadt mit ihren engen Gassen und dem historischen Marktplatz lädt zu einem gemütlichen Bummel ein.\n\nDirekt am Rand der Stadt liegt der Echternacher See, ein beliebtes Ausflugsziel zum Spazieren und Radfahren. Echternach ist zugleich Tor zum Mullerthal und idealer Ausgangspunkt für Wanderungen in die Region.",
                'location_name' => 'Echternach',
                'address' => 'Parvis de la Basilique, 6486 Echternach',
                'lat' => 49.8114, 'lng' => 6.4211,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze im Stadtzentrum',
                'arrival_information' => 'Mit dem Bus ab Luxemburg-Stadt in ca. 45 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Ältester Ort Luxemburgs', 'Basilika St. Willibrord', 'Echternacher See zum Spazieren'],
                'categories' => ['kultur-geschichte', 'familie-ausflug'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Schiessentümpel',
                'short_description' => 'Meistfotografierter Wasserfall im Mullerthal.',
                'description' => "Der Schiessentümpel ist der bekannteste und meistfotografierte Wasserfall Luxemburgs. Eine kleine, malerische Steinbrücke direkt vor dem Wasserfall macht das Motiv zu einem der beliebtesten des Landes.\n\nDer Wasserfall liegt mitten im Mullerthal und ist über einen kurzen Waldweg erreichbar. Besonders nach Regenfällen führt der Bach viel Wasser und der Schiessentümpel zeigt sich von seiner eindrucksvollsten Seite.",
                'location_name' => 'Mullerthal, Luxemburg',
                'address' => 'Schiessentümpel, 6245 Müllerthal',
                'lat' => 49.8103, 'lng' => 6.3389,
                'duration' => '30–60 Minuten',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Wanderparkplatz an der Zufahrt',
                'arrival_information' => 'Mit dem Auto ab Luxemburg-Stadt in ca. 35 Minuten, dann kurzer Fußweg',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Meistfotografierter Wasserfall Luxemburgs', 'Malerische Steinbrücke', 'Kurzer Waldweg zum Wasserfall'],
                'categories' => ['natur-landschaft', 'wandern'],
                'labels' => ['natur', 'geheimtipp', 'familie'],
                'motif' => 'waterfall',
            ],
            [
                'title' => 'Schloss Beaufort',
                'short_description' => 'Romantische Burgruine im Mullerthal.',
                'description' => "Schloss Beaufort besteht aus einer mittelalterlichen Burgruine und einem angrenzenden Renaissanceschloss und liegt idyllisch am Rand eines kleinen Waldsees. Die verwinkelten Gemäuer der Ruine lassen sich auf eigene Faust erkunden.\n\nDer angrenzende Weiher mit seinen Seerosen und der stimmungsvollen Kulisse der Ruine macht Beaufort zu einem besonders fotogenen Ausflugsziel im Mullerthal. Ein kleiner Rundweg führt einmal um den Teich.",
                'location_name' => 'Beaufort, Luxemburg',
                'address' => 'Chemin du Château, 6310 Beaufort',
                'lat' => 49.8347, 'lng' => 6.2933,
                'duration' => '1 Stunde',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 3 € (Ruine)',
                'opening_hours' => 'April bis Oktober, täglich 10–18 Uhr',
                'parking_information' => 'Parkplatz am Schloss',
                'arrival_information' => 'Mit dem Auto ab Luxemburg-Stadt in ca. 30 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Mittelalterliche Burgruine', 'Idyllischer Weiher mit Seerosen', 'Renaissanceschloss nebenan'],
                'categories' => ['kultur-geschichte', 'natur-landschaft'],
                'labels' => ['kultur', 'geheimtipp', 'natur'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Schloss Larochette',
                'short_description' => 'Eindrucksvolle Doppelburg über dem Ort Larochette.',
                'description' => "Die Burgruine Larochette thront auf einem Felssporn über dem gleichnamigen Städtchen und besteht aus mehreren mittelalterlichen Wohntürmen unterschiedlicher Adelsfamilien. Die weitläufige Anlage lässt sich über Treppen und Wege in den Mauern erkunden.\n\nVon den Türmen aus reicht der Blick weit über das Tal der Weißen Ernz. Der Ort Larochette selbst mit seinem gemütlichen Marktplatz lädt zu einer Rast nach der Besichtigung ein.",
                'location_name' => 'Larochette, Luxemburg',
                'address' => 'Chemin du Château, 7622 Larochette',
                'lat' => 49.7833, 'lng' => 6.2222,
                'duration' => '1–1,5 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Erwachsene ca. 3 €',
                'opening_hours' => 'April bis Oktober, täglich 10–18 Uhr',
                'parking_information' => 'Parkplatz im Ortszentrum Larochette',
                'arrival_information' => 'Mit dem Auto ab Luxemburg-Stadt in ca. 25 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Mittelalterliche Doppelburg', 'Blick über das Tal der Weißen Ernz', 'Begehbare Türme und Wehrgänge'],
                'categories' => ['kultur-geschichte', 'aussicht-panorama'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Remich an der Mosel',
                'short_description' => 'Charmanter Weinort an der luxemburgischen Mosel.',
                'description' => "Remich liegt an der luxemburgischen Moselstraße und ist bekannt für seine Winzerbetriebe und die gemütliche Uferpromenade. Ein Spaziergang entlang des Flusses mit Blick auf die gegenüberliegenden deutschen Weinberge gehört zu den schönsten Erlebnissen der Region.\n\nZahlreiche Winzerhöfe laden zur Weinprobe der lokalen Crémants und Weißweine ein. Von Remich aus starten auch Ausflugsschiffe zu Fahrten auf der Mosel.",
                'location_name' => 'Remich, Luxemburg',
                'address' => 'Esplanade, 5533 Remich',
                'lat' => 49.5453, 'lng' => 6.3653,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Weinproben kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze entlang der Esplanade',
                'arrival_information' => 'Mit dem Auto ab Luxemburg-Stadt in ca. 30 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Uferpromenade an der Mosel', 'Weinproben bei lokalen Winzern', 'Ausflugsschiffe ab Remich'],
                'categories' => ['kulinarik', 'natur-landschaft'],
                'labels' => ['kulinarik', 'geheimtipp', 'sommer'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Esch-sur-Sûre',
                'short_description' => 'Malerisches Städtchen in einer Flussschleife der Sauer.',
                'description' => "Esch-sur-Sûre liegt in einer engen Flussschleife der Sauer und wird von einer Burgruine hoch über den Dächern überragt. Die kleinen Gassen und Fachwerkhäuser machen den Ort zu einem der pittoreskesten in Luxemburg.\n\nEin Rundweg führt hinauf zur Burgruine und bietet von dort einen herrlichen Blick auf die Flussschleife und den nahen Stausee. Der Ort ist ein beliebter Ausgangspunkt für Wander- und Wassersportaktivitäten am Obersauerstausee.",
                'location_name' => 'Esch-sur-Sûre, Luxemburg',
                'address' => 'Rue du Château, 9650 Esch-sur-Sûre',
                'lat' => 49.9139, 'lng' => 5.9439,
                'duration' => '1,5–2 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplatz im Ortszentrum',
                'arrival_information' => 'Mit dem Auto ab Luxemburg-Stadt in ca. 45 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Ort in einer Flussschleife der Sauer', 'Burgruine mit Panoramablick', 'Nähe zum Obersauerstausee'],
                'categories' => ['kultur-geschichte', 'natur-landschaft'],
                'labels' => ['kultur', 'natur', 'geheimtipp'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Berdorf',
                'short_description' => 'Kletter- und Wanderdorf mitten im Mullerthal.',
                'description' => "Berdorf gilt als das Zentrum des Mullerthals und ist bei Wanderern und Kletterern gleichermaßen beliebt. Zahlreiche markierte Wege führen von hier aus zu Felsformationen, Aussichtspunkten und kleinen Grotten in der Umgebung.\n\nDie Felswände rund um Berdorf gehören zu den beliebtesten Klettergebieten Luxemburgs. Auch ohne Kletterausrüstung lohnt sich ein Spaziergang zu den nahegelegenen Aussichtsfelsen wie dem Wanterbach oder der Kasselslay.",
                'location_name' => 'Berdorf, Luxemburg',
                'address' => 'Rue de Grundhof, 6550 Berdorf',
                'lat' => 49.8103, 'lng' => 6.3572,
                'duration' => '2–3 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Wanderparkplätze im Ortszentrum',
                'arrival_information' => 'Mit dem Auto ab Luxemburg-Stadt in ca. 40 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Zentrum des Mullerthal Trail', 'Beliebtes Klettergebiet', 'Zahlreiche Felsformationen und Grotten'],
                'categories' => ['wandern', 'natur-landschaft'],
                'labels' => ['wandern', 'aktiv', 'natur'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Schloss Clervaux',
                'short_description' => 'Renaissanceschloss mit weltberühmter Fotoausstellung.',
                'description' => "Schloss Clervaux im Norden Luxemburgs beherbergt die weltberühmte Fotoausstellung „The Family of Man“ von Edward Steichen, die von der UNESCO zum Weltdokumentenerbe erklärt wurde. Die eindrucksvolle Sammlung von über 500 Fotografien erzählt universelle Geschichten menschlichen Lebens.\n\nDas Schloss selbst thront über dem malerischen Städtchen Clervaux und beherbergt zusätzlich ein Modell der luxemburgischen Burgen sowie ein Kriegsmuseum zur Ardennenoffensive. Der Ort liegt eingebettet in die bewaldeten Hügel der Ardennen.",
                'location_name' => 'Clervaux, Luxemburg',
                'address' => 'Montée du Château, 9712 Clervaux',
                'lat' => 50.0500, 'lng' => 6.0281,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 8 €',
                'opening_hours' => 'Täglich 10–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz im Ortszentrum Clervaux',
                'arrival_information' => 'Mit dem Zug ab Luxemburg-Stadt in ca. 50 Minuten erreichbar',
                'website_url' => 'https://www.thefamilyofman.lu',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Weltberühmte Fotoausstellung „The Family of Man“', 'UNESCO-Weltdokumentenerbe', 'Malerische Lage in den Ardennen'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Kirchberg-Plateau',
                'short_description' => 'Modernes Europaviertel mit Philharmonie und Architektur.',
                'description' => "Das Kirchberg-Plateau ist das moderne Gesicht Luxemburgs und beherbergt zahlreiche EU-Institutionen sowie die markante Philharmonie mit ihrer namensgebenden Säulenfassade. Zeitgenössische Architektur prägt das gesamte Viertel.\n\nDer angrenzende Park Dräi Eechelen mit der gleichnamigen Festung bietet einen ruhigen Kontrast zu den modernen Bauten. Das Viertel lässt sich gut mit einem Besuch des benachbarten Mudam verbinden.",
                'location_name' => 'Kirchberg, Luxemburg-Stadt',
                'address' => 'Place de l\'Europe, 1499 Luxemburg',
                'lat' => 49.6217, 'lng' => 6.1428,
                'duration' => '1–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhaus Kirchberg',
                'arrival_information' => 'Mit der Straßenbahn ab Zentrum Luxemburg erreichbar',
                'website_url' => 'https://www.philharmonie.lu',
                'phone' => null,
                'rating' => 4.3,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Markante Philharmonie-Architektur', 'Festung Dräi Eechelen', 'Modernes Europaviertel'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Abtei Neumünster',
                'short_description' => 'Historisches Kloster im Grund als lebendiges Kulturzentrum.',
                'description' => "Die Abtei Neumünster im Stadtteil Grund wurde im 17. Jahrhundert als Benediktinerkloster errichtet und diente später unter anderem als Kaserne und Gefängnis. Heute ist das restaurierte Gebäude ein lebendiges Kultur- und Begegnungszentrum mit Konzerten, Ausstellungen und Festivals.\n\nDer ruhige Innenhof und die historischen Gewölbe bilden einen stimmungsvollen Rahmen für Veranstaltungen aller Art. Die Lage direkt am Fluss Alzette und unterhalb der Festungsmauern macht einen Besuch gut mit einem Spaziergang durch den Grund kombinierbar.",
                'location_name' => 'Grund, Luxemburg-Stadt',
                'address' => '28 Rue Münster, 2160 Luxemburg',
                'lat' => 49.6098, 'lng' => 6.1358,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Kostenlos (Innenhof), Ausstellungen teils kostenpflichtig',
                'opening_hours' => 'Täglich 10–18 Uhr',
                'parking_information' => 'Parkhaus Saint-Esprit, Aufzug zum Grund',
                'arrival_information' => 'Mit dem Panoramaaufzug oder zu Fuß über den Grund erreichbar',
                'website_url' => 'https://www.neimenster.lu',
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Restauriertes Benediktinerkloster', 'Lebendiges Kultur- und Begegnungszentrum', 'Lage direkt am Fluss Alzette'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'geheimtipp', 'schlechtwetter'],
                'motif' => 'town',
            ],
        ];
    }
}
