<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class MauritiusSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#6ec6e8',
        'sky_bottom' => '#eaf7e0',
        'accent' => '#f5c94a',
        'layers' => ['#4a9a6a', '#2f7a4a', '#1e5030'],
        'water' => '#1a9ac2',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'mauritius'],
            [
                'name' => 'Mauritius',
                'type' => 'Insel',
                'country' => 'Mauritius',
                'federal_state' => null,
                'short_description' => 'Tropische Trauminsel mit türkisen Lagunen und bunter Kultur',
                'description' => "Mauritius liegt rund 2.000 Kilometer vor der Küste Ostafrikas im Indischen Ozean und gilt als eine der schönsten Trauminseln der Welt. Türkisfarbene Lagunen, kilometerlange Palmenstrände und ein fast durchgängig umgebendes Korallenriff prägen die Küste, während das Inselinnere mit schroffen Vulkanbergen und dichtem Regenwald überrascht.\n\nDie bewegte Kolonialgeschichte spiegelt sich in einer außergewöhnlich vielfältigen Kultur aus indischen, afrikanischen, chinesischen und europäischen Einflüssen wider, die sich in Küche, Musik und Festen der Insel zeigt. Zwischen Wanderungen im Nationalpark Black River Gorges, Bootsausflügen zu vorgelagerten Inseln und der bunten Geologie von Chamarel bietet Mauritius weit mehr als nur Strandurlaub.",
                'hero_image' => 'regions/mauritius/mauritius-hero-1.jpg',
                'latitude' => -20.2760,
                'longitude' => 57.5751,
                'best_travel_time' => 'Mai bis Dezember (Trockenzeit), ganzjährig warm',
                'arrival_information' => 'Internationaler Flughafen Sir Seewoosagur Ramgoolam im Südosten der Insel. Direktflüge aus Europa dauern etwa 11–12 Stunden. Mietwagen oder Taxis sind die gängigsten Fortbewegungsmittel auf der Insel.',
                'seo_title' => 'Mauritius Reisetipps – Strände, Natur & Kultur | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele auf Mauritius: Traumstrände, Nationalparks, bunte Erde und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 8,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/mauritius', 'mauritius-hero', 'lake', $this->palette, 'Türkise Lagune auf Mauritius', true, 0);
        MediaSeederHelper::attach($region, 'regions/mauritius', 'mauritius-hero', 'mountains', $this->palette, 'Berglandschaft im Inselinneren von Mauritius', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['natur', 'sommer', 'seen'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' auf Mauritius | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Le Morne Brabant',
                'short_description' => 'UNESCO-Weltnaturerbe-Berg mit dramatischer Geschichte.',
                'description' => "Der Le Morne Brabant ist ein schroffer Basaltberg an der Südwestspitze von Mauritius und zählt zum UNESCO-Weltkulturerbe, da er einst geflüchteten Sklaven als Zufluchtsort diente. Die steilen Felswände und die symbolische Bedeutung machen den Berg zu einem der eindrucksvollsten Orte der Insel.\n\nEine anspruchsvolle Wanderung führt bis zu einer Plattform auf halber Höhe mit spektakulärem Blick auf die Lagune und die vorgelagerten Riffe. Der Strand am Fuß des Berges zählt zudem zu den schönsten der Insel und ist berühmt für den optischen Effekt eines „Unterwasserwasserfalls“, der von der Luft aus sichtbar ist.",
                'location_name' => 'Le Morne',
                'address' => 'Le Morne Brabant, Mauritius',
                'lat' => -20.4497, 'lng' => 57.3183,
                'duration' => '3–4 Stunden (Wanderung)',
                'difficulty' => 'anspruchsvoll',
                'price_information' => 'Geführte Touren ab ca. 40 €',
                'opening_hours' => 'Wanderung nur mit lokalem Guide erlaubt',
                'parking_information' => 'Parkplatz am Wanderausgangspunkt',
                'arrival_information' => 'Mit dem Mietwagen oder Taxi an die Südwestspitze der Insel',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => false, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['UNESCO-Weltkulturerbe', 'Optischer „Unterwasserwasserfall“', 'Traumhafter Strand am Bergfuß'],
                'categories' => ['wandern', 'aussicht-panorama'],
                'labels' => ['wandern', 'aktiv', 'natur'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Chamarel Seven Coloured Earths',
                'short_description' => 'Einzigartige bunte Dünenlandschaft aus vulkanischem Gestein.',
                'description' => "Die Seven Coloured Earths bei Chamarel zeigen ein außergewöhnliches Naturphänomen: Vulkanisches Gestein hat sich durch unterschiedliche Mineralzusammensetzungen in Schichten aus Rot, Braun, Violett, Grün und Gelb verfärbt. Die Dünen behalten ihre Farbschichtung sogar bei starkem Regen bei, was Wissenschaftler bis heute fasziniert.\n\nEin Rundweg mit Aussichtsplattformen ermöglicht Blicke auf die farbige Landschaft aus verschiedenen Perspektiven. In der Umgebung leben zudem Riesenschildkröten in einem kleinen Gehege, die besuchsfreundlich sind.",
                'location_name' => 'Chamarel',
                'address' => 'Seven Coloured Earths, Chamarel',
                'lat' => -20.4372, 'lng' => 57.3814,
                'duration' => '1–1,5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 6 €',
                'opening_hours' => 'Täglich 7–17:30 Uhr',
                'parking_information' => 'Parkplatz am Eingang',
                'arrival_information' => 'Mit dem Mietwagen oder Taxi ab Le Morne oder Flic en Flac erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Einzigartige farbige Erdschichten', 'Riesenschildkröten-Gehege', 'Mehrere Aussichtsplattformen'],
                'categories' => ['natur-landschaft', 'familie-ausflug'],
                'labels' => ['natur', 'familie'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Black River Gorges National Park',
                'short_description' => 'Größter Nationalpark der Insel mit endemischer Tierwelt.',
                'description' => "Der Black River Gorges National Park schützt die letzten großen Regenwaldflächen von Mauritius und beherbergt zahlreiche endemische Pflanzen- und Vogelarten, darunter den seltenen Mauritius-Falken. Tiefe Schluchten, Wasserfälle und dichter Urwald prägen die Landschaft.\n\nEin Netz aus Wanderwegen unterschiedlicher Länge führt durch den Park, mehrere Aussichtspunkte wie der Alexandra Falls Viewpoint bieten spektakuläre Blicke über den Regenwald bis zur Küste. Der Park ist die wichtigste Adresse für Naturliebhaber und Wanderer auf der Insel.",
                'location_name' => 'Black River',
                'address' => 'Black River Gorges National Park, Mauritius',
                'lat' => -20.4186, 'lng' => 57.4514,
                'duration' => '3–5 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Täglich 6–18 Uhr',
                'parking_information' => 'Parkplätze an mehreren Eingängen',
                'arrival_information' => 'Mit dem Mietwagen über die Hauptstraße B9 erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['Letzter großer Regenwald der Insel', 'Endemischer Mauritius-Falke', 'Aussichtspunkt Alexandra Falls'],
                'categories' => ['wandern', 'natur-landschaft'],
                'labels' => ['wandern', 'natur', 'aktiv'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Île aux Cerfs',
                'short_description' => 'Traumhafte Insel mit türkiser Lagune vor der Ostküste.',
                'description' => "Die Île aux Cerfs gilt als eine der schönsten Inseln vor Mauritius und lockt mit puderweißen Stränden und kristallklarem, türkisfarbenem Wasser. Die Insel ist ausschließlich per Boot erreichbar, was ihr trotz großer Beliebtheit einen exklusiven Charakter verleiht.\n\nNeben Baden und Schnorcheln bietet die Insel Wassersportmöglichkeiten wie Jetski und Parasailing sowie mehrere Restaurants direkt am Strand. Ein Golfplatz auf der Insel gehört zu den schönsten der Insel Mauritius.",
                'location_name' => 'Trou d\'Eau Douce',
                'address' => 'Île aux Cerfs, Mauritius',
                'lat' => -20.2667, 'lng' => 57.8000,
                'duration' => '4–6 Stunden',
                'difficulty' => null,
                'price_information' => 'Bootstour ab ca. 25 €',
                'opening_hours' => 'Boote ganztägig, saisonal abweichend',
                'parking_information' => 'Parkplatz am Bootsanleger Trou d\'Eau Douce',
                'arrival_information' => 'Mit dem Boot ab Trou d\'Eau Douce in ca. 20 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['Türkise Lagune', 'Nur per Boot erreichbar', 'Wassersport und Golfplatz'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'sommer', 'natur'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Port Louis Caudan Waterfront',
                'short_description' => 'Lebendige Hafenpromenade der Inselhauptstadt.',
                'description' => "Die Caudan Waterfront bildet das moderne Herz der Hauptstadt Port Louis und verbindet Einkaufszentren, Restaurants und ein Kasino direkt am Hafenbecken. Von hier aus lässt sich der Kontrast zwischen kolonialer Architektur und moderner Stadtentwicklung gut erleben.\n\nNur wenige Schritte entfernt liegt der historische Central Market mit seinen Gewürz-, Obst- und Souvenirständen sowie das Blue Penny Museum. Ein Spaziergang entlang der Promenade lässt sich gut mit einem Bummel durch die Altstadt von Port Louis verbinden.",
                'location_name' => 'Port Louis',
                'address' => 'Caudan Waterfront, Port Louis',
                'lat' => -20.1567, 'lng' => 57.4989,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Geschäfte meist 10–20 Uhr',
                'parking_information' => 'Parkhaus an der Waterfront',
                'arrival_information' => 'Mit dem Bus oder Taxi ab jedem Ort der Insel erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Moderne Hafenpromenade', 'Nähe zum Central Market', 'Blue Penny Museum'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Grand Baie',
                'short_description' => 'Belebtes Touristenzentrum im Norden der Insel.',
                'description' => "Grand Baie zählt zu den touristischen Zentren im Norden von Mauritius und bietet eine große Auswahl an Restaurants, Bars und Geschäften direkt an einer geschützten Bucht. Die Uferpromenade lädt abends zum Flanieren zwischen Straßenmusikern und Souvenirständen ein.\n\nVon Grand Baie aus starten zahlreiche Bootsausflüge zu den vorgelagerten Inseln im Norden sowie Katamaranfahrten entlang der Küste. Tagsüber laden mehrere kleine Buchten mit ruhigem, flachem Wasser zum Baden ein.",
                'location_name' => 'Grand Baie',
                'address' => 'Grand Baie, Mauritius',
                'lat' => -20.0186, 'lng' => 57.5806,
                'duration' => '2–4 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Ausflüge kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze entlang der Uferpromenade',
                'arrival_information' => 'Mit dem Mietwagen oder Bus im Norden der Insel erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Lebendige Uferpromenade', 'Ausgangspunkt für Bootsausflüge', 'Geschützte Badebuchten'],
                'categories' => ['seen-baden', 'kulinarik'],
                'labels' => ['familie', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Trou aux Biches',
                'short_description' => 'Einer der schönsten öffentlichen Strände der Insel.',
                'description' => "Trou aux Biches gilt regelmäßig als einer der schönsten Strände von Mauritius und besticht mit puderweißem Sand und einer flachen, ruhigen Lagune, die sich hervorragend zum Schwimmen und Schnorcheln eignet. Casuarina-Bäume spenden entlang des Strandes angenehmen Schatten.\n\nAnders als viele Hotelstrände ist Trou aux Biches öffentlich zugänglich und bei Einheimischen wie Reisenden gleichermaßen beliebt. Mehrere kleine Restaurants und Verleihstationen für Schnorchelausrüstung liegen direkt am Strand.",
                'location_name' => 'Trou aux Biches',
                'address' => 'Trou aux Biches, Mauritius',
                'lat' => -20.0347, 'lng' => 57.5486,
                'duration' => '2–4 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Öffentliche Parkplätze am Strand',
                'arrival_information' => 'Mit dem Mietwagen oder Bus im Nordwesten der Insel erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['Puderweißer, öffentlicher Strand', 'Flache Lagune zum Schnorcheln', 'Schattenspendende Casuarina-Bäume'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'sommer', 'natur'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Sir Seewoosagur Ramgoolam Botanical Garden',
                'short_description' => 'Weltberühmter botanischer Garten mit Riesenseerosen.',
                'description' => "Der botanische Garten von Pamplemousses zählt zu den ältesten der südlichen Hemisphäre und ist weltberühmt für seine riesigen Victoria-Seerosen mit bis zu zwei Metern Durchmesser. Über 80 Palmenarten und zahlreiche exotische Gewächse aus aller Welt gedeihen auf dem weitläufigen Gelände.\n\nEin Rundgang mit lokalem Guide erklärt die Geschichte und Besonderheiten der einzelnen Pflanzenarten anschaulich. Der Garten ist ein ruhiges, schattiges Ausflugsziel und eignet sich gut als Ergänzung zu einem Besuch in Port Louis.",
                'location_name' => 'Pamplemousses',
                'address' => 'Sir Seewoosagur Ramgoolam Botanical Garden, Pamplemousses',
                'lat' => -20.1019, 'lng' => 57.5789,
                'duration' => '1,5–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 6 €',
                'opening_hours' => 'Täglich 8:30–17 Uhr',
                'parking_information' => 'Parkplatz am Eingang',
                'arrival_information' => 'Mit dem Mietwagen oder Bus ab Port Louis in ca. 20 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Riesige Victoria-Seerosen', 'Über 80 Palmenarten', 'Einer der ältesten Gärten der Südhalbkugel'],
                'categories' => ['natur-landschaft', 'familie-ausflug'],
                'labels' => ['natur', 'familie'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Chamarel Wasserfall',
                'short_description' => 'Höchster Einzelwasserfall der Insel im Dschungel.',
                'description' => "Der Chamarel-Wasserfall stürzt aus rund 100 Metern Höhe in ein dicht bewaldetes Tal und ist der höchste Einzelwasserfall von Mauritius. Eine Aussichtsplattform ermöglicht einen ungehinderten Blick auf die tosenden Wassermassen inmitten üppiger tropischer Vegetation.\n\nDer Wasserfall liegt in unmittelbarer Nähe der Seven Coloured Earths und lässt sich gut mit einem Besuch dort kombinieren. Nach starken Regenfällen führt der Fall besonders viel Wasser und zeigt sich von seiner beeindruckendsten Seite.",
                'location_name' => 'Chamarel',
                'address' => 'Chamarel Waterfall, Chamarel',
                'lat' => -20.4306, 'lng' => 57.3781,
                'duration' => '30–45 Minuten',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 4 €',
                'opening_hours' => 'Täglich 7–17:30 Uhr',
                'parking_information' => 'Parkplatz an der Aussichtsplattform',
                'arrival_information' => 'Mit dem Mietwagen ab Chamarel in wenigen Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Höchster Einzelwasserfall der Insel', 'Aussichtsplattform im Dschungel', 'Nähe zu den Seven Coloured Earths'],
                'categories' => ['natur-landschaft'],
                'labels' => ['natur', 'geheimtipp'],
                'motif' => 'waterfall',
            ],
            [
                'title' => 'Casela Nature Parks',
                'short_description' => 'Abenteuerpark mit Löwen, Zebras und Zipline.',
                'description' => "Die Casela Nature Parks vereinen einen Wildpark mit afrikanischer Savannenlandschaft und ein Abenteuergelände mit Ziplines, Quad-Touren und Klettersteigen. Besucher können unter Aufsicht sogar mit Geparden spazieren gehen oder Löwen aus nächster Nähe beobachten.\n\nDer Park liegt am Fuß der markanten Berge von Rivière Noire und bietet zusätzlich Segway-Touren und einen kleinen Streichelzoo für jüngere Kinder. Damit ist Casela eines der vielseitigsten Familienausflugsziele der Insel.",
                'location_name' => 'Cascavelle',
                'address' => 'Casela Nature Parks, Cascavelle',
                'lat' => -20.2864, 'lng' => 57.4056,
                'duration' => '3–5 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 25 €, Aktivitäten zusätzlich',
                'opening_hours' => 'Täglich 9–17 Uhr',
                'parking_information' => 'Parkplatz am Eingang',
                'arrival_information' => 'Mit dem Mietwagen ab Flic en Flac in ca. 15 Minuten erreichbar',
                'website_url' => 'https://www.caselapark.com',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Wildpark mit Löwen und Zebras', 'Ziplines und Quad-Touren', 'Spaziergang mit Geparden'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'aktiv'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Belle Mare Beach',
                'short_description' => 'Kilometerlanger Traumstrand an der Ostküste.',
                'description' => "Belle Mare zählt zu den längsten und schönsten Sandstränden von Mauritius und liegt geschützt hinter einem vorgelagerten Riff, das für ruhiges, flaches Wasser sorgt. Feiner weißer Sand und hoch aufragende Palmen prägen das Bild dieses klassischen Postkartenstrands.\n\nDa der Strand über weite Strecken öffentlich zugänglich ist, lässt er sich auch ohne Hotelaufenthalt in der Umgebung genießen. Wassersportarten wie Kitesurfen und Stand-up-Paddling sind entlang des Strandes weit verbreitet.",
                'location_name' => 'Belle Mare',
                'address' => 'Belle Mare, Mauritius',
                'lat' => -20.2081, 'lng' => 57.7847,
                'duration' => '2–4 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Öffentliche Parkplätze am Strand',
                'arrival_information' => 'Mit dem Mietwagen an der Ostküste erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['Kilometerlanger weißer Sandstrand', 'Ruhiges Wasser hinter dem Riff', 'Beliebt zum Kitesurfen'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Grand Bassin (Ganga Talao)',
                'short_description' => 'Heiliger Kratersee und wichtigstes Hindu-Pilgerziel der Insel.',
                'description' => "Grand Bassin, auch Ganga Talao genannt, ist ein Kratersee im Hochland von Mauritius und das bedeutendste Pilgerziel der hinduistischen Bevölkerung außerhalb Indiens. Der Legende nach ist das Wasser des Sees mit dem heiligen Fluss Ganges verbunden.\n\nEine über 33 Meter hohe Statue des Gottes Shiva wacht über den See, umgeben von zahlreichen bunten Tempeln. Besonders während des Maha-Shivaratri-Festivals pilgern hunderttausende Gläubige aus dem ganzen Land hierher.",
                'location_name' => 'Vacoas-Phoenix',
                'address' => 'Grand Bassin, Mauritius',
                'lat' => -20.4106, 'lng' => 57.4886,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplatz am Tempelgelände',
                'arrival_information' => 'Mit dem Mietwagen im zentralen Hochland erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Wichtigstes Hindu-Pilgerziel außerhalb Indiens', 'Über 33 Meter hohe Shiva-Statue', 'Bunte Tempelanlagen am Kratersee'],
                'categories' => ['kultur-geschichte', 'natur-landschaft'],
                'labels' => ['kultur', 'natur'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Flic en Flac',
                'short_description' => 'Beliebter Badeort mit Sonnenuntergängen über dem Meer.',
                'description' => "Flic en Flac an der Westküste ist einer der beliebtesten Badeorte von Mauritius und bekannt für seine spektakulären Sonnenuntergänge über dem offenen Meer. Ein langer, öffentlicher Sandstrand mit Casuarina-Bäumen bietet Platz für Badegäste und Familien.\n\nVor der Küste liegt ein Korallenriff, das sich hervorragend zum Schnorcheln und Tauchen eignet. Zahlreiche Restaurants und kleine Boutiquen entlang der Strandpromenade machen Flic en Flac zu einem lebendigen Ferienort.",
                'location_name' => 'Flic en Flac',
                'address' => 'Flic en Flac, Mauritius',
                'lat' => -20.2772, 'lng' => 57.3644,
                'duration' => '2–4 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Öffentliche Parkplätze am Strand',
                'arrival_information' => 'Mit dem Mietwagen an der Westküste erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['Spektakuläre Sonnenuntergänge', 'Schnorcheln am Korallenriff', 'Lebendige Strandpromenade'],
                'categories' => ['seen-baden', 'kulinarik'],
                'labels' => ['familie', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Île aux Aigrettes',
                'short_description' => 'Naturschutzinsel mit letzten Küstenwäldern der Insel.',
                'description' => "Die Île aux Aigrettes ist eine kleine Naturschutzinsel vor der Ostküste und beherbergt einen der letzten ursprünglichen Küstenwälder von Mauritius. Ein Artenschutzprogramm hat hier vom Aussterben bedrohte Tiere wie die Rosataube und die Aldabra-Riesenschildkröte wieder angesiedelt.\n\nGeführte Touren über die Insel erklären die einzigartige, endemische Flora und Fauna sowie die Bedeutung des Artenschutzprojekts. Die Insel ist ein Muss für alle, die sich für die ursprüngliche Natur von Mauritius abseits der Strände interessieren.",
                'location_name' => 'Pointe d\'Esny',
                'address' => 'Île aux Aigrettes, Mauritius',
                'lat' => -20.4211, 'lng' => 57.7186,
                'duration' => '2–3 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Geführte Tour ab ca. 25 €',
                'opening_hours' => 'Touren nach Voranmeldung, Di–So',
                'parking_information' => 'Parkplatz am Bootsanleger Pointe d\'Esny',
                'arrival_information' => 'Mit dem Boot ab Pointe d\'Esny in wenigen Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Letzter ursprünglicher Küstenwald', 'Artenschutzprojekt mit Riesenschildkröten', 'Geführte Naturtouren'],
                'categories' => ['natur-landschaft'],
                'labels' => ['natur', 'geheimtipp'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Rochester Falls',
                'short_description' => 'Wasserfall mit ungewöhnlich geometrischen Felsformationen.',
                'description' => "Die Rochester Falls im Süden von Mauritius stürzen über auffällig rechteckige, fast künstlich wirkende Basaltformationen in ein kleines Becken. Die geometrischen Felsstrukturen entstanden durch die Abkühlung von Lavaströmen und sind ein seltenes geologisches Phänomen.\n\nDer Wasserfall liegt versteckt in einem Zuckerrohrfeld und ist über einen kurzen, unbefestigten Weg erreichbar. Bei ausreichend Wasserstand lässt sich im Becken unterhalb des Falls auch baden.",
                'location_name' => 'Souillac',
                'address' => 'Rochester Falls, Souillac',
                'lat' => -20.5158, 'lng' => 57.5486,
                'duration' => '45–60 Minuten',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig zugänglich',
                'parking_information' => 'Kleiner Parkplatz am Wegbeginn',
                'arrival_information' => 'Mit dem Mietwagen ab Souillac in wenigen Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Geometrische Basaltformationen', 'Verstecktes Ausflugsziel im Zuckerrohrfeld', 'Bademöglichkeit im Becken'],
                'categories' => ['natur-landschaft'],
                'labels' => ['natur', 'geheimtipp'],
                'motif' => 'waterfall',
            ],
            [
                'title' => 'Blue Bay Marine Park',
                'short_description' => 'Geschütztes Meeresgebiet mit intaktem Korallenriff.',
                'description' => "Der Blue Bay Marine Park im Südosten von Mauritius schützt eines der artenreichsten Korallenriffe der Insel mit außergewöhnlich klarem Wasser. Glasboden-Boote ermöglichen auch Nicht-Schnorchlern einen Blick auf die bunte Unterwasserwelt.\n\nDer angrenzende Sandstrand ist von Filao-Bäumen gesäumt und deutlich ruhiger als die touristischeren Strände im Norden der Insel. Schnorchelausrüstung lässt sich direkt am Strand ausleihen, um die Korallengärten auf eigene Faust zu erkunden.",
                'location_name' => 'Blue Bay',
                'address' => 'Blue Bay Marine Park, Mauritius',
                'lat' => -20.4406, 'lng' => 57.7156,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Bootstouren kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplatz am Strand von Blue Bay',
                'arrival_information' => 'Mit dem Mietwagen im Südosten der Insel erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['Artenreiches Korallenriff', 'Glasboden-Bootstouren', 'Ruhiger Strand abseits des Trubels'],
                'categories' => ['seen-baden', 'natur-landschaft'],
                'labels' => ['natur', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Aapravasi Ghat',
                'short_description' => 'UNESCO-Weltkulturerbestätte zur Geschichte der Vertragsarbeiter.',
                'description' => "Der Aapravasi Ghat in Port Louis erinnert an die Ankunft hunderttausender indischer Vertragsarbeiter, die ab 1834 über diesen Ort nach Mauritius kamen und die kulturelle Zusammensetzung der Insel bis heute prägen. Die erhaltenen Gebäude zählen zum UNESCO-Weltkulturerbe.\n\nEin kleines Besucherzentrum dokumentiert mit Fotografien und Dokumenten die bewegte Geschichte der Migration. Der Ort bietet einen wichtigen historischen Kontrapunkt zu den touristischen Stränden der Insel.",
                'location_name' => 'Port Louis',
                'address' => '1 Quay Street, Port Louis',
                'lat' => -20.1594, 'lng' => 57.5008,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 3 €',
                'opening_hours' => 'Mo–Fr 9–16 Uhr',
                'parking_information' => 'Parkhaus in der Nähe der Caudan Waterfront',
                'arrival_information' => 'Fußläufig von der Caudan Waterfront erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.3,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['UNESCO-Weltkulturerbe', 'Geschichte der indischen Vertragsarbeiter', 'Nähe zur Caudan Waterfront'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'La Vanille Nature Park',
                'short_description' => 'Park mit der weltweit größten Ansammlung von Riesenschildkröten.',
                'description' => "Der La Vanille Nature Park im Süden von Mauritius beherbergt die größte Ansammlung von Aldabra-Riesenschildkröten weltweit, von denen einige über 100 Jahre alt sind. Besucher können die sanften Riesen aus nächster Nähe beobachten und sogar füttern.\n\nNeben den Schildkröten zeigt der Park Krokodile, einheimische Flughunde und ein kleines Insektarium. Der Park liegt in einem üppigen, tropischen Gartenareal und eignet sich hervorragend für einen Familienausflug.",
                'location_name' => 'Rivière des Anguilles',
                'address' => 'La Vanille Nature Park, Rivière des Anguilles',
                'lat' => -20.5044, 'lng' => 57.5111,
                'duration' => '2–2,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 16 €',
                'opening_hours' => 'Täglich 9:30–17 Uhr',
                'parking_information' => 'Parkplatz am Eingang',
                'arrival_information' => 'Mit dem Mietwagen im Süden der Insel erreichbar',
                'website_url' => 'https://www.lavanille-naturepark.com',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Größte Riesenschildkröten-Kolonie weltweit', 'Krokodile und Flughunde', 'Familienfreundlicher Rundgang'],
                'categories' => ['familie-ausflug', 'natur-landschaft'],
                'labels' => ['familie', 'natur'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Tamarin Bay',
                'short_description' => 'Beliebte Surfbucht mit Delfinbeobachtungen.',
                'description' => "Tamarin Bay an der Westküste ist bekannt für ihre zuverlässigen Wellen und zählt zu den besten Surfspots von Mauritius. Zugleich patrouillieren regelmäßig Gruppen von Spinnerdelfinen in der Bucht, die sich bei Bootsausflügen am frühen Morgen beobachten lassen.\n\nDer Ort selbst ist deutlich ruhiger und ursprünglicher als die touristischeren Küstenabschnitte und bietet einen authentischen Einblick in das mauritische Küstenleben. Ein Spaziergang entlang der Bucht bei Sonnenuntergang gehört zu den schönsten Erlebnissen der Westküste.",
                'location_name' => 'Tamarin',
                'address' => 'Tamarin Bay, Mauritius',
                'lat' => -20.3253, 'lng' => 57.3689,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Bootstouren kostenpflichtig',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze am Strand von Tamarin',
                'arrival_information' => 'Mit dem Mietwagen an der Westküste erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Dezember',
                'highlights' => ['Beliebter Surfspot', 'Delfinbeobachtungen am Morgen', 'Ursprüngliches Küstendorf'],
                'categories' => ['seen-baden', 'natur-landschaft'],
                'labels' => ['aktiv', 'natur', 'geheimtipp'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Gris Gris und Roche qui Pleure',
                'short_description' => 'Wilde Steilküste mit tosender Brandung im Süden.',
                'description' => "Der Küstenabschnitt bei Gris Gris im Süden von Mauritius zeigt eine völlig andere Seite der Insel als die ruhigen Lagunen im Norden: Hier trifft der offene Indische Ozean ungebremst auf schroffe Klippen. Der markante Felsen Roche qui Pleure „weint“ bei Wellenschlag sichtbar Wasser über seine Kante.\n\nEin Küstenweg entlang der Klippen bietet spektakuläre Ausblicke auf die tosende Brandung. Der Ort ist deutlich weniger besucht als die Nordküste und zeigt Mauritius von seiner wilden, ungezähmten Seite.",
                'location_name' => 'Souillac',
                'address' => 'Gris Gris, Souillac',
                'lat' => -20.5225, 'lng' => 57.5297,
                'duration' => '1–1,5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplatz an der Klippe',
                'arrival_information' => 'Mit dem Mietwagen ab Souillac in wenigen Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Wilde Steilküste am offenen Ozean', 'Markanter Felsen Roche qui Pleure', 'Wenig besuchter Küstenabschnitt'],
                'categories' => ['aussicht-panorama', 'natur-landschaft'],
                'labels' => ['natur', 'geheimtipp'],
                'motif' => 'canyon',
            ],
        ];
    }
}
