<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class SuedtirolSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#8fb8d9',
        'sky_bottom' => '#f4e3c1',
        'accent' => '#e8b04b',
        'layers' => ['#c98a6d', '#8a5a4a', '#4a3b39'],
        'water' => '#3f7f97',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'suedtirol'],
            [
                'name' => 'Südtirol',
                'type' => 'Region',
                'country' => 'Italien',
                'federal_state' => 'Trentino-Südtirol',
                'short_description' => 'Dolomiten, Weinberge und italienische Lebensfreude',
                'description' => "Südtirol vereint schroffe Dolomitengipfel, sonnige Weinhänge und historische Altstädte auf engstem Raum. Zwischen Bozen, Meran und den Ladiner Tälern wechseln sich alpine Bergseen, jahrhundertealte Burgen und erstklassige Kulinarik ab. Wer hier unterwegs ist, findet an einem Vormittag ruhige Waalwege durch Apfelplantagen und am Nachmittag Panoramen, die zu den spektakulärsten der Alpen zählen.\n\nDie Region punktet mit einer außergewöhnlichen Dichte an gut ausgeschilderten Wander- und Almwegen, die für Familien ebenso geeignet sind wie für ambitionierte Bergsteiger. Dazu kommt eine lebendige Kulturszene aus Südtiroler und italienischer Tradition, die sich in Küche, Architektur und Festen widerspiegelt.",
                'hero_image' => 'regions/suedtirol/suedtirol-1.jpg',
                'latitude' => 46.4983,
                'longitude' => 11.3548,
                'best_travel_time' => 'Mai bis Oktober für Wandern, Dezember bis März für Wintersport',
                'arrival_information' => 'Nächstgelegene Flughäfen: Bozen, Innsbruck, Verona und München. Gute Zuganbindung über Bozen und Meran, Autobahnausfahrten der A22 Brennerautobahn.',
                'seo_title' => 'Südtirol Reisetipps – Dolomiten, Almen & Altstädte | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele in Südtirol: Bergseen, Wanderwege, Burgen und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 1,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/suedtirol', 'suedtirol', 'mountains', $this->palette, 'Dolomitenpanorama mit Almwiesen in Südtirol', true, 0);
        MediaSeederHelper::attach($region, 'regions/suedtirol', 'suedtirol', 'lake', $this->palette, 'Bergsee vor Dolomitenkulisse in Südtirol', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['natur', 'wandern', 'familie', 'kultur'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' in Südtirol | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Kalterer See',
                'short_description' => 'Der wärmste Badesee der Alpen mit flachem Ufer und Weinbergblick.',
                'description' => "Der Kalterer See gilt als einer der wärmsten Badeseen der Alpen und ist deshalb schon im Frühsommer angenehm temperiert. Flache Uferzonen, Liegewiesen und mehrere Bootsverleihe machen ihn zu einem beliebten Ziel für Familien und alle, die einen entspannten Tag am Wasser suchen.\n\nRund um den See erstrecken sich sanfte Weinberge, durch die ein flacher Rundweg führt – ideal für einen Spaziergang nach dem Baden. Mehrere Restaurants und Buschenschänken laden zur Einkehr mit Südtiroler Weinen ein.",
                'location_name' => 'Kaltern an der Weinstraße',
                'address' => 'Seepromenade, 39052 Kaltern, Südtirol',
                'lat' => 46.4064, 'lng' => 11.2452,
                'duration' => '2–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Freier Zugang, Liegewiesenbereiche teils kostenpflichtig (ca. 5 €)',
                'opening_hours' => 'Ganzjährig frei zugänglich, Infrastruktur von Mai bis September geöffnet',
                'parking_information' => 'Mehrere kostenpflichtige Parkplätze rund um den See',
                'arrival_information' => 'Von Bozen ca. 20 Minuten mit dem Auto oder mit der Buslinie 121/122',
                'website_url' => 'https://www.kalterersee.com',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Mai bis September',
                'highlights' => ['Wärmster Badesee der Alpen', 'Flacher Rundweg durch die Weinberge', 'Zahlreiche Buschenschänken am Ufer'],
                'categories' => ['seen-baden', 'familie-ausflug'],
                'labels' => ['familie', 'natur', 'seen', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Marlinger Waalweg',
                'short_description' => 'Einer der schönsten Waalwege Südtirols entlang historischer Bewässerungskanäle.',
                'description' => "Der Marlinger Waalweg zählt zu den bekanntesten Wanderwegen Südtirols und folgt über weite Strecken einem jahrhundertealten Bewässerungskanal, der einst Wasser aus dem Naturnser Tal in die Obstplantagen von Marling brachte. Der Weg verläuft nahezu eben durch Apfelgärten, Kastanienhaine und lichte Wälder mit Blick auf die Texelgruppe.\n\nUnterwegs laden mehrere Rastplätze und kleine Einkehrmöglichkeiten zur Pause ein. Der leichte Höhenverlauf macht die Strecke auch für Familien mit älteren Kindern gut machbar.",
                'location_name' => 'Marling bei Meran',
                'address' => 'Ausgangspunkt Töll, 39020 Marling, Südtirol',
                'lat' => 46.6516, 'lng' => 11.1264,
                'duration' => '3–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig geöffnet, beste Begehbarkeit April bis Oktober',
                'parking_information' => 'Parkplatz am Bahnhof Töll',
                'arrival_information' => 'Mit dem Zug bis Bahnhof Töll oder mit dem Auto über die Vinschgauer Staatsstraße',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Historischer Bewässerungskanal', 'Fast ebener Wegverlauf', 'Blick auf die Texelgruppe'],
                'categories' => ['wandern', 'natur-landschaft'],
                'labels' => ['wandern', 'natur', 'geheimtipp'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Gärten von Schloss Trauttmansdorff',
                'short_description' => 'Preisgekrönte botanische Gärten mit Blick über Meran.',
                'description' => "Die Gärten von Schloss Trauttmansdorff wurden mehrfach zum schönsten Park Italiens gewählt und vereinen auf terrassierten Hängen mediterrane, alpine und exotische Vegetation. Themenwelten wie der Sonnengarten, der Waldgarten und der Wasser- und Terrassengarten machen den Rundgang abwechslungsreich.\n\nIm Schloss selbst informiert das Touriseum über die Geschichte des Tourismus in Südtirol. Für Kinder gibt es Erlebnisstationen und einen Abenteuerspielplatz, für Erwachsene zahlreiche Aussichtspunkte über das Etschtal.",
                'location_name' => 'Meran',
                'address' => 'St.-Valentin-Straße 51a, 39012 Meran, Südtirol',
                'lat' => 46.6690, 'lng' => 11.1712,
                'duration' => '3–5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 14 €, ermäßigt für Familien und Kinder',
                'opening_hours' => 'April bis Oktober, täglich 9–18 Uhr (saisonal abweichend)',
                'parking_information' => 'Parkhaus am Areal vorhanden',
                'arrival_information' => 'Fußläufig vom Zentrum Meran über den Gilfpromenade erreichbar',
                'website_url' => 'https://www.trauttmansdorff.it',
                'phone' => '+39 0473 235730',
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Mehrfach ausgezeichneter Botanischer Garten', 'Touriseum im Schlossgebäude', 'Weitblick über das Etschtal'],
                'categories' => ['natur-landschaft', 'familie-ausflug', 'kultur-geschichte'],
                'labels' => ['familie', 'natur', 'kultur'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Seiser Alm',
                'short_description' => 'Europas größte Hochalm – ideal für Wanderungen mit der Familie.',
                'description' => "Die Seiser Alm ist mit über 50 Quadratkilometern die größte Hochalmwiese Europas und liegt eingebettet zwischen den markanten Silhouetten von Langkofel und Schlern. Weite, sanft geschwungene Almwiesen laden zu Wanderungen mit spektakulärem Panorama ein, ganz ohne große Höhenunterschiede.\n\nMehrere Umlaufbahnen und Sessellifte erschließen die Alm autofrei von Kastelruth und Seis aus. Im Sommer ein Wanderparadies für die ganze Familie, im Winter eines der größten zusammenhängenden Skigebiete der Dolomiten.",
                'location_name' => 'Kastelruth / Seis am Schlern',
                'address' => 'Compatsch, 39040 Kastelruth, Südtirol',
                'lat' => 46.5499, 'lng' => 11.6167,
                'duration' => 'Ganztägig',
                'difficulty' => 'leicht',
                'price_information' => 'Umlaufbahn ab ca. 18 € Hin- und Rückfahrt',
                'opening_hours' => 'Ganzjährig, Bahnen saisonal abhängig',
                'parking_information' => 'Autofreie Zone, Talstationen in Seis und Kastelruth mit Parkplätzen',
                'arrival_information' => 'Anreise über die Umlaufbahn ab Seis, Auto nur mit Sondergenehmigung erlaubt',
                'website_url' => 'https://www.seiseralm.it',
                'phone' => null,
                'rating' => 4.9,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Juni bis Oktober, Dezember bis März',
                'highlights' => ['Größte Hochalm Europas', 'Autofrei erreichbar', 'Blick auf Langkofel und Schlern'],
                'categories' => ['wandern', 'natur-landschaft', 'familie-ausflug'],
                'labels' => ['familie', 'wandern', 'natur', 'sommer', 'winter'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Hans-und-Paula-Steger-Weg',
                'short_description' => 'Panoramaweg auf der Seiser Alm mit Blick auf den Langkofel.',
                'description' => "Der Hans-und-Paula-Steger-Weg ist einer der schönsten Panoramawege der Seiser Alm und führt von Compatsch aus fast eben entlang der Almwiesen direkt auf den mächtigen Langkofel zu. Die Strecke ist auch mit Kinderwagen gut machbar und bietet durchgehend freie Sicht auf die Dolomitengipfel.\n\nAn mehreren Stellen laden Bänke zum Verweilen ein, unterwegs liegen zwei urige Almhütten mit Südtiroler Küche. Der Weg eignet sich hervorragend als leichter Einstieg in die Bergwelt der Seiser Alm.",
                'location_name' => 'Seiser Alm, Compatsch',
                'address' => 'Compatsch, 39040 Kastelruth, Südtirol',
                'lat' => 46.5480, 'lng' => 11.6100,
                'duration' => '2–3 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos, Anfahrt mit der Umlaufbahn kostenpflichtig',
                'opening_hours' => 'Juni bis Oktober frei begehbar',
                'parking_information' => 'Parkplatz an der Talstation Seis',
                'arrival_information' => 'Mit der Umlaufbahn nach Compatsch, von dort direkt zu Fuß',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Juni bis Oktober',
                'highlights' => ['Fast ebener Panoramaweg', 'Direkter Blick auf den Langkofel', 'Zwei Almhütten am Wegesrand'],
                'categories' => ['wandern', 'aussicht-panorama'],
                'labels' => ['wandern', 'natur', 'familie', 'sommer'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Meraner Altstadt',
                'short_description' => 'Mediterranes Flair, Lauben und Cafés in Südtirols zweitgrößter Stadt.',
                'description' => "Die Altstadt von Meran besticht durch ihre Verbindung aus alpiner und mediterraner Architektur. Die Meraner Lauben mit ihren Arkadengängen laden zum Bummeln und Einkaufen ein, während die Uferpromenaden entlang der Passer ein mildes, fast italienisches Klima spürbar machen.\n\nCafés, Weinstuben und kleine Boutiquen prägen das Stadtbild ebenso wie die Jugendstilgebäude entlang der Kurpromenade. Meran ist idealer Ausgangspunkt für Ausflüge in die umliegenden Weinberge und Bergtäler.",
                'location_name' => 'Meran',
                'address' => 'Lauben, 39012 Meran, Südtirol',
                'lat' => 46.6708, 'lng' => 11.1594,
                'duration' => '2–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich, Geschäfte meist 9–19 Uhr',
                'parking_information' => 'Mehrere Parkgaragen im Stadtzentrum',
                'arrival_information' => 'Gut mit dem Zug erreichbar, Bahnhof Meran zentral gelegen',
                'website_url' => 'https://www.meran.eu',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Historische Lauben mit Geschäften', 'Promenaden entlang der Passer', 'Jugendstilarchitektur'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Algunder Waalweg',
                'short_description' => 'Leichter Spazierweg entlang eines historischen Waalkanals bei Meran.',
                'description' => "Der Algunder Waalweg verläuft entlang eines der ältesten Bewässerungskanäle Südtirols und bietet einen ruhigen, schattigen Spazierweg durch Weinberge und Obstgärten oberhalb von Meran. Der nahezu ebene Weg ist auch für ungeübte Wanderer und Familien mit Kindern bestens geeignet.\n\nUnterwegs eröffnen sich immer wieder Ausblicke auf das Meraner Becken und die umliegenden Gipfel. Der Weg lässt sich gut mit einem Abstecher in das Dorfzentrum von Algund verbinden.",
                'location_name' => 'Algund bei Meran',
                'address' => 'Gaulschlucht, 39022 Algund, Südtirol',
                'lat' => 46.6767, 'lng' => 11.1391,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig geöffnet',
                'parking_information' => 'Kostenloser Parkplatz am Ortseingang Algund',
                'arrival_information' => 'Mit dem Bus ab Meran oder zu Fuß über die Gaulschlucht erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'März bis November',
                'highlights' => ['Historischer Waalkanal', 'Schattiger, ebener Weg', 'Blick auf das Meraner Becken'],
                'categories' => ['wandern', 'natur-landschaft'],
                'labels' => ['wandern', 'natur', 'geheimtipp', 'familie'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Partschinser Wasserfall',
                'short_description' => 'Einer der höchsten frei fallenden Wasserfälle der Alpen.',
                'description' => "Mit rund 97 Metern Fallhöhe zählt der Partschinser Wasserfall zu den beeindruckendsten Naturschauspielen Südtirols. Ein gut ausgebauter Weg führt entlang des Zielbachs direkt bis an den Fuß des Wasserfalls, wo die Gischt an heißen Sommertagen für angenehme Abkühlung sorgt.\n\nDer Rundweg ist familientauglich und größtenteils schattig, was ihn besonders im Sommer attraktiv macht. Eine kleine Themenausstellung entlang des Wegs erklärt die Entstehung des Naturdenkmals.",
                'location_name' => 'Partschins bei Meran',
                'address' => 'Zieltal, 39020 Partschins, Südtirol',
                'lat' => 46.6417, 'lng' => 11.0940,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Eintritt ca. 4 €',
                'opening_hours' => 'April bis Oktober, täglich 9–18 Uhr',
                'parking_information' => 'Parkplatz am Eingang des Zieltals',
                'arrival_information' => 'Mit dem Auto oder Bus bis Partschins, von dort ausgeschildert',
                'website_url' => 'https://www.partschins.com',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['97 Meter Fallhöhe', 'Schattiger Weg entlang des Zielbachs', 'Erfrischende Gischt im Sommer'],
                'categories' => ['natur-landschaft', 'seen-baden'],
                'labels' => ['natur', 'familie', 'sommer'],
                'motif' => 'waterfall',
            ],
            [
                'title' => 'Vigiljoch',
                'short_description' => 'Autofreier Bergrücken oberhalb von Lana mit Panoramablick.',
                'description' => "Das Vigiljoch oberhalb von Lana ist seit über hundert Jahren autofrei und nur mit der historischen Seilbahn erreichbar. Oben angekommen erwarten Besucher weite Almwiesen, lichte Lärchenwälder und ein Panorama, das von den Dolomiten bis zur Texelgruppe reicht.\n\nEin dichtes Netz an leichten Wanderwegen verbindet mehrere Aussichtspunkte und Almhütten. Die autofreie Atmosphäre macht das Vigiljoch zu einem besonders ruhigen Ausflugsziel abseits des Trubels.",
                'location_name' => 'Lana',
                'address' => 'St. Vigil, 39011 Lana, Südtirol',
                'lat' => 46.6122, 'lng' => 11.1281,
                'duration' => '3–5 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Seilbahn ab ca. 16 € Hin- und Rückfahrt',
                'opening_hours' => 'Mai bis Oktober, Seilbahn saisonal',
                'parking_information' => 'Parkplatz an der Talstation in Lana',
                'arrival_information' => 'Mit der Seilbahn ab Lana, autofrei am Berg',
                'website_url' => 'https://www.vigiljoch.com',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Autofreier Bergrücken', 'Historische Seilbahn', 'Panorama bis zur Texelgruppe'],
                'categories' => ['wandern', 'aussicht-panorama'],
                'labels' => ['wandern', 'natur', 'geheimtipp'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Hafling',
                'short_description' => 'Sonniges Hochplateau mit Blick auf die Texelgruppe – bekannt für Haflinger Pferde.',
                'description' => "Hafling liegt auf einem sonnenverwöhnten Hochplateau oberhalb von Meran und gab der berühmten Haflinger Pferderasse ihren Namen. Weite Wiesen, lichte Wälder und ein mildes Klima machen den Ort zu einem beliebten Ziel für Wanderungen und Reitausflüge.\n\nVon mehreren Aussichtspunkten reicht der Blick über das Etschtal bis zur Texelgruppe. Für Familien bietet Hafling ein entspanntes Bergerlebnis ohne große Höhenunterschiede.",
                'location_name' => 'Hafling (Avelengo)',
                'address' => 'Dorfplatz, 39010 Hafling, Südtirol',
                'lat' => 46.6167, 'lng' => 11.2333,
                'duration' => '2–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Öffentliche Parkplätze im Ortszentrum',
                'arrival_information' => 'Mit dem Auto oder Bus ab Meran über die Höhenstraße erreichbar',
                'website_url' => 'https://www.hafling-hochplateau.com',
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Heimat der Haflinger Pferde', 'Sonniges Hochplateau', 'Blick auf die Texelgruppe'],
                'categories' => ['natur-landschaft', 'familie-ausflug'],
                'labels' => ['familie', 'natur', 'sommer'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Knottnkino',
                'short_description' => 'Naturbühne mit Panoramablick über das Etschtal.',
                'description' => "Das Knottnkino ist eine felsige Aussichtsplattform oberhalb von Hafling, die ihren Namen von der kinoartigen Anordnung der Sitzstufen hat. Von hier öffnet sich ein weiter Blick über das Etschtal bis zu den Dolomiten – ein beliebtes Ziel bei Sonnenuntergang.\n\nDer Zustieg erfolgt über einen kurzen, gut markierten Wanderweg ab Hafling. Wegen der ungesicherten Felskante ist bei Kindern etwas Vorsicht geboten, der Ausblick entschädigt aber jede Anstrengung.",
                'location_name' => 'Hafling',
                'address' => 'Knottnkino, 39010 Hafling, Südtirol',
                'lat' => 46.6190, 'lng' => 11.2280,
                'duration' => '1–2 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig frei zugänglich',
                'parking_information' => 'Wanderparkplatz in Hafling',
                'arrival_information' => 'Zu Fuß ab Hafling in etwa 30 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => false, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Felsige Naturbühne', 'Panorama bis zu den Dolomiten', 'Beliebt bei Sonnenuntergang'],
                'categories' => ['aussicht-panorama', 'wandern'],
                'labels' => ['geheimtipp', 'natur', 'aktiv'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Schloss Tirol',
                'short_description' => 'Stammsitz der Grafen von Tirol mit Landesmuseum.',
                'description' => "Schloss Tirol thront hoch über Meran und gilt als Namensgeber und Wiege des Landes Tirol. Die mittelalterliche Burganlage beherbergt heute das Südtiroler Landesmuseum für Kultur- und Landesgeschichte mit umfangreichen Ausstellungen zur Geschichte der Region.\n\nSchon der Aufstieg zur Burg bietet immer neue Ausblicke auf das Etschtal und Meran. Die gut erhaltenen romanischen Portale zählen zu den bedeutendsten Kunstwerken ihrer Zeit in Mitteleuropa.",
                'location_name' => 'Dorf Tirol bei Meran',
                'address' => 'Schlossweg 24, 39019 Dorf Tirol, Südtirol',
                'lat' => 46.6858, 'lng' => 11.1494,
                'duration' => '2–3 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Erwachsene ca. 9 €',
                'opening_hours' => 'März bis November, Di–So 10–17 Uhr',
                'parking_information' => 'Parkplatz am Ortseingang von Dorf Tirol',
                'arrival_information' => 'Mit dem Bus ab Meran oder zu Fuß über den Tappeinerweg erreichbar',
                'website_url' => 'https://www.schlosstirol.it',
                'phone' => '+39 0473 220221',
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'März bis November',
                'highlights' => ['Namensgebende Burg Tirols', 'Südtiroler Landesmuseum', 'Romanische Portale'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur'],
                'motif' => 'castle',
            ],
            [
                'title' => 'Bozner Lauben',
                'short_description' => 'Historische Einkaufsstraße im Herzen der Landeshauptstadt.',
                'description' => "Die Bozner Lauben sind das pulsierende Zentrum der Südtiroler Landeshauptstadt. Unter den mittelalterlichen Arkadengängen reihen sich Geschäfte, Cafés und Marktstände aneinander, während gotische Fassaden von der langen Handelstradition der Stadt erzählen.\n\nGleich in der Nähe liegen der Waltherplatz mit dem Dom sowie der Obstmarkt, auf dem täglich frisches Obst und Gemüse aus der Region angeboten wird. Ideal für einen Stadtbummel mit anschließendem Café-Besuch.",
                'location_name' => 'Bozen',
                'address' => 'Bozner Lauben, 39100 Bozen, Südtirol',
                'lat' => 46.4983, 'lng' => 11.3548,
                'duration' => '1–3 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich, Geschäfte meist 9–19 Uhr',
                'parking_information' => 'Parkgaragen im Stadtzentrum',
                'arrival_information' => 'Zentral gelegen, gut zu Fuß vom Bahnhof Bozen erreichbar',
                'website_url' => 'https://www.bolzano-bozen.it',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Mittelalterliche Arkadengänge', 'Nähe zu Dom und Obstmarkt', 'Zahlreiche Cafés und Geschäfte'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Ötzi-Museum',
                'short_description' => 'Südtiroler Archäologiemuseum mit der weltberühmten Gletschermumie.',
                'description' => "Im Südtiroler Archäologiemuseum in Bozen wird Ötzi gezeigt, die weltberühmte Gletschermumie aus der Kupfersteinzeit. Multimediale Ausstellungen erklären den Fund in den Ötztaler Alpen sowie die Lebensweise und Ausrüstung des Mannes aus dem Eis.\n\nDas Museum ist besonders bei Regenwetter ein lohnendes Ziel und für Kinder ab dem Grundschulalter spannend aufbereitet. Ein Audioguide führt in mehreren Sprachen durch die Ausstellung.",
                'location_name' => 'Bozen',
                'address' => 'Museumstraße 43, 39100 Bozen, Südtirol',
                'lat' => 46.4996, 'lng' => 11.3540,
                'duration' => '1–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 13 €',
                'opening_hours' => 'Di–So 10–18 Uhr, im Sommer auch montags',
                'parking_information' => 'Parkgarage Museumstraße in Gehnähe',
                'arrival_information' => 'Fußläufig vom Bozner Stadtzentrum erreichbar',
                'website_url' => 'https://www.iceman.it',
                'phone' => '+39 0471 320100',
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Weltberühmte Gletschermumie Ötzi', 'Multimediale Ausstellung', 'Ideal bei Schlechtwetter'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'familie', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Rittner Horn',
                'short_description' => 'Aussichtsberg über dem Ritten mit Blick auf die Dolomiten.',
                'description' => "Das Rittner Horn ist der höchste Punkt des Ritten und bietet ein 360-Grad-Panorama von den Dolomiten bis zu den Sarntaler Alpen. Ein Sessellift bringt Besucher bequem in die Nähe des Gipfels, von dort führt ein kurzer Weg zur Aussichtsplattform.\n\nIm Sommer ist das Gebiet ein beliebter Ausgangspunkt für Wanderungen, im Winter für Skitouren und Schneeschuhwanderungen. Die Region rund um das Rittner Horn ist deutlich ruhiger als die bekannteren Dolomitenskigebiete.",
                'location_name' => 'Ritten',
                'address' => 'Rittner Horn, 39054 Klobenstein, Südtirol',
                'lat' => 46.5333, 'lng' => 11.4667,
                'duration' => '3–5 Stunden',
                'difficulty' => 'mittel',
                'price_information' => 'Sessellift ab ca. 12 € Hin- und Rückfahrt',
                'opening_hours' => 'Juni bis Oktober und Dezember bis März',
                'parking_information' => 'Parkplatz an der Talstation',
                'arrival_information' => 'Mit der Rittner Seilbahn ab Bozen, anschließend Sessellift',
                'website_url' => 'https://www.ritten.com',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Juni bis Oktober, Dezember bis März',
                'highlights' => ['360-Grad-Panorama', 'Ruhiges Wander- und Skigebiet', 'Blick auf die Sarntaler Alpen'],
                'categories' => ['wandern', 'aussicht-panorama'],
                'labels' => ['wandern', 'natur', 'winter', 'sommer'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Erdpyramiden am Ritten',
                'short_description' => 'Bizarre Felsformationen im Wald oberhalb von Bozen.',
                'description' => "Die Erdpyramiden am Ritten zählen zu den außergewöhnlichsten Naturphänomenen Südtirols. Erosion hat aus Moränenmaterial schlanke Felstürme geformt, die von schützenden Gesteinsblöcken auf ihrer Spitze gekrönt werden – ein faszinierender Anblick mitten im Wald.\n\nMehrere gut ausgeschilderte Rundwege führen von Lengmoos und Oberbozen zu den verschiedenen Gruppen der Erdpyramiden. Die Wanderung eignet sich auch für Familien und dauert je nach Route ein bis zwei Stunden.",
                'location_name' => 'Ritten',
                'address' => 'Lengmoos, 39054 Ritten, Südtirol',
                'lat' => 46.5228, 'lng' => 11.4189,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplatz in Lengmoos',
                'arrival_information' => 'Mit der Rittner Seilbahn ab Bozen, dann kurze Bahnfahrt oder Fußweg',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Bizarre Erosionsformationen', 'Gut ausgeschilderte Rundwege', 'Familienfreundliche Wanderung'],
                'categories' => ['natur-landschaft', 'wandern'],
                'labels' => ['natur', 'geheimtipp', 'familie'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Karersee',
                'short_description' => 'Smaragdgrüner Bergsee mit Spiegelbild des Latemar.',
                'description' => "Der Karersee ist berühmt für sein leuchtend türkis-smaragdgrünes Wasser, in dem sich bei ruhigen Bedingungen die Zacken des Latemar spiegeln. Ein kurzer Rundweg umrundet den See und bietet von mehreren Punkten aus die besten Fotomotive.\n\nDa der See selbst nicht zum Baden freigegeben ist, steht die Aussicht im Vordergrund. In unmittelbarer Nähe starten mehrere Wanderwege in Richtung Latemar und Rosengarten.",
                'location_name' => 'Welschnofen',
                'address' => 'Karerpass, 39056 Welschnofen, Südtirol',
                'lat' => 46.4239, 'lng' => 11.5670,
                'duration' => '1 Stunde',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Kostenpflichtiger Parkplatz direkt am See',
                'arrival_information' => 'Mit dem Auto oder Bus über die Karerpassstraße erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Smaragdgrünes Wasser', 'Spiegelbild des Latemar', 'Kurzer, leichter Rundweg'],
                'categories' => ['seen-baden', 'aussicht-panorama'],
                'labels' => ['natur', 'seen', 'familie'],
                'motif' => 'lake',
            ],
            [
                'title' => 'St. Magdalena in Villnöss',
                'short_description' => 'Ikonisches Kirchlein vor der Kulisse der Geislerspitzen.',
                'description' => "Das kleine Kirchlein St. Magdalena vor den schroffen Geislerspitzen zählt zu den meistfotografierten Motiven Südtirols. Die sanft geschwungenen Almwiesen des Villnösstals bilden den perfekten Vordergrund für die markanten Dolomitengipfel im Hintergrund.\n\nVon Zans aus führt ein leichter Spazierweg zum besten Fotopunkt oberhalb des Weilers St. Magdalena. Wer weiter möchte, kann von hier aus in Richtung Adolf-Munkel-Weg und Geisleralm weiterwandern.",
                'location_name' => 'Villnöss',
                'address' => 'St. Magdalena, 39040 Villnöss, Südtirol',
                'lat' => 46.6294, 'lng' => 11.7069,
                'duration' => '1–3 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplatz in Zans oder St. Magdalena',
                'arrival_information' => 'Mit dem Auto über Klausen ins Villnösstal, ausgeschildert',
                'website_url' => 'https://www.villnoess.com',
                'phone' => null,
                'rating' => 4.9,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Bekanntestes Fotomotiv Südtirols', 'Blick auf die Geislerspitzen', 'Ausgangspunkt für weitere Wanderungen'],
                'categories' => ['aussicht-panorama', 'kultur-geschichte', 'wandern'],
                'labels' => ['natur', 'wandern', 'sommer'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Pragser Wildsee',
                'short_description' => 'Türkisfarbener Bergsee, einer der meistbesuchten Orte der Dolomiten.',
                'description' => "Der Pragser Wildsee gehört zu den meistfotografierten Seen der Dolomiten und begeistert mit seiner intensiven türkisgrünen Farbe vor der Kulisse der Seekofelgruppe. Ein flacher Rundweg umrundet den gesamten See in etwa einer Stunde.\n\nAn der historischen Seepromenade lässt sich in Ruderbooten die Aussicht vom Wasser aus genießen. Wegen der hohen Besucherzahlen ist eine frühe Anreise oder die Nutzung des Shuttlebusses in der Hauptsaison empfehlenswert.",
                'location_name' => 'Prags',
                'address' => 'Pragser Wildsee, 39030 Prags, Südtirol',
                'lat' => 46.6883, 'lng' => 12.0947,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos, Parkgebühr bzw. Shuttlebus kostenpflichtig',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'In der Hauptsaison Zufahrtsbeschränkung, Shuttlebus ab Neu-Prags',
                'arrival_information' => 'Mit dem Auto über Niederdorf und Prags, in der Hochsaison mit Shuttlebus',
                'website_url' => 'https://www.prags.info',
                'phone' => null,
                'rating' => 4.9,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Juni bis September',
                'highlights' => ['Intensive türkisgrüne Wasserfarbe', 'Ruderboote am Ufer', 'Rundweg in etwa einer Stunde'],
                'categories' => ['seen-baden', 'aussicht-panorama'],
                'labels' => ['natur', 'seen', 'familie', 'sommer'],
                'motif' => 'lake',
            ],
            [
                'title' => 'Tappeinerweg',
                'short_description' => 'Meraner Panoramaweg mit mediterraner Vegetation über den Dächern der Stadt.',
                'description' => "Der Tappeinerweg zieht sich auf rund vier Kilometern oberhalb der Meraner Altstadt entlang und gilt als einer der schönsten Höhenwege Europas. Palmen, Kakteen und Zypressen säumen den Weg und schaffen ein mediterranes Flair mitten in den Alpen.\n\nImmer wieder eröffnen sich Ausblicke über Meran und das Etschtal. Der Weg ist nahezu eben, gut befestigt und lässt sich in beide Richtungen begehen – ein Spaziergang für jede Jahreszeit.",
                'location_name' => 'Meran',
                'address' => 'Tappeinerweg, 39012 Meran, Südtirol',
                'lat' => 46.6721, 'lng' => 11.1583,
                'duration' => '2–3 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig geöffnet',
                'parking_information' => 'Parkmöglichkeiten im Meraner Stadtzentrum',
                'arrival_information' => 'Mehrere Zugänge vom Meraner Stadtzentrum aus, u. a. bei der Seilbahn Meran 2000',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.8,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Mediterrane Vegetation', 'Nahezu ebener Höhenweg', 'Panorama über Meran'],
                'categories' => ['wandern', 'aussicht-panorama'],
                'labels' => ['wandern', 'natur', 'familie'],
                'motif' => 'town',
            ],
        ];
    }
}
