<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Label;
use App\Models\Region;
use App\Support\MediaSeederHelper;
use Illuminate\Database\Seeder;

class TrierSeeder extends Seeder
{
    private array $palette = [
        'sky_top' => '#a9c9e0',
        'sky_bottom' => '#f2e8d5',
        'accent' => '#e0b04a',
        'layers' => ['#8a7a6a', '#5a4a3a', '#3a2f28'],
        'water' => '#4a7a9a',
    ];

    public function run(): void
    {
        $region = Region::updateOrCreate(
            ['slug' => 'trier'],
            [
                'name' => 'Trier',
                'type' => 'Stadt',
                'country' => 'Deutschland',
                'federal_state' => 'Rheinland-Pfalz',
                'short_description' => 'Älteste Stadt Deutschlands mit römischem Erbe an der Mosel',
                'description' => "Trier blickt auf über 2.000 Jahre Geschichte zurück und gilt als älteste Stadt Deutschlands. Als einstige Kaiserresidenz des Römischen Reiches hinterließ die Stadt ein einzigartiges Ensemble antiker Bauwerke, das heute zum UNESCO-Weltkulturerbe zählt – allen voran die Porta Nigra, das größte erhaltene Stadttor nördlich der Alpen.\n\nZwischen wuchtigen Ruinen, einer lebendigen Altstadt und den sanften Weinbergen entlang der Mosel verbindet Trier Antike und Moderne auf kleinem Raum. Die Nähe zu Luxemburg und den Moseltälern macht die Stadt zu einem idealen Ausgangspunkt für Tagesausflüge in die Region.",
                'hero_image' => 'regions/trier/trier-hero-1.jpg',
                'latitude' => 49.7596,
                'longitude' => 6.6428,
                'best_travel_time' => 'April bis Oktober, Weihnachtsmarkt im Dezember',
                'arrival_information' => 'Nächstgelegene Flughäfen: Luxemburg, Frankfurt-Hahn und Saarbrücken. Guter Bahnanschluss über Koblenz und Luxemburg-Stadt, Autobahnanschluss über die A1/A64.',
                'seo_title' => 'Trier Reisetipps – Römisches Erbe & Mosel | Lieblingsorte',
                'seo_description' => 'Die schönsten Ausflugsziele in Trier: Römische Ruinen, Altstadt, Weinberge und Geheimtipps – handverlesen und mit Karte.',
                'is_published' => true,
                'sort_order' => 3,
            ]
        );

        $region->media()->delete();
        MediaSeederHelper::attach($region, 'regions/trier', 'trier-hero', 'town', $this->palette, 'Römische Porta Nigra in Trier', true, 0);
        MediaSeederHelper::attach($region, 'regions/trier', 'trier-hero', 'canyon', $this->palette, 'Moseltal bei Trier', false, 1);

        $region->labels()->sync(Label::whereIn('slug', ['kultur', 'familie', 'geheimtipp'])->pluck('id'));

        foreach ($this->tips() as $index => $tip) {
            $travelTip = $region->travelTips()->updateOrCreate(
                ['slug' => \Illuminate\Support\Str::slug($tip['title'], '-', 'de', ['ü' => 'ue', 'ä' => 'ae', 'ö' => 'oe', 'ß' => 'ss'])],
                [
                    'title' => $tip['title'],
                    'short_description' => $tip['short_description'],
                    'description' => $tip['description'],
                    'location_name' => $tip['location_name'],
                    'address' => $tip['address'],
                    'latitude' => $tip['lat'],
                    'longitude' => $tip['lng'],
                    'duration' => $tip['duration'],
                    'difficulty' => $tip['difficulty'],
                    'price_information' => $tip['price_information'],
                    'opening_hours' => $tip['opening_hours'],
                    'parking_information' => $tip['parking_information'],
                    'arrival_information' => $tip['arrival_information'],
                    'website_url' => $tip['website_url'],
                    'phone' => $tip['phone'],
                    'rating' => $tip['rating'],
                    'family_friendly' => $tip['family_friendly'],
                    'stroller_friendly' => $tip['stroller_friendly'],
                    'dog_friendly' => $tip['dog_friendly'],
                    'indoor' => $tip['indoor'],
                    'free_entry' => $tip['free_entry'],
                    'featured' => $tip['featured'],
                    'best_season' => $tip['best_season'],
                    'highlights' => $tip['highlights'],
                    'seo_title' => $tip['title'].' in Trier | Lieblingsorte',
                    'seo_description' => $tip['short_description'],
                    'is_published' => true,
                    'sort_order' => $index,
                ]
            );

            $travelTip->categories()->sync(Category::whereIn('slug', $tip['categories'])->pluck('id'));
            $travelTip->labels()->sync(Label::whereIn('slug', $tip['labels'])->pluck('id'));

            $travelTip->media()->delete();
            $slug = $travelTip->slug;
            MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – '.$tip['short_description'], true, 0);
            if ($tip['featured']) {
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 2', false, 1);
                MediaSeederHelper::attach($travelTip, "tips/{$slug}", $slug, $tip['motif'], $this->palette, $tip['title'].' – Impression 3', false, 2);
            }
        }
    }

    private function tips(): array
    {
        return [
            [
                'title' => 'Porta Nigra',
                'short_description' => 'Das größte erhaltene römische Stadttor nördlich der Alpen.',
                'description' => "Die Porta Nigra ist das Wahrzeichen Triers und das am besten erhaltene römische Stadttor der Welt. Aus dunklem Sandstein errichtet, diente sie einst als nördlicher Zugang zur römischen Stadtmauer und beeindruckt bis heute durch ihre wuchtige, fast unverwitterte Fassade.\n\nIm Inneren führt ein Rundgang über mehrere Stockwerke bis auf die Aussichtsplattform, von der sich ein weiter Blick über die Trierer Altstadt bietet. Multimediale Stationen erklären die wechselvolle Geschichte des Bauwerks vom römischen Stadttor bis zur mittelalterlichen Kirche.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Porta-Nigra-Platz, 54290 Trier',
                'lat' => 49.7592, 'lng' => 6.6425,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 4 €',
                'opening_hours' => 'Täglich 9–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkhaus am Porta-Nigra-Platz',
                'arrival_information' => 'Fußläufig vom Hauptbahnhof Trier in 10 Minuten erreichbar',
                'website_url' => 'https://www.trier-info.de',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => true,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Größtes erhaltenes römisches Stadttor', 'Aussichtsplattform über der Altstadt', 'UNESCO-Weltkulturerbe'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Trierer Dom St. Peter',
                'short_description' => 'Ältester Bischofssitz Deutschlands mit Baugeschichte über 1.700 Jahre.',
                'description' => "Der Trierer Dom St. Peter ist die älteste Bischofskirche Deutschlands und vereint Bauelemente aus römischer, romanischer, gotischer und barocker Zeit unter einem Dach. Der wuchtige Westbau aus römischer Zeit bildet bis heute den Kern des imposanten Gebäudes.\n\nIm Inneren beherbergt der Dom kostbare Kunstschätze, darunter den Domschatz mit dem Heiligen Rock, einer bedeutenden christlichen Reliquie. Direkt angrenzend lädt die Liebfrauenkirche, einer der frühesten gotischen Kirchenbauten Deutschlands, zur Besichtigung ein.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Liebfrauenstraße 12, 54290 Trier',
                'lat' => 49.7554, 'lng' => 6.6444,
                'duration' => '1–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Kostenlos, Domschatz kostenpflichtig',
                'opening_hours' => 'Täglich 6:30–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkhaus Domfreihof in Gehnähe',
                'arrival_information' => 'Fußläufig vom Hauptmarkt in wenigen Minuten erreichbar',
                'website_url' => 'https://www.dominformation.de',
                'phone' => null,
                'rating' => 4.7,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Ältester Bischofssitz Deutschlands', 'Domschatz mit dem Heiligen Rock', 'Angrenzende gotische Liebfrauenkirche'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'town',
            ],
            [
                'title' => 'Kaiserthermen',
                'short_description' => 'Monumentale römische Badeanlage aus der Spätantike.',
                'description' => "Die Kaiserthermen zählen zu den größten erhaltenen Thermenanlagen des Römischen Reiches außerhalb Roms. Die gewaltigen Ruinen der einstigen Badehallen lassen die Dimensionen der ursprünglichen Anlage eindrucksvoll erahnen.\n\nUnter der Anlage führt ein weitläufiges System von Gängen und Kanälen, das teilweise begehbar ist und einen seltenen Blick auf die römische Ingenieurskunst erlaubt. Info-Tafeln erklären die einstige Funktion der Räume anschaulich.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Weberbach 41, 54290 Trier',
                'lat' => 49.7481, 'lng' => 6.6486,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 4 €',
                'opening_hours' => 'Täglich 9–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz am Kaiserthermen-Areal',
                'arrival_information' => 'Fußläufig von der Trierer Altstadt in 10 Minuten erreichbar',
                'website_url' => 'https://www.trier-info.de',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Eine der größten Thermenanlagen des Römischen Reichs', 'Begehbare unterirdische Gänge', 'UNESCO-Weltkulturerbe'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Amphitheater Trier',
                'short_description' => 'Römische Arena für bis zu 20.000 Zuschauer.',
                'description' => "Das Trierer Amphitheater diente einst als Schauplatz für Gladiatorenkämpfe und Tierhetzen und bot Platz für rund 20.000 Zuschauer. Die in den Hang gebaute Arena ist bis heute in ihren Grundzügen gut erhalten.\n\nUnter der Arena liegt ein unterirdisches Kellergeschoss, das für die Vorbereitung der Kämpfe genutzt wurde und heute besichtigt werden kann. Im Sommer finden gelegentlich Freilichtveranstaltungen in der historischen Kulisse statt.",
                'location_name' => 'Trier',
                'address' => 'Olewiger Straße, 54295 Trier',
                'lat' => 49.7486, 'lng' => 6.6558,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 4 €',
                'opening_hours' => 'Täglich 9–18 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz direkt am Amphitheater',
                'arrival_information' => 'Mit dem Bus ab Trier Hauptbahnhof oder zu Fuß über die Kaiserthermen erreichbar',
                'website_url' => 'https://www.trier-info.de',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => false, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Arena für rund 20.000 Zuschauer', 'Begehbares unterirdisches Kellergeschoss', 'Gelegentliche Freilichtveranstaltungen'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur'],
                'motif' => 'town',
            ],
            [
                'title' => 'Liebfrauenkirche Trier',
                'short_description' => 'Eine der ältesten gotischen Kirchen Deutschlands.',
                'description' => "Die Liebfrauenkirche direkt neben dem Trierer Dom zählt zu den frühesten und bedeutendsten Bauwerken der Gotik in Deutschland. Der zentrale Grundriss in Form eines Kreuzes mit eingeschriebenem Rund ist in dieser Form einzigartig unter den deutschen Kirchenbauten.\n\nDas lichtdurchflutete Innere mit seinen schlanken Säulen und den historischen Grabmälern lädt zu einem ruhigen Rundgang ein. Die unmittelbare Nähe zum Dom ermöglicht eine gemeinsame Besichtigung beider Bauwerke.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Liebfrauenstraße 2, 54290 Trier',
                'lat' => 49.7551, 'lng' => 6.6440,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Täglich 9–18 Uhr',
                'parking_information' => 'Parkhaus Domfreihof in Gehnähe',
                'arrival_information' => 'Direkt neben dem Trierer Dom gelegen',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Eine der ältesten gotischen Kirchen Deutschlands', 'Einzigartiger zentraler Grundriss', 'Direkt neben dem Dom'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'town',
            ],
            [
                'title' => 'Barbarathermen',
                'short_description' => 'Ruinen einer der größten Thermenanlagen nördlich der Alpen.',
                'description' => "Die Barbarathermen am Moselufer gehörten einst zu den größten Badeanlagen des Römischen Reiches. Heute liegt die Anlage als weitläufiges Bodendenkmal frei, dessen Grundmauern die enorme Ausdehnung der einstigen Thermen erahnen lassen.\n\nEin Rundweg mit Informationstafeln führt durch die Ruinen und erklärt die einzelnen Badebereiche von den kalten bis zu den beheizten Räumen. Die Lage direkt an der Mosel macht einen Spaziergang hierher besonders reizvoll.",
                'location_name' => 'Trier',
                'address' => 'Südallee, 54290 Trier',
                'lat' => 49.7513, 'lng' => 6.6437,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig frei zugänglich',
                'parking_information' => 'Parkplätze an der Südallee',
                'arrival_information' => 'Fußläufig vom Trierer Stadtzentrum erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.2,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Eine der größten Thermenanlagen nördlich der Alpen', 'Freier Zugang ohne Eintritt', 'Lage direkt an der Mosel'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Römerbrücke Trier',
                'short_description' => 'Älteste erhaltene Brücke Deutschlands.',
                'description' => "Die Römerbrücke überspannt seit rund 2.000 Jahren die Mosel und gilt als älteste erhaltene Brücke Deutschlands. Die massiven Pfeiler aus römischem Basalt tragen bis heute den modernen Fahrbahnbelag und werden weiterhin für den Verkehr genutzt.\n\nEin Spaziergang über die Brücke verbindet die Trierer Altstadt mit dem gegenüberliegenden Moselufer und bietet schöne Blicke auf den Fluss. Besonders am Abend, wenn sich das Licht im Wasser spiegelt, lohnt sich ein Besuch.",
                'location_name' => 'Trier',
                'address' => 'Karl-Marx-Straße, 54290 Trier',
                'lat' => 49.7538, 'lng' => 6.6367,
                'duration' => '20–30 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig frei zugänglich',
                'parking_information' => 'Parkplätze am Moselufer',
                'arrival_information' => 'Fußläufig von der Trierer Altstadt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Älteste erhaltene Brücke Deutschlands', 'Original römische Pfeiler', 'Verbindung zur Trierer Altstadt'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Hauptmarkt Trier',
                'short_description' => 'Historischer Marktplatz im Herzen der Altstadt.',
                'description' => "Der Trierer Hauptmarkt bildet seit dem Mittelalter das Zentrum der Stadt und ist von prächtigen Bürgerhäusern, dem Marktkreuz und der Steipe umgeben. Cafés und Geschäfte laden zum Verweilen und Bummeln ein.\n\nRegelmäßig finden auf dem Platz Wochenmärkte und Veranstaltungen statt, im Advent verwandelt sich der Hauptmarkt in einen der schönsten Weihnachtsmärkte der Region. Von hier aus sind alle wichtigen Sehenswürdigkeiten der Altstadt fußläufig erreichbar.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Hauptmarkt, 54290 Trier',
                'lat' => 49.7566, 'lng' => 6.6414,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkhäuser in der Innenstadt',
                'arrival_information' => 'Zentral gelegen, gut zu Fuß erreichbar',
                'website_url' => 'https://www.trier-info.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Historisches Marktkreuz', 'Prächtige Bürgerhäuser', 'Beliebter Weihnachtsmarkt im Advent'],
                'categories' => ['kultur-geschichte', 'kulinarik'],
                'labels' => ['kultur', 'familie'],
                'motif' => 'town',
            ],
            [
                'title' => 'Karl-Marx-Haus',
                'short_description' => 'Geburtshaus von Karl Marx mit historischer Ausstellung.',
                'description' => "Im Geburtshaus von Karl Marx dokumentiert eine umfangreiche Ausstellung Leben und Werk des einflussreichen Philosophen und Ökonomen. Originaldokumente, Erstausgaben und multimediale Stationen zeichnen seinen Werdegang von Trier bis nach London nach.\n\nDas historische Bürgerhaus selbst vermittelt einen Eindruck vom großbürgerlichen Wohnen im frühen 19. Jahrhundert. Die Ausstellung ordnet Marx' Ideen zugleich in ihren historischen Kontext und ihre bis heute anhaltende Wirkung ein.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Brückenstraße 10, 54290 Trier',
                'lat' => 49.7538, 'lng' => 6.6392,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 5 €',
                'opening_hours' => 'Di–So 10–17 Uhr',
                'parking_information' => 'Parkhaus in der Innenstadt',
                'arrival_information' => 'Fußläufig vom Hauptmarkt erreichbar',
                'website_url' => 'https://www.fes.de/karl-marx-haus-trier',
                'phone' => null,
                'rating' => 4.3,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Original-Geburtshaus von Karl Marx', 'Umfangreiche Dokumentenausstellung', 'Ideal bei Schlechtwetter'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Basilika Trier (Aula Palatina)',
                'short_description' => 'Größter erhaltener Einraumbau der Antike.',
                'description' => "Die Trierer Basilika, einst Thronsaal Kaiser Konstantins, ist der größte erhaltene Einraumbau aus der römischen Antike. Die gewaltigen Ausmaße und die schlichte, klare Architektur beeindrucken bis heute jeden Besucher.\n\nHeute dient das Gebäude als evangelische Kirche und ist frei zugänglich. Der helle, fast schmucklose Innenraum lässt die enorme Höhe und Weite des römischen Bauwerks besonders eindrucksvoll wirken.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Konstantinplatz 10, 54290 Trier',
                'lat' => 49.7551, 'lng' => 6.6458,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Mo–Sa 10–17 Uhr, So ab 13 Uhr',
                'parking_information' => 'Parkhaus Domfreihof in Gehnähe',
                'arrival_information' => 'Fußläufig vom Dom und Hauptmarkt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Größter erhaltener Einraumbau der Antike', 'Einstiger Thronsaal Kaiser Konstantins', 'Kostenloser Eintritt'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Kurfürstliches Palais mit Palastgarten',
                'short_description' => 'Barockes Schloss mit prächtigem Rokoko-Garten.',
                'description' => "Das Kurfürstliche Palais zählt zu den schönsten Rokokobauten Deutschlands und liegt eingebettet in einen weitläufigen Palastgarten. Die rosafarbene Fassade und die aufwendigen Stuckarbeiten machen das Gebäude zu einem architektonischen Highlight der Stadt.\n\nDer angrenzende Palastgarten mit Springbrunnen, Skulpturen und gepflegten Rasenflächen lädt zum Spazieren und Verweilen ein. Besonders an sonnigen Tagen ist der Park ein beliebter Rückzugsort für Einheimische und Besucher.",
                'location_name' => 'Trier',
                'address' => 'Konstantinplatz, 54290 Trier',
                'lat' => 49.7545, 'lng' => 6.6474,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Kostenlos (Garten)',
                'opening_hours' => 'Garten ganztägig frei zugänglich',
                'parking_information' => 'Parkhaus Konstantinplatz',
                'arrival_information' => 'Fußläufig von der Basilika Trier erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => true,
                'best_season' => 'Mai bis September',
                'highlights' => ['Prächtiger Rokoko-Palast', 'Weitläufiger Palastgarten', 'Kostenloser Zugang zum Garten'],
                'categories' => ['kultur-geschichte', 'familie-ausflug'],
                'labels' => ['kultur', 'familie', 'natur'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Petrisberg Aussichtspunkt',
                'short_description' => 'Panoramablick über Trier und das Moseltal.',
                'description' => "Vom Petrisberg oberhalb der Trierer Universität öffnet sich ein weiter Panoramablick über die gesamte Stadt und das Moseltal bis zu den umliegenden Hügeln. Der ehemalige Kasernenstandort wurde zu einem großzügigen Park- und Wohngebiet mit Aussichtspunkten umgestaltet.\n\nMehrere Wege führen über das Gelände, vorbei an Kunstinstallationen und Sitzgelegenheiten. Der Petrisberg ist ein beliebtes Ausflugsziel für einen Spaziergang mit Panoramablick abseits der touristischen Altstadt.",
                'location_name' => 'Trier',
                'address' => 'Petrisberg, 54296 Trier',
                'lat' => 49.7469, 'lng' => 6.6672,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplätze am Wissenschaftspark',
                'arrival_information' => 'Mit dem Bus ab Trier Hauptbahnhof erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Panoramablick über Trier', 'Ruhiger Park abseits der Altstadt', 'Kunstinstallationen entlang der Wege'],
                'categories' => ['aussicht-panorama', 'familie-ausflug'],
                'labels' => ['geheimtipp', 'natur', 'familie'],
                'motif' => 'mountains',
            ],
            [
                'title' => 'Igeler Säule',
                'short_description' => 'Bestens erhaltenes römisches Grabmal bei Trier.',
                'description' => "Die Igeler Säule im nahen Ort Igel gilt als eines der besterhaltenen römischen Grabmäler nördlich der Alpen. Das über 20 Meter hohe Monument aus Sandstein ist reich mit Reliefs geschmückt, die Szenen aus dem Alltag einer wohlhabenden Trierer Kaufmannsfamilie zeigen.\n\nDie Säule steht bis heute an ihrem ursprünglichen Standort mitten im Ort und ist frei zugänglich. Ein kurzer Ausflug von Trier aus lohnt sich für alle, die sich für römische Grabkultur und Steinmetzkunst interessieren.",
                'location_name' => 'Igel bei Trier',
                'address' => 'Trierer Straße, 54298 Igel',
                'lat' => 49.7194, 'lng' => 6.4711,
                'duration' => '30–45 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig frei zugänglich',
                'parking_information' => 'Parkplätze im Ortszentrum Igel',
                'arrival_information' => 'Mit dem Auto oder Bus ab Trier in ca. 15 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Bestens erhaltenes römisches Grabmal', 'Reich verzierte Reliefs', 'Frei zugänglich im Ortszentrum'],
                'categories' => ['kultur-geschichte'],
                'labels' => ['kultur', 'geheimtipp'],
                'motif' => 'town',
            ],
            [
                'title' => 'Mosel-Radweg bei Trier',
                'short_description' => 'Flacher Radweg entlang der Mosel durch Weinberge.',
                'description' => "Der Mosel-Radweg führt von Trier aus flach und gut ausgebaut entlang des Flusses durch malerische Weinorte und Weinberge. Die Strecke eignet sich hervorragend für einen halbtägigen Ausflug mit dem Fahrrad, ganz ohne nennenswerte Steigungen.\n\nUnterwegs laden zahlreiche Winzerhöfe und Straußwirtschaften zur Rast ein. Der Radweg lässt sich beliebig verlängern oder verkürzen und ist auch für Familien mit Kindern gut geeignet.",
                'location_name' => 'Trier',
                'address' => 'Moselradweg, 54290 Trier',
                'lat' => 49.7440, 'lng' => 6.6580,
                'duration' => '2–4 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig befahrbar',
                'parking_information' => 'Parkplätze am Moselufer Trier',
                'arrival_information' => 'Start direkt am Trierer Moselufer',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Flacher, familienfreundlicher Radweg', 'Weinberge und Winzerhöfe am Wegesrand', 'Beliebig verlängerbare Strecke'],
                'categories' => ['wandern', 'natur-landschaft'],
                'labels' => ['aktiv', 'familie', 'sommer'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Olewiger Weinberge',
                'short_description' => 'Idyllisches Weindorf mit Steillagen direkt bei Trier.',
                'description' => "Der Trierer Stadtteil Olewig gilt als eines der ältesten Weindörfer der Region und liegt eingebettet zwischen steilen Weinbergterrassen. Enge Gassen mit historischen Winzerhäusern und zahlreiche Straußwirtschaften prägen das Ortsbild.\n\nEin Spaziergang durch die Weinberge oberhalb von Olewig bietet schöne Ausblicke auf Trier und die umliegenden Hänge. Besonders im Herbst zur Weinlese und bei den Straußwirtschaften im Sommer ist der Ort ein beliebtes Ausflugsziel.",
                'location_name' => 'Olewig, Trier',
                'address' => 'Weinkulturpfad, 54295 Trier',
                'lat' => 49.7433, 'lng' => 6.6644,
                'duration' => '1–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplätze im Ortskern Olewig',
                'arrival_information' => 'Mit dem Bus ab Trier Zentrum oder zu Fuß über das Amphitheater erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis Oktober',
                'highlights' => ['Historisches Weindorf', 'Steile Weinbergterrassen', 'Zahlreiche Straußwirtschaften'],
                'categories' => ['kulinarik', 'natur-landschaft'],
                'labels' => ['kulinarik', 'geheimtipp', 'sommer'],
                'motif' => 'garden',
            ],
            [
                'title' => 'Museum am Dom Trier',
                'short_description' => 'Bedeutende Sammlung christlicher Kunst und Archäologie.',
                'description' => "Das Museum am Dom zeigt eine der bedeutendsten Sammlungen christlicher Kunst in Deutschland, von römischen Deckenmalereien bis zu mittelalterlichen Skulpturen. Highlight der Sammlung sind die restaurierten Deckenfresken aus dem Palast Kaiser Konstantins.\n\nDie modernen Ausstellungsräume bieten viel Platz für die eindrucksvollen Exponate und sind auch bei schlechtem Wetter ein lohnendes Ziel. Die Nähe zum Dom ermöglicht eine Kombination mit dem Besuch der Kathedrale.",
                'location_name' => 'Trier Altstadt',
                'address' => 'Bischof-Stein-Platz 1, 54290 Trier',
                'lat' => 49.7559, 'lng' => 6.6448,
                'duration' => '1–1,5 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 6 €',
                'opening_hours' => 'Di–So 10–17 Uhr',
                'parking_information' => 'Parkhaus Domfreihof',
                'arrival_information' => 'Direkt neben dem Trierer Dom gelegen',
                'website_url' => 'https://www.museum-am-dom-trier.de',
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Restaurierte römische Deckenfresken', 'Bedeutende Sammlung christlicher Kunst', 'Ideal bei Schlechtwetter'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Basilika St. Matthias',
                'short_description' => 'Grabstätte des einzigen Apostelgrabs nördlich der Alpen.',
                'description' => "Die Basilika St. Matthias birgt das Grab des Apostels Matthias und ist damit die einzige Apostelgrabstätte nördlich der Alpen. Die romanische Kirche mit ihrer schlichten, ruhigen Architektur ist bis heute ein bedeutendes Pilgerziel.\n\nDie angrenzende Klosteranlage der Benediktiner lädt zu einem stillen Rundgang ein. Der etwas außerhalb der Altstadt gelegene Standort macht die Basilika zu einem ruhigeren Gegenpol zu den belebten römischen Sehenswürdigkeiten im Zentrum.",
                'location_name' => 'Trier',
                'address' => 'Matthiasstraße 85, 54290 Trier',
                'lat' => 49.7392, 'lng' => 6.6392,
                'duration' => '45–60 Minuten',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Täglich 6–19 Uhr, saisonal abweichend',
                'parking_information' => 'Parkplatz an der Basilika',
                'arrival_information' => 'Mit dem Bus ab Trier Zentrum oder zu Fuß in ca. 20 Minuten erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Ganzjährig',
                'highlights' => ['Einziges Apostelgrab nördlich der Alpen', 'Romanische Klosterkirche', 'Ruhiger Pilgerort abseits der Altstadt'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'geheimtipp', 'schlechtwetter'],
                'motif' => 'town',
            ],
            [
                'title' => 'Rheinisches Landesmuseum Trier',
                'short_description' => 'Größtes archäologisches Museum zur römischen Geschichte in Deutschland.',
                'description' => "Das Rheinische Landesmuseum Trier beherbergt eine der umfangreichsten Sammlungen zur römischen Geschichte in Deutschland, darunter das berühmte Neumagener Weinschiff und zahlreiche Grabmäler und Mosaiken. Die Ausstellung führt chronologisch durch die Geschichte der Region von der Steinzeit bis ins Mittelalter.\n\nModerne Rekonstruktionen und Multimediastationen machen das antike Alltagsleben anschaulich erlebbar. Das Museum liegt direkt neben den Kaiserthermen und lässt sich gut mit einem Rundgang durch die römischen Ausgrabungen verbinden.",
                'location_name' => 'Trier',
                'address' => 'Weimarer Allee 1, 54290 Trier',
                'lat' => 49.7498, 'lng' => 6.6473,
                'duration' => '1,5–2 Stunden',
                'difficulty' => null,
                'price_information' => 'Erwachsene ca. 8 €',
                'opening_hours' => 'Di–So 10–17 Uhr',
                'parking_information' => 'Parkplatz am Museum',
                'arrival_information' => 'Fußläufig von den Kaiserthermen erreichbar',
                'website_url' => 'https://www.landesmuseum-trier.de',
                'phone' => null,
                'rating' => 4.6,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => false, 'indoor' => true, 'free_entry' => false, 'featured' => false,
                'best_season' => 'Ganzjährig, besonders an Regentagen',
                'highlights' => ['Berühmtes Neumagener Weinschiff', 'Größte römische Sammlung Deutschlands', 'Direkt neben den Kaiserthermen'],
                'categories' => ['kultur-geschichte', 'indoor-schlechtwetter'],
                'labels' => ['kultur', 'schlechtwetter', 'familie'],
                'motif' => 'indoor',
            ],
            [
                'title' => 'Zurlaubener Ufer',
                'short_description' => 'Malerische Uferpromenade mit Fischerhäusern an der Mosel.',
                'description' => "Das Zurlaubener Ufer zählt zu den schönsten Ecken Triers und besticht durch seine bunten, historischen Fischerhäuser direkt an der Mosel. Die Promenade lädt zu einem entspannten Spaziergang entlang des Flusses ein.\n\nZahlreiche Cafés und Restaurants mit Terrassen direkt am Wasser machen das Zurlaubener Ufer besonders in den Sommermonaten zu einem beliebten Treffpunkt. Von hier starten auch Fahrgastschiffe zu Ausflügen auf der Mosel.",
                'location_name' => 'Trier',
                'address' => 'Zurlaubener Ufer, 54292 Trier',
                'lat' => 49.7602, 'lng' => 6.6321,
                'duration' => '1 Stunde',
                'difficulty' => null,
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganztägig frei zugänglich',
                'parking_information' => 'Parkplätze entlang des Ufers',
                'arrival_information' => 'Mit dem Bus oder zu Fuß von der Trierer Altstadt erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.5,
                'family_friendly' => true, 'stroller_friendly' => true, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'Mai bis September',
                'highlights' => ['Bunte historische Fischerhäuser', 'Cafés direkt am Moselufer', 'Anlegestelle für Flussschiffe'],
                'categories' => ['kulinarik', 'natur-landschaft'],
                'labels' => ['geheimtipp', 'familie', 'sommer'],
                'motif' => 'canyon',
            ],
            [
                'title' => 'Weisshaus Trier',
                'short_description' => 'Beliebter Aussichtspunkt und Ausflugsziel über der Stadt.',
                'description' => "Das Weisshaus oberhalb von Trier ist seit Generationen ein beliebtes Ausflugsziel und bietet einen schönen Blick auf die Stadt und das Moseltal. Ein Wald- und Wanderweg führt von der Innenstadt aus hinauf zum Aussichtspunkt.\n\nAn der historischen Ausflugsgaststätte lässt sich nach dem Spaziergang gemütlich einkehren. Der Weg eignet sich auch für einen entspannten Sonntagsspaziergang mit der ganzen Familie.",
                'location_name' => 'Trier',
                'address' => 'Weisshauswald, 54296 Trier',
                'lat' => 49.7373, 'lng' => 6.6558,
                'duration' => '1,5–2 Stunden',
                'difficulty' => 'leicht',
                'price_information' => 'Kostenlos',
                'opening_hours' => 'Ganzjährig zugänglich',
                'parking_information' => 'Parkplatz am Waldrand',
                'arrival_information' => 'Mit dem Bus ab Trier Zentrum oder zu Fuß über den Irscher Weg erreichbar',
                'website_url' => null,
                'phone' => null,
                'rating' => 4.4,
                'family_friendly' => true, 'stroller_friendly' => false, 'dog_friendly' => true, 'indoor' => false, 'free_entry' => true, 'featured' => false,
                'best_season' => 'April bis Oktober',
                'highlights' => ['Aussicht über Trier und das Moseltal', 'Historische Ausflugsgaststätte', 'Familienfreundlicher Waldweg'],
                'categories' => ['wandern', 'aussicht-panorama'],
                'labels' => ['geheimtipp', 'natur', 'familie'],
                'motif' => 'mountains',
            ],
        ];
    }
}
